### ISSUE TITLE
Reinforcement Learning

### ISSUE THREAD

**Issue by nooralahzadeh** [thunlp/OpenNRE#101]
Hi, I would be grateful if you could advice me where you implemented the reinforcement learning part , coming from following paper: 
"Reinforcement Learning for Relation Classification from Noisy Data"
Thanks

**Comment by gaotianyu1350** [comment]
Hi, currently you can find it in branch [old_version](https://github.com/thunlp/OpenNRE/tree/old_version). I'll add RL to master soon.

**Comment by gaotianyu1350** [comment]
RL has been added to master branch. Usage:

```
python train_demo.py nyt pcnn att rl
```
