### ISSUE TITLE
Tensor slice is too large to serialize

### ISSUE THREAD

**Issue by cgallay** [thunlp/OpenNRE#103]
Hi,
I changed the word embedding vector from a size of 50 to a size of 300 dimentions. But when training the model again I got this error:
```
Traceback (most recent call last):
  File "train_demo.py", line 103, in <module>
    framework.train(model, ckpt_dir="checkpoint", model_name=dataset_name + "_" + model.encoder + "_" + model.selector, max_epoch=60, gpu_nums=1)
  File "/notebooks/OpenNRE/nrekit/framework.py", line 207, in train
    path = saver.save(self.sess, os.path.join(ckpt_dir, model_name))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1458, in save
    meta_graph_filename, strip_default_attrs=strip_default_attrs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1496, in export_meta_graph
    graph_def=ops.get_default_graph().as_graph_def(add_shapes=True),
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3122, in as_graph_def
    result, _ = self._as_graph_def(from_version, add_shapes)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3080, in _as_graph_def
    c_api.TF_GraphToGraphDef(self._c_graph, buf)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot serialize protocol buffer of type tensorflow.GraphDefas the serialized size (2575910939bytes) would be larger than the limit (2147483647 bytes)
```

It happened to me at Epoch 16 after that the `auc` on the test set was better than previous ones so the code tried to store the best model. I find it strange that it was able to store the model previously with different weight. I was expecting the weight of the model to change for sure but not its size. Did you ever encounter this error?

**Comment by gaotianyu1350** [comment]
Hi~I think this is because that a new `model` instance will be generated each time it goes into test function, so the number of parameters will be larger and large and eventually it will exceed the limitation. It's a bad design and I'll fix it soon.

Hint: I implemented it this way mainly due to the need of multi gpu training (need multi `model` instances), but now I've figured a way to solve the problem more elegantly.

**Comment by xiongfeihtp** [comment]
I encounter the same problem!!!! Have you worked it out？

**Comment by xpxpx** [comment]
Because every test step, the function will create a new test model. And the saved model will be larger and larger.
I modify the author's code "framework.py".
`class re_framework:
    MODE_BAG = 0 # Train and test the model at bag level.
    MODE_INS = 1 # Train and test the model at instance level

    def __init__(self, train_data_loader, test_data_loader, max_length=120, batch_size=160):
        self.train_data_loader = train_data_loader
        self.test_data_loader = test_data_loader
        self.sess = None
        self.test_model = None`
and 
`def __test_bag__(self, model, ckpt=None, return_result=False):
        print("Testing...")
        if self.sess == None:
            self.sess = tf.Session()
        if self.test_model is None:
            model = model(self.test_data_loader, self.test_data_loader.batch_size, self.test_data_loader.max_length)
            self.test_model = model
        else:
            model = self.test_model`
Keep only one test model.
I test modified code. It can work.

**Comment by Morpheus6d** [comment]
Based on your thoughts, I modified the code, but it still went wrong, it is CHECK failed: (byte_size_before_serialization) == (byte_size_after_serialization): tensorflow.GraphDef was modified concurrently during serialization. terminate called after throwing an instance of 'google::protobuf::FatalException' what():  CHECK failed: (byte_size_before_serialization) == (byte_size_after_serialization): tensorflow.GraphDef was modified concurrently during serialization.
thank you!!
