### ISSUE TITLE
请教NYT数据集问题

### ISSUE THREAD

**Issue by dlongq** [thunlp/OpenNRE#104]
NYT是使用远程监督得到的，为什么在数据集中，有一些句子明明实体对相同，但是对应的关系却不同呢？相同的实体对使用远程监督不是只能产生一种关系嘛。

求解答，谢谢

比如：
m.053x3n	m.0fnb4	shamsur_rahman	dhaka	/people/deceased_person/place_of_death
m.053x3n	m.0fnb4	shamsur_rahman	dhaka	/people/deceased_person/place_of_death
m.053x3n	m.0fnb4	shamsur_rahman	dhaka	/people/deceased_person/place_of_death
m.053x3n	m.0fnb4	shamsur_rahman	dhaka	/people/person/place_of_birth
m.053x3n	m.0fnb4	shamsur_rahman	dhaka	/people/person/place_of_birth
m.053x3n	m.0fnb4	shamsur_rahman	dhaka	/people/person/place_of_birth

**Comment by THUCSTHanxu13** [comment]
同一个实体对可以有多种不同的关系，远距离监督会把这些关系都标注上，本质上这是个多实例多标签分类问题
