### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by cgallay** [thunlp/OpenNRE#108]
Hi,

I have just retrained the model using the `nyt` dataset. The accuracy on the test set seems to be around 40% for none NA relations. But when I try to build a simple test for prediction, the model isn't able to detect any relations (All the score for every relation are really low, something around 1%!!!). 
The input I gave was 
>Bastien was born in New York.
>Andrew works for Apple. inc since 2010.
>Peter is the son of Robert. Peter was born in 1993.
>Peter graduated from MIT in 2019. 
>Peter and his brother Andrew are French.

Which translate to this [json file](https://drive.google.com/open?id=1UQ7xgE-vhSfz8whVZtq5ekHRVmDyuAEC).
Is that normal, or am I using wrongly the model?

In the `nyt` dataset I realized that each entity contains a `type` filed, what's the importance of this filed is it used for training and prediction or not at all?

**Comment by gaotianyu1350** [comment]
You should add spaces around punctuations and delete `\n`. For example, sentence `Peter was born in 1993.\n` should be changed into `Peter was born in 1993 .`.

**Comment by cgallay** [comment]
@gaotianyu1350 Thanks for the correction I changed the input .json into [that](https://drive.google.com/open?id=1ckLrFfZk9pxDvDt5-iHFrbpldogwSQZW) but the scores are still really low.
Could you acknowledge that the input is now correctly formatted and if so do you obtain low scores too when predicting the relations using a `nyt_pcnn_att` model for that input?
