### ISSUE TITLE
rl的问题  不知道是不是bug

### ISSUE THREAD

**Issue by yuexjlu** [thunlp/OpenNRE#109]
不知道是否是bug：训练rl模型的时候，更新main_model的时候，调用的还是更新agent的代码

问题：不知道有没有理解错，更新agent的时候，主要依据ins_label的改变？ reward占的比例很小？ 不知道怎么体现reward的价值？能否解释一下。

谢谢

**Comment by qet2211pm** [comment]
我也想问这个问题，rl.py里面好像除了pretrian_main_model这一步以外之后的过程中没有更新main model了。然后policy gradient 更新我理解的代码好像也不是按照
<img width="302" alt="2019-01-07 10 36 34" src="https://user-images.githubusercontent.com/5837996/50746071-4977d680-1268-11e9-8dc0-40a0a4163676.png">
这个公式来的。

**Comment by mehrdad-naser-73** [comment]
Hi. I also noticed that the main model doesn't seem to get updated and the using rl only makes the results worse!
