### ISSUE TITLE
citation?

### ISSUE THREAD

**Issue by andriy-nikolov** [thunlp/OpenNRE#11]
Thanks for uploading the project! If I want to cite your work, how should I do it? Should I reference this Github project or do you have some document/report/paper to be cited?

**Comment by zibuyu** [comment]
Hi,

You can simply cite our ACL paper: [Lin et al., 2016] Yankai Lin, Shiqi
Shen, Zhiyuan Liu, Huanbo Luan, and Maosong Sun. Neural Relation Extraction
with Selective Attention over Instances. In Proceedings of ACL.

Thanks for your support.

Best regards,
Zhiyuan
