### ISSUE TITLE
新旧两版的测试效果为什么不一样呢

### ISSUE THREAD

**Issue by zxs1995** [thunlp/OpenNRE#112]
![image](https://user-images.githubusercontent.com/26573634/49568995-9e74b400-f96d-11e8-9a1a-b4bef66b6e22.png)
请问新旧两版的测试效果为什么不一样呢

**Comment by zxs1995** [comment]
您好，麻烦问一下为什么新旧两版的测试集不一样呀

**Comment by THUCSTHanxu13** [comment]
因为NYT-10原始的数据集合里面，有一些个别案例只在测试集合里出现，以及部分实体对既在训练集合里出现又在测试集合里出现。因为之前的关系抽取任务需要的是利用句子语义来判别关系，NYT-10虽然有实体对既出现在训练集又出现在测试集，但是训练集和测试集里的实体对对应的句子是不同的，所以之前任务使用NYT-10数据集合是不太注意这个问题的。但是我们的实验结果发现，关系抽取有时候模型会通过两个实体自身的意义直接判断关系，有这一层因素之后，NYT-10原来的数据集就会出现一些问题，测试集的信息可能会提前暴露，因而我们对数据集合进行了清洗和筛出来规避这种情况，因而两次的结果是不同的。

**Comment by THUCSTHanxu13** [comment]
🤔我们也在根据这些问题制作新的数据，近期可能会开出来给大家进行模型评测，大家可以关注下

**Comment by zxs1995** [comment]
好的谢谢您
