### ISSUE TITLE
About "Type" message

### ISSUE THREAD

**Issue by MrRace** [thunlp/OpenNRE#116]
From the train data we can see an instance below:
```
{
        "head": {
            "id": "/guid/9202a8c04000641f8000000000038574",
            "type": "/location/dated_location,/location/place_with_neighborhoods,/user/brendan/default_domain/top_architectural_city,/location/citytown,/location/location,/user/nitromaster101/default_domain/abh_city,/sports/sports_team_location,/common/topic,/location/statistical_region",
            "word": "Syracuse"
        },
        "relation": "/location/location/contains",
        "sentence": "She also oversaw the refinancing of the state Superfund law ; the creation of a plan for decontaminating heavily polluted Onondaga Lake , near Syracuse ; the acquisition of hundreds of thousands of acres of Adirondack woodlands ; and the imposition of tough new acid rain rules .",
        "tail": {
            "id": "/guid/9202a8c04000641f80000000002fe8e4",
            "type": "/common/topic,/geography/geographical_feature,/geography/lake,/geography/body_of_water,/location/location",
            "word": "Onondaga Lake"
        }
    }
```
Have you used the "type" message in your models?As I have not found  the place where you used them.

**Comment by GhadaAlfattni** [comment]
I have a quite similar question,
I it possible to add features to head and tail?

e.g., 

{
        "head": {
            "id": "/guid/9202a8c04000641f8000000000038574",
            "tense": "xxx",
            "word": "Syracuse"
        },
        "relation": "/location/location/contains",
        "sentence": "She also oversaw the refinancing of the state Superfund law ; the creation of a plan for decontaminating heavily polluted Onondaga Lake , near Syracuse ; the acquisition of hundreds of thousands of acres of Adirondack woodlands ; and the imposition of tough new acid rain rules .",
        "tail": {
            "id": "/guid/9202a8c04000641f80000000002fe8e4",
            "tense": "yyy",
            "word": "Onondaga Lake"
        }
    }

**Comment by gaotianyu1350** [comment]
In models that we provided we didn't use the `type` information, but there are some works utilizing additional information, for example, treating types of entities as one feature. Some models in the `neural encoder` part of [NREPapers](https://github.com/thunlp/NREPapers) contain the entity type embedding.
