### ISSUE TITLE
How do you train Word Embedding Data?

### ISSUE THREAD

**Issue by MrRace** [thunlp/OpenNRE#117]
What corpus do you use to train  Word Embedding Data( `word_vec.json` you provided) and how?

**Comment by gaotianyu1350** [comment]
You can refer to the [paper](http://www.aclweb.org/anthology/P16-1200) for detail. 

> In this paper, we use the word2vec tool to train the word embeddings on NYT corpus. We keep the words which appear more than 100 times in the corpus as vocabulary. Besides, we concatenate the words of an entity when it has multiple words.

You can also use other pre-trained word embeddings like Glove or models like ELMO or BERT.
