### ISSUE TITLE
关于数据集的问题Question of dataset

### ISSUE THREAD

**Issue by npc123456** [thunlp/OpenNRE#121]
你好：
最近在跑这个程序，我有几个问题一直搞不明白，看了之前的问题，也没有明白，想要咨询你们一下。
1.为什么train.txt中有那么多的NA关系，比例将近80%，是故意加进去的还是NYT和freebase对齐后的结果
2.这么多NA关系对于训练效果没有影响吗？
3.train.txt中有56种关系，而relation2id只有53种关系，那train.txt中的关系是如何处理的呢？还有就是relation2id中的53种关系是如何获得的呢

**Comment by npc123456** [comment]
Hello, 
Recently in running this procedure, I have a few questions have been confused, read the previous questions, did not understand, want to consult you. 
1. Why are there so many NA relationships in train.txt, nearly 80% deliberately added or the result of aligning NYT and freebase 
2. Do so many NA relationships have no effect on the training effect? 
3. There are 56 relationships in train.txt and only 53 relationships in relation2id. How do you deal with the relationships in train.txt? And how do you get the 53 relationships in relation2id

**Comment by gaotianyu1350** [comment]
1. The original results of aligning NYT with Freebase have lots of NA instances.
2. We alleviate the negative effects brought by NA samples by giving small weight to NA-labelled instances. 
3. There are no sufficient data for certain relations, so we just discard these relations and instances of those relations will be treated as NA during training.
