### ISSUE TITLE
birnn模型不收敛

### ISSUE THREAD

**Issue by ShangYuming** [thunlp/OpenNRE#122]
你好，非常感谢分享代码
可是在运行birnn的时候，发现模型不收敛，auc一直在0.006左右徘徊。请问需要再设置什么参数么

**Comment by gaotianyu1350** [comment]
是在我们提供的数据集上还是新数据集上？如果是原始数据集上应该是可以收敛的，其他数据集的话可以尝试调长训练轮数，调整学习率等参数

**Comment by s1998** [comment]
Hey
@gaotianyu , I am having the same issue. I tried this for rnn too

**Comment by ssnvxia** [comment]
> Hey
> @gaotianyu , I am having the same issue. I tried brnn too on nyt dataset and can't get the results.

Hello, have your solve this problem?
I can only get the auc 0.32, far away from 0.35
