### ISSUE TITLE
the entity pairs in train.json processed don't match with the paper

### ISSUE THREAD

**Issue by yanjieG** [thunlp/OpenNRE#123]
Hi, guys
    I have run the data processing code (protobuf2json.py) and get the train.json & test.json.
    But I find that the entity pairs in train.json is 279,235 which is less than 281,270.
    I also test the data before dealing with overlapping, but the entity pairs is 291109 which is more than 281,270.
    I have no idea why this happen,  so could you please tell me is there something wrong with that? 
    Thanks a lot : p

**Comment by gaotianyu1350** [comment]
There might be some slight differences between the way we count the entity pairs and the original work (for example case-sensitive or not). Yet the total instance number of the data we provide is the same as the paper mentioned.

**Comment by yanjieG** [comment]
Thanks for your response.
But now I get a new confused question. when I calculate the top@2000 pr, I'm confused about the number of correct instances.
When testing,  if the sentences in a bag contain more than one relations, for example, 3 relations, and all of the three probabilities show in the top@2000. When this happen, the number of correct should be 'correct = correct + 3' or 'correct + 1'?
Best : P

**Comment by gaotianyu1350** [comment]
It should be `correct = correct + 3`
