### ISSUE TITLE
关于 testing framework for sentence-level RE 

### ISSUE THREAD

**Issue by JiyangZhang** [thunlp/OpenNRE#124]
尊敬的开发者您好：
请问README.md中提到的‘testing framework for sentence-level RE’如何实现？
在(https://github.com/thunlp/OpenNRE/blob/58e348bb8e86c7ae1664210371aa2c3f84c5e6b4/nrekit/framework.py#L233) 中是'raise NotImplementedError'
请问是否应该逐句pred与label比较，计算precision和recall，并以此绘制pr曲线图。感觉自己绘制的曲线有一些问题，遂前来请教。
打扰了，非常感谢。

**Comment by gaotianyu1350** [comment]
逐句比较判断正确/错误，然后按照和bag-level代码中相同的方法计算pr曲线即可（将每个instance对每个类别的预测概率排序，计算precision和recall）。因为我们的数据集是distant的就没有实现sentence-level的评测，之后也可能更新一波。

**Comment by JiyangZhang** [comment]
感谢您的回答，我现在测试的数据集是比较干净的人标注的数据集，因此想做sentence-level的评测。能否问的更仔细一点，如果我有m个句子，n种关系（包含N/A)。如果我想计算pr曲线，应该逐句比较判断正确/错误，得到每个instance对每个类别的预测概率矩阵（m*(n-1)维矩阵），对概率排序并计算precision和recall。
