### ISSUE TITLE
Confused about how to correctly calculate recall and precision?

### ISSUE THREAD

**Issue by yanjieG** [thunlp/OpenNRE#127]
But now I get a new confused question. when I calculate the top@2000 pr, I'm confused about the number of correct instances.
When testing, if the sentences in a bag contain more than one relations, for example, 3 relations, and all of the three probabilities show in the top@2000. When this happen, the number of correct should be 'correct = correct + 3' or 'correct + 1'?
Best : P

**Comment by gaotianyu1350** [comment]
It should be `correct = correct + 3`.
