### ISSUE TITLE
RNN keeps itself at auc of 0.006

### ISSUE THREAD

**Issue by s1998** [thunlp/OpenNRE#128]
Hi, 
I was trying to run the code with RNN with "GRU" and "LSTM" cell. The auc stays at 0.01. If possible, can you tell me what might be going wrong?

>def rnn(x, length, hidden_size=230, cell_name='lstm', var_scope=None, keep_prob=1.0):
>   with tf.variable_scope(var_scope or "rnn", reuse=tf.AUTO_REUSE):
>        x = __dropout__(x, keep_prob)
>        cell = __rnn_cell__(hidden_size, cell_name)
>        _, states = tf.nn.dynamic_rnn(cell, x, sequence_length=length, dtype=tf.float32, scope='dynamic-rnn')
>        if isinstance(states, tuple):
>            states = states[0]
>return states

**Comment by s1998** [comment]
@gaotianyu1350  It would be great if you could take a look.

**Comment by ssnvxia** [comment]
您好，因为我的英文水平很差，我就给你发中文。可以使用google translate帮助你看懂。
RNN代码不收敛的问题我也遇到过。是随机初始化的问题。多运行几次就可以了。
但是RNN的效果比其他几个模型都要差很多。
