### ISSUE TITLE
有点没搞明白instance_scope的含义

### ISSUE THREAD

**Issue by FlandrinorZXY** [thunlp/OpenNRE#131]
请问是这个变量的作用是什么？

**Comment by FlandrinorZXY** [comment]
如果它的作用是记录entity的位置，那么变量长度为什么和sentence的总数不一样呢？

**Comment by FlandrinorZXY** [comment]
主要是没理清楚mentions，sentence，relations，以及len（instance_scope）的关系

**Comment by gaotianyu1350** [comment]
这里我们用的是bag的训练方法，对于所有有相同entity_pair和relation的句子（entity_pair和relation的组合又称为triplet或者relation fact），是一个bag，对于每个bag我们预测对各个relation的概率。instance_scope中的每一个scope指定的就是一个bag的范围，从哪一句到哪一句是这个bag里面的

**Comment by lu161513** [comment]
> 这里我们用的是bag的训练方法，对于所有有相同entity_pair和relation的句子（entity_pair和relation的组合又称为triplet或者relation fact），是一个bag，对于每个bag我们预测对各个relation的概率。instance_scope中的每一个scope指定的就是一个bag的范围，从哪一句到哪一句是这个bag里面的

想问一下，构建这个bag是如何构建的，好像没有找到相关的代码，谢谢
