### ISSUE TITLE
Data Preprocessing doesn't work?

### ISSUE THREAD

**Issue by kasunsp** [thunlp/OpenNRE#132]
Hi
I try to use "python protobuf2json.py" to generate train and test data from NYT raw data. But it produce an error as follows.

`Loading entities...
Finish loading, got 1845262 entities totally
Loading ./kb_manual/trainPositive.pb
Traceback (most recent call last):
  File "protobuf2json.py", line 75, in <module>
    main()
  File "protobuf2json.py", line 51, in main
    get_instances(ori_train_json_data, os.path.join(root_dir, 'kb_manual/trainPositive.pb'))
  File "protobuf2json.py", line 35, in get_instances
    head = guid2entity[relfact.sourceGuid]
KeyError: '/guid/9202a8c04000641f8000000000038574'
`

How can I proceed ?

**Comment by eukaryote31** [comment]
For posterity, I managed to fix this with the following patch:

```
15,16c15,16
<         guid, word, type = line.split('\t')
<         guid2entity[guid] = {'id': guid, 'word': word, 'type': type}
---
>         guid, word, type = line.split(b'\t')
>         guid2entity[guid.decode('utf-8')] = {'id': guid.decode('utf-8'), 'word': word.decode('utf-8'), 'type': type.decode('utf-8')}
```
