### ISSUE TITLE
NYT10 data Toolkit中protobuf2json.py的bug

### ISSUE THREAD

**Issue by zhengyima** [thunlp/OpenNRE#134]
protobuf2json.py中第12行

`
f = open(file_name, 'rb')
`

应改为

`
f = open(file_name, 'r')
`

不然会报TypeError: a bytes-like object is required, not 'str'

很明显的bug

**Comment by HWZX** [comment]
是所有的open中的rb都改吗，我这里报的错是“TypeError: expected bytes, str found”，改了第12行的错也还报错

**Comment by charosen** [comment]
应该是对get_entities函数进行修改：
修改方法1：
`f = open(file_name, 'rb')`改为`f = open(file_name, 'r')`
或者
修改方法2:
`line = line.rstrip()`改为`line = line.rstrip().decode()`

个人猜测：
get_entities函数只是读取tsv文本文件，用以构建guid到entity的字典映射，所以可以不用以二进制格式读取文件；而get_instances函数用到了protobuf，所以需要以二进制格式读取.pb文件，所以是`f = open(file_name, 'rb')`

我的python版本是3.6.7

**Comment by grance1** [comment]
> 是所有的open中的rb都改吗，我这里报的错是“TypeError: expected bytes, str found”，改了第12行的错也还报错

你好，我运行这个文件也出错了，你的错误修改好了吗？我用的是python3.6.7

**Comment by read2017** [comment]
line = line.rstrip()改为line = line.rstrip().decode()
亲测有效

**Comment by qingdujun** [comment]
> 应该是对get_entities函数进行修改：
> 修改方法1：
> `f = open(file_name, 'rb')`改为`f = open(file_name, 'r')`
> 或者
> 修改方法2:
> `line = line.rstrip()`改为`line = line.rstrip().decode()`
> 
> 个人猜测：
> get_entities函数只是读取tsv文本文件，用以构建guid到entity的字典映射，所以可以不用以二进制格式读取文件；而get_instances函数用到了protobuf，所以需要以二进制格式读取.pb文件，所以是`f = open(file_name, 'rb')`
> 
> 我的python版本是3.6.7

Yes, you are right. 

I'm using python2.7, and I only modify `rb` to `r`.

It' s work. And you can see that `test-reading-friendly.json` and `train-reading-friendly.json` are generated.

```bash
qingdujun@ubuntu1804lts:~/googol/opennre/nyt$ vim protobuf2json.py 

f = open(file_name, 'rb')改为f = open(file_name, 'r')

qingdujun@ubuntu1804lts:~/googol/opennre/nyt$ python protobuf2json.py ./
Loading entities...
Finish loading, got 1845262 entities totally
Loading ./kb_manual/trainPositive.pb
Finish loading, got 121867 instances and 19465 relfacts totally
Loading ./kb_manual/trainNegative.pb
Finish loading, got 322249 instances and 226576 relfacts totally
Loading ./heldout_relations/trainPositive.pb
Finish loading, got 34811 instances and 4700 relfacts totally
Loading ./heldout_relations/trainNegative.pb
Finish loading, got 91373 instances and 63596 relfacts totally
Loading ./heldout_relations/testPositive.pb
Finish loading, got 6444 instances and 1950 relfacts totally
Loading ./heldout_relations/testNegative.pb
Finish loading, got 166004 instances and 94917 relfacts totally
Dealing with overlapping...
Finish
Storing json files...
Finish

qingdujun@ubuntu1804lts:~/googol/opennre/nyt$ ls
Document_pb2.py   filtered-freebase-simple-topic-dump-3cols.tsv  protobuf2json.py  rel2id.json                 train.json
Document_pb2.pyc  heldout_relations                              __pycache__       test.json                   train-reading-friendly.json
Document.proto    kb_manual                                      README.md         test-reading-friendly.json  word_vec.json
```

**Comment by TuanMinhLe** [comment]
> 应该是对get_entities函数进行修改：
> 修改方法1：
> `f = open(file_name, 'rb')`改为`f = open(file_name, 'r')`
> 或者
> 修改方法2:
> `line = line.rstrip()`改为`line = line.rstrip().decode()`
> 
> 个人猜测：
> get_entities函数只是读取tsv文本文件，用以构建guid到entity的字典映射，所以可以不用以二进制格式读取文件；而get_instances函数用到了protobuf，所以需要以二进制格式读取.pb文件，所以是`f = open(file_name, 'rb')`
> 
> 我的python版本是3.6.7

It's work for me, thanks
