### ISSUE TITLE
path split error in data_loader

### ISSUE THREAD

**Issue by YuhwaChoong** [thunlp/OpenNRE#135]
the file_name and word_vec_name is joined by os.path.join, but in line 385 of data_loader.py the path is splited by string ‘/‘. But in Windows, os.path.join will join paths via ‘\\’,  this will occur path error in Windows. so my suggestion is to change the path splitter to os.path.split.
That is to change the code of line 385-386 in data_loader.py to
name_prefix = ‘.’.join(os.path.split(file_name)[-1])
word_vec_name_prefix = ‘.’.join(os.split(word_vec_file_name)[-1])

**Comment by gaotianyu1350** [comment]
Thanks! This has been fixed.
