### ISSUE TITLE
关于Document_pb2.py的问题

### ISSUE THREAD

**Issue by JerichoHy** [thunlp/OpenNRE#137]
文件中第16行
`serialized_pb='\n\x0e\x44ocument.proto\x12\x14large_coref.protobuf\"\x97\x04\n\x08\x44ocument\x12\x10\n\x08\x66ilename\x18\x01 \x02(\t\x12:\n\tsentences\x18\x02 \x03(\x0b\x32\'.large_coref.protobuf.Document.Sentence\x1a\xb3\x01\n\x08Sentence\x12\x34\n\x06tokens\x18\x01 \x03(\x0b\x32$.large_coref.protobuf.Document.Token\x12\x38\n\x08mentions\x18\x02 \x03(\x0b\x32&.large_coref.protobuf.Document.Mention\x12\x37\n\x07\x64\x65pTree\x18\x03 \x01(\x0b\x32&.large_coref.protobuf.Document.DepTree\x1a/\n\x05Token\x12\x0c\n\x04word\x18\x01 \x02(\t\x12\x0b\n\x03tag\x18\x02 \x01(\t\x12\x0b\n\x03ner\x18\x03 \x01(\t\x1aR\n\x07Mention\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x12\n\nentityGuid\x18\x02 \x01(\t\x12\x0c\n\x04\x66rom\x18\x03 \x02(\x05\x12\n\n\x02to\x18\x04 \x02(\x05\x12\r\n\x05label\x18\x05 \x02(\t\x1a\x36\n\x07\x44\x65pTree\x12\x0c\n\x04root\x18\x01 \x02(\x05\x12\x0c\n\x04head\x18\x02 \x03(\x05\x12\x0f\n\x07relType\x18\x03 \x03(\t\x1aJ\n\x0fRelationMention\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0e\n\x06source\x18\x02 \x02(\x05\x12\x0c\n\x04\x64\x65st\x18\x03 \x02(\x05\x12\r\n\x05label\x18\x04 \x02(\t\"\xf2\x01\n\x08Relation\x12\x12\n\nsourceGuid\x18\x01 \x02(\t\x12\x10\n\x08\x64\x65stGuid\x18\x02 \x02(\t\x12\x0f\n\x07relType\x18\x03 \x02(\t\x12\x42\n\x07mention\x18\x04 \x03(\x0b\x32\x31.large_coref.protobuf.Relation.RelationMentionRef\x1ak\n\x12RelationMentionRef\x12\x10\n\x08\x66ilename\x18\x01 \x02(\t\x12\x10\n\x08sourceId\x18\x02 \x02(\x05\x12\x0e\n\x06\x64\x65stId\x18\x03 \x02(\x05\x12\x0f\n\x07\x66\x65\x61ture\x18\x04 \x03(\t\x12\x10\n\x08sentence\x18\x05 \x01(\t\"\xc3\x01\n\x06\x45ntity\x12\x0c\n\x04guid\x18\x01 \x02(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x0c\n\x04pred\x18\x04 \x01(\t\x12>\n\x07mention\x18\x05 \x03(\x0b\x32-.large_coref.protobuf.Entity.EntityMentionRef\x1a\x41\n\x10\x45ntityMentionRef\x12\x10\n\x08\x66ilename\x18\x01 \x02(\t\x12\n\n\x02id\x18\x02 \x02(\x05\x12\x0f\n\x07\x66\x65\x61ture\x18\x03 \x03(\tB6\n$cc.refectorie.proj.relation.protobufB\x0e\x44ocumentProtos')
``应该怎么解决`

**Comment by wyl-nlp** [comment]
python版本不对，你的应该是python3。只需要把Document_pb2.py里的所有syntax='proto2'改成syntax='proto3'即可，
还一个就是将protobuf2json.py 里15行guid, word, type = line.split('\t')  改成guid, word, type = line.decode().split('\t')
完美解决

**Comment by JerichoHy** [comment]
好的，谢谢

**Comment by ShellingFord221** [comment]
你好，为什么我下载的Document_pb2.py里没有syntax='proto2'呢？也是报第16行的错误

**Comment by ShellingFord221** [comment]
另外protobuf2json.py中的unicode也报错

**Comment by wcz1997** [comment]
> 另外protobuf2json.py中的unicode也报错

我也是这样
不知道如何跑通代码

**Comment by gaotianyu1350** [comment]
这个Document_pb2.py是原始数据里带的，应该用python2执行
