### ISSUE TITLE
test_demo中json.dump()出错

### ISSUE THREAD

**Issue by Dwyane3** [thunlp/OpenNRE#141]
TypeError: Object of type 'bytes' is not JSON serializable
看了一下好像是framework中pred_result中的batch_data['entpair'][idx].encode('utf-8')是bytes类型的,而且json.dump()好像是将dict转换为json，但是pred_result似乎是list类型；请问如何解决这个报错呢？

**Comment by Dwyane3** [comment]
python版本3.6

**Comment by lu161513** [comment]
解决了吗。。。我也碰到这个问题了

**Comment by zhileeee** [comment]
我也碰到这个问题了

**Comment by Dwyane3** [comment]
> 解决了吗。。。我也碰到这个问题了

看一下 py2 py3的bytes问题就可以了

**Comment by Dwyane3** [comment]
> 我也碰到这个问题了

看一下 py2 py3的bytes问题就可以了
