### ISSUE TITLE
computing sentence level attention

### ISSUE THREAD

**Issue by lephong** [thunlp/OpenNRE#142]
I get confused how to compute sentence-level attentions for bags. In the source code (as well as the corresponding paper "Neural Relation Extraction with Selective Attention over Instances"), to compute **s**, representation for bag of n sentences s = {x1,...,xn}, we need a query r to compute attention weights (eq.8 in the paper). Because of this "query r", your probability p (eq 9) is actually a distribution over relations given the "query r". 

In your source code, both for test and train, you use "bag_attention", which requires "query". I don't see in your source code anywhere that sums up over "query".

If my understanding is correct, it is nonsense to maximize p using cross-entropy (because p is conditioning on query). 

If my understanding is correct, I was wondering how the source code (and model) works at test time, given that we have to find the best "query r"

**Comment by gaotianyu1350** [comment]
`att_mat` is the query you ask. During training, we use the correct r as query. For inference, we calculate attention scores for each relation. Please refer to the code for details.
