### ISSUE TITLE
Can't find any test result document

### ISSUE THREAD

**Issue by Jim0530** [thunlp/OpenNRE#144]
我有按照您給的步驟去跑training 也跑完20epoch 最後得出
[TEST] auc: 0.0
Finish testing
######
Finish training nyt_pcnn_att
Best epoch auc = 0.000000
但在draw plot 的時候 No such file or directory: './test_result/{nyt}_x.npy'
拜託回答了 卡很久一直找不到錯誤

**Comment by Jim0530** [comment]
having this FileNotFoundError: [Errno 2] No such file or directory: './test_result\\{nyt}_x.npy'
while running python draw_plot.py

**Comment by zhileeee** [comment]
您的结果是什么，怎么样，可以看看吗

**Comment by gaomin0806** [comment]
我也有同样的问题，请问怎么处理，谢谢

**Comment by gaomin0806** [comment]
你好,我有同样的问题,training之后并没有生成test_result文件夹,请问该如何解决

**Comment by djxprogrammer** [comment]
If your halt trainning by hand, then it will not generate "test_result" folder. Or, u may find other reasons.
