### ISSUE TITLE
关于max_length参数问题

### ISSUE THREAD

**Issue by orangewang111** [thunlp/OpenNRE#146]
max_length参数表示的是每句话截取的长度，这个数值是否可以修改？修改值要满足哪些条件呢？感谢！

**Comment by gaotianyu1350** [comment]
可以修改，这个看你要使用的数据集，尽量把max_length设置为数据集中最长的句子的长度，但如果只有个别句子特别长也可以无视，毕竟max_length越长，模型越慢
