### ISSUE TITLE
请问一个句子只能预测出一个关系吗

### ISSUE THREAD

**Issue by lalalei21** [thunlp/OpenNRE#147]
1. 如果测试集用ner工具标注了实体，一个句子有多个实体，我如何指定哪个是头实体，哪个是尾实体。输入数据是否必须明确头和尾 才能进行预测？
2. 假设我句子里有3个实体，实体12是A关系，实体13是B关系，您的代码是否支持这种多关系预测呢？

**Comment by THUCSTHanxu13** [comment]
我们的数据格式给定了head和tail的说明，不过现在的系统确实只能支持单句预测一个关系。

**Comment by xxllp** [comment]
看来有点弱
