### ISSUE TITLE
Using this repository for Relation classification.

### ISSUE THREAD

**Issue by normalOne95** [thunlp/OpenNRE#149]
Hi,

Thanks a lot for this great repository. 

1. Is it possible to use this repository for relation classification (like SemEval 2010 Task 8)? What are some changes I need to make to be able to run the code for relation classification?

2. Also, what is the reason of using instance scope, entpair2scope, and relfact2scope? I think these might not be needed for the task of relation classification.

Hoping for a swift reply!

Thank You,

**Comment by gaotianyu1350** [comment]
You can see the examples in the repo and it can be used for datasets like SemEval. Scope variables are for bag-level relation extraction (distant supervision).
