### ISSUE TITLE
question about position embedding

### ISSUE THREAD

**Issue by ShellingFord221** [thunlp/OpenNRE#150]
Hi, I have another question about position embedding. In NYT dataset, there are some sentences that e1 or e2 appears more than 1 time. For example, these sentences may like _ _ _ e1 _ _ e2 _ _ _ e2 _ _. The relative distance of e1 is out of question, but the relative distance of e2 is ambiguous. How do you embed positions in this situation? Thanks!

**Comment by Spico197** [comment]
From the source code of `data_loader.py`, we can get such a  piece of code (before really embedding, actually)
```python3
p1 = sentence.find(' ' + head + ' ')
p2 = sentence.find(' ' + tail + ' ')
```
so I guess the code just find the first `e2` if it is ambiguous.

**Comment by gaotianyu1350** [comment]
We just take the first e2. Since NYT is a distant supervision dataset, we cannot get the accurate position of the entities. For supervised datasets, we use the annotated positions of entities.
