### ISSUE TITLE
为什么训练时训练集跟验证集loss会是nan，not NA accuracy也是0

### ISSUE THREAD

**Issue by LambdaWs** [thunlp/OpenNRE#151]
您好，关系的json里面我只定义了NA：0，相关：1，无关：2 这三种关系，我的训练数据里面只有相关、无关两种关系数据，没有Na对应的数据，利用pcnn att的参数进行训练，可是训练过程中遇到下面的日志
loss: nan, not NA accuracy: 0.000000, accuracy: 0.010156
not NA accuracy: 0.000000, accuracy: 0.049479
我有两个问题，1、请问您知道是什么原因造成 的如上结果吗？2、咱们的训练数据里面必须要有Na关系对应的数据吗？这个Na到底在后面的实现中扮演什么样的角色。谢谢了！！

**Comment by Spico197** [comment]
关系中的NA指无法确定或未确定的关系，这点应该是和NYT10数据集对应的

**Comment by gaotianyu1350** [comment]
@Spico197 说的是对的，你可以用你说的NA：0，相关1，无关2的定义方式，只是NA没有训练样本而已。

至于loss NAN，可能有很多原因，比如学习率设置过大，可以尝试调一下参

**Comment by dengxingwang** [comment]
我也遇到了相同的问题，请问楼主解决了吗？
