### ISSUE TITLE
How to generate Document_pb2.py?

### ISSUE THREAD

**Issue by ShellingFord221** [thunlp/OpenNRE#153]
Hi, please give some more details about how to generate Document_pb2.py. It seems that this python file I downloaded from your cloud is different with other people's python file.

**Comment by ShellingFord221** [comment]
Or if you have fully processed json files, please upload to your cloud. Thank you so much!

**Comment by wzhxs** [comment]
I have processed JSON files completely, but these files are very large. I recommend that you handle them by yourself and generate the first step of the file, "protoc - proto_path=. - python_out=. Document. proto", which can be executed without execution. There is a "Document_pb2.py" file in the project, but you need to modify the "protobuf2json.py" file, "line = line. rstrip ()" to "line = line. rstrip (). decode ()", and then run "python decode ()". N protobuf2json.py. /". Finally, specify the parameter as the current path, run on it. Good luck to you.

**Comment by wzhxs** [comment]
The "Document_pb2.py" file in the original project is generated based on Python 2. If you need Python 3 to perform the first step, you can generate it yourself. Protobuf needs to be installed

**Comment by qingdujun** [comment]
```
$ protoc --proto_path=. --python_out=. Document.proto

[libprotobuf WARNING google/protobuf/compiler/parser.cc:547] No syntax specified for the proto file: Document.proto.  Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
```


Hello, in `Document.proto`, you should add `syntax = "proto2";`

```proto
syntax = "proto2";  //add it

package large_coref.protobuf;

option java_package = "cc.refectorie.proj.relation.protobuf";
option java_outer_classname = "DocumentProtos";

message Document {
  required string filename = 1;
  repeated Sentence sentences = 2;

...


```
