### ISSUE TITLE
Question about bag?

### ISSUE THREAD

**Issue by nine09** [thunlp/OpenNRE#154]
I have checked processed NYT data. 
```
[[2501, '/location/country/capital'],
 [2501, '/location/location/contains'],
 [1713, '/location/location/contains'],
 [1489, '/location/administrative_division/country'],
 [1489, '/location/country/administrative_divisions'],
 [1489, '/location/country/capital'],
 [1489, '/location/location/contains'],
 [921, '/location/location/contains'],
 [921, '/location/neighborhood/neighborhood_of'],
 [893, '/business/person/company'],
 [751, '/location/location/contains'],
 [751, '/location/neighborhood/neighborhood_of'],
 [703, '/people/deceased_person/place_of_death'],
 [703, '/people/person/nationality'],
 [703, '/people/person/place_of_birth'],
 [684, '/location/administrative_division/country'],
 [684, '/location/country/administrative_divisions'],
 [647, '/location/location/contains'],
```

**Here is number of instances in a bag and the label of bag.**
We can see some times one label will refer to multi bags, **for example there are several bags of label** `/location/country/capital`. And some times bag is so huge that has 2500 instances.
**So is there any idea about how we split bags?**

**Comment by Spico197** [comment]
In an easy way, sentences with the same entity pairs could be split into one bag (ent1#ent2). Besides, sentences with the same entity pairs and the same relations could be split into one bag, either (ent1#ent2#rel).
In OpenNRE, the second bag split method (ent1#ent2#rel) is used in training steps, and the first (ent1#ent2) is used in test steps.

**Comment by nine09** [comment]
Thank you so much, And my anxiety is that **when we test, what's the basic unit we feed to our model. It is also a bag or it is just one instance**, cause actually we want relation label for each instance, not a entity pair bag.
According what you said, it seems that we use bags principle even in test process.

**Comment by nine09** [comment]
> In an easy way, sentences with the same entity pairs could be split into one bag (ent1#ent2). Besides, sentences with the same entity pairs and the same relations could be split into one bag, either (ent1#ent2#rel).
> In OpenNRE, the second bag split method (ent1#ent2#rel) is used in training steps, and the first (ent1#ent2) is used in test steps.

Thank you so much, And my anxiety is that **when we test, what's the basic unit we feed to our model. It is also a bag or it is just one instance**, cause actually we want relation label for each instance, not a entity pair bag.
According what you said, it seems that we use bags principle even in test process.

**Comment by Spico197** [comment]
Yes. Because we use a multi-instance learning model during training, so the test input must be bags, either. The MIL could only predict bag labels, but not instance labels.

**Comment by cm12348** [comment]
@Spico197 Hi, is it meaningful to test an instance as a bag with one instance? Also, it seems like that there are many bags with only one instance.
