### ISSUE TITLE
train_GRU.py IndexError:list index out of range

### ISSUE THREAD

**Issue by snowxiaoru** [thunlp/OpenNRE#16]
你好，
 我在运行 train_GRU.py 时，遇到list Index out of  range error，具体错误显示在
network.py
sen_a = tf.get_variable('attention_A',[gru_size])
麻烦看一下这个问题怎么解决，谢谢！

**Comment by Tsingularity** [comment]
抱歉这么晚才回复。
麻烦请问您可以贴出全部报错信息吗？这样我可以更好地确定bug的原因。

**Comment by snowxiaoru** [comment]
![image](https://cloud.githubusercontent.com/assets/12291912/26624439/735e9ea6-4623-11e7-911d-57fe0e5ac84f.png)

**Comment by THUCSTHanxu13** [comment]
我们更新了一波代码和使用，你可以再看一下
