### ISSUE TITLE
Accessing Raw attention values at Instance Level

### ISSUE THREAD

**Issue by unknown1990** [thunlp/OpenNRE#161]
Hi there,

Many Thanks for your code !
I have two questions:
1.
I am running the model in this configuration: `python train_demo.py nyt pcnn att`
I am interested in extracting raw level attention values of instances/examples within a bag at test time, is there a simple interface to access attention value per instance (within each bag)?
2.
Why is the bag representation of **<h,r,t>** is preferred over **<h,t>**? If I instead create bag on the basis of <h,t> the code (train/test) should still run smoothly?

**Comment by gaotianyu1350** [comment]
We use <h,r,t> during training and <h,t> during inference. You can manually modify the code to get the raw attention values.
