### ISSUE TITLE
How to predict relations for raw sentences?

### ISSUE THREAD

**Issue by rstarlet** [thunlp/OpenNRE#166]

**Comment by rstarlet** [comment]
Like I have plain text with no relations and entities, How would I go about to predict the relations, kindly guide

**Comment by taufique74** [comment]
@rstarlet Did you find any solution to this?
I'm also trying to predict the relations given just only entities.

**Comment by nexsys** [comment]
Any update on this issue ??

**Comment by geekhch** [comment]
> Like I have plain text with no relations and entities, How would I go about to predict the relations, kindly guide

you need run named entity recoginition firstly, which find the entity in a plain text.
