### ISSUE TITLE
why use range(1, self.test_data_loader.rel_tot) in test (not the unique rel in test) ?

### ISSUE THREAD

**Issue by bifeng** [thunlp/OpenNRE#169]
In the framework.py, line of 374:
```
                for rel in range(1, self.test_data_loader.rel_tot):
                    test_result.append({'score': iter_logit[idx][rel], 'flag': batch_data['multi_rel'][idx][rel]})
```

why don't use all the rel in the test, such as:
`for rel in range(1, self.test_data_loader.rel.unique()).`

Because the real label may not appear in the range(1, self.test_data_loader.rel_tot).

**Comment by gaotianyu1350** [comment]
The two are the same.
