### ISSUE TITLE
is there a memory leak? it can't run more than 20 epoches on my 16GB memory pc. 

### ISSUE THREAD

**Issue by qwer10** [thunlp/OpenNRE#171]

**Comment by HeapRQ** [comment]
This problem was also occurred on my 16GB memory pc, do you solve it?

**Comment by qwer10** [comment]
> This problem was also occurred on my 16GB memory pc, do you solve it?

no,  wish the author's reply

**Comment by HeapRQ** [comment]
I try it again and again and it works successfully in third times, you can just try it again,good luck!

**Comment by MrSchnappi** [comment]
I have try it again and again . it does not  work. then I have set the bath_size = 16, but the problem of OOM still exist. what should I do? By the way, I am running the model of att_is_all

**Comment by gaotianyu1350** [comment]
You can try out the latest version. The problem should have gone.
