### ISSUE TITLE
Selective attention has no improvement

### ISSUE THREAD

**Issue by cm12348** [thunlp/OpenNRE#173]
Hello, I simply run the code on NYT for 36 epochs by following the instructions in readme, but I found the performance of selective attention and max instance are similar. I wonder if there is some setting I missed? This is the PR graph generated by the codes.
![图片1](https://user-images.githubusercontent.com/29419903/60785967-69d90d00-a187-11e9-9057-4ac35b6f216a.png)

**Comment by gaotianyu1350** [comment]
Move to #264
