### ISSUE TITLE
The attention score computation seems different from the eauqtion in the paper

### ISSUE THREAD

**Issue by lanzhuzhu** [thunlp/OpenNRE#175]
The equation 8 in the paper _Neural Relation Extraction with Selective Attention over Instances_ shows that the sentence representation **x_i** is associated with the 'query' relation **r** through a diagonal matrix **A**. I guess this bilinear form can help project the two vectors into the same vector space, so as to compute their distance better. 
![Screenshot from 2019-07-17 21-53-38](https://user-images.githubusercontent.com/14541203/61423341-6bb87400-a8dd-11e9-9a9b-43c66ca3a046.png)
The implementation of this part is: 
https://github.com/thunlp/OpenNRE/blob/78cdf0b6f3d8ce398379399f4d57daa55c77d8f0/nrekit/network/selector.py#L19
It seems that the two vectors are multiplied directly without any parameter like a matrix.

**Comment by loginaway** [comment]
I found the same mistake in this code. Guess it might be a little mistake in this implementation.

**Comment by gaotianyu1350** [comment]
In our practical experiments, not using matrix A produces better results.
