### ISSUE TITLE
求教关于中文实体关系训练问题？

### ISSUE THREAD

**Issue by denglizong** [thunlp/OpenNRE#178]
亲爱的作者您好，我想将该项目用于中文实体关系识别，但看了一些历史回答，疑惑仍然没有解决，故求教以下理解是否正确。

1. 若以中文字作为单元 (相应的，word_vec.json中也是字和vec)，但我不清楚的是，在训练集和测试集中，需要以空格将sentence和word的字符显式的分开吗(像英文一样)？ 
例如，
  {
    "sentence": “工商注册地在广州市南沙区”,
    "head": {"word": "工商注册地","id":"1"},
    "tail": {"word": "广州市南沙区","id":"2"},
    "relation": "范围内"
  },
是否应为
  {
    "sentence": “工 商 注 册 地 在 广 州 市 南 沙 区”,
    "head": {"word": "工 商 注 册 地","id":"1"},
    "tail": {"word": "广 州 市 南 沙 区","id":"2"},
    "relation": "范围内"
  },

2. 这一问题若是以词为单元，我也不清楚，训练集是以没有分词的原始形式  ，还是以thulac进行分词后的形式表征呢？

感谢回复。

**Comment by gaotianyu1350** [comment]
Hi，

第一个问题，是向你写的这样划分。当然如果你觉得数据里面这么多空格很浪费的话，也可以直接修改代码。

第二个问题，一种方法是对训练集分词后，词与词之间用空格隔开存在磁盘上，比如“工商 注册地 在 广州市”，要么直接修改代码，在程序里面分词。
