### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by 595849292** [thunlp/OpenNRE#18]
您好
train.txt: training file, format (fb_mid_e1, fb_mid_e2, e1_name, e2_name, relation, sentence).
对其中，fb_mid_e1,fb_mid_e2,e1_name,e2_name,请问是什么意思？
另外，relation 的结果是实体／实体／关系吗？
感谢

**Comment by Tsingularity** [comment]
十分抱歉这么久才回复。

其中train.txt中，fb_mid_e1和fb_mid_e2是两个实体在freebase中的编号，e1_name和e2_name是实体的字符串。由于distant supervision的特性，其实这里字符串与编号是基本一一对应的，所以代码中真正使用的是字符串，编号并未参与任何运算。但这里为了和baseline数据保持一致，因而采用的是同一份train.txt. 其中relation是freebase中定义好的关系类别.
