### ISSUE TITLE
请问可否用于中文数据，需要修改哪里

### ISSUE THREAD

**Issue by 526222883** [thunlp/OpenNRE#180]
感谢

**Comment by PKUYeYuan** [comment]
我试过将中文的数据转化为要求的输入格式，然后提供一个中文的词向量文件是能够运行的，代码方面应该是不需要怎么修改的。不知道你说的修改是指的什么？

**Comment by li10141110** [comment]
@PKUYeYuan 你好，请问能告知用的那个数据集吗？或者基本中文数据处理流程，十分感谢

**Comment by PKUYeYuan** [comment]
> @PKUYeYuan 你好，请问能告知用的那个数据集吗？或者基本中文数据处理流程，十分感谢

中文数据集是我们自己使用的一个数据集，目前还没有打算公开。基本的流程：分词--> GloVe词向量训练--> 根据OpenNRE要求准备数据-->运行代码。我印象中流程里面没有特别地处理。
