### ISSUE TITLE
Question about OOM

### ISSUE THREAD

**Issue by MrSchnappi** [thunlp/OpenNRE#181]
在运行att_is_all的时候，提示我OOM问题。把相关参数调小（batch_size =16, hidden_size=16)问题依然存在。初次之外，发现结果也有点奇怪，loss不收敛，NA accuracy 近似等于1（0.999543）还持续上升 ， not NA accuracy 从0.0005直线下降。将learn rate更改为0.001问题依旧如此，由于OOM问题 只能训练到epoch 0 的step 2000左右。 硬件设备是：32GB tesla P100V ，是内存太小了吗？

**Comment by gaotianyu1350** [comment]
You can try it out again. Now all the examples should be able to run.
