### ISSUE TITLE
关于AUC

### ISSUE THREAD

**Issue by ShellingFord221** [thunlp/OpenNRE#182]
你好，想请教下AUC值的计算问题。

我总共设置100个epoch，在每个epoch都train和test，这样每个epoch都会得到一组PR值，每个epoch都可绘制一条PR曲线，都可计算一个AUC值。那么：

1. 模型最终的AUC值是这100条PR曲线中最大的那个吗？
2. 是否存在这样一种情况，即当前epoch的AUC值最大，但F1值却不是最大的？

谢谢！

**Comment by gaotianyu1350** [comment]
Hi,

1. 模型的AUC值是这100个里面最大的。
2. 的确存在这种情况，AUC大但F1小，你可以选择auc最大的那个，也可以选择f1最大的那个

**Comment by ShellingFord221** [comment]
那么，在PR曲线中，使用AUC来度量模型的好坏，和使用max F1来度量模型的好坏，那种更合理些呢？
我自己的方法是max F1比别人好，但是AUC比别人差

**Comment by gaotianyu1350** [comment]
这两个metric其实都可以，auc对整体的模型表现，包括长尾的数据应该会反映的更好一些，在这个task上我们用auc更多一些

**Comment by ShellingFord221** [comment]
好的，谢谢~
