### ISSUE TITLE
No module named 'pytorch_pretrained_bert'

### ISSUE THREAD

**Issue by ejokhan** [thunlp/OpenNRE#183]
Hi seniors , i am new in this field i tried to run the first python file train_nyt10_pcnn_att.py

but it is giving me the error "No module named 'pytorch_pretrained_bert'"

any guidance from seniors will be appreciated

**Comment by Spico197** [comment]
The default encoder is `opennre.encoder.BERTEncoder`, which needs a `pytorch_pretrained_bert` library. If you'd like to use a basic pretrained model, you can change it to other encoders. `pytorch_pretrained_bert` library is out-of-date now. And you can find a new version from https://github.com/huggingface/transformers

**Comment by gaotianyu1350** [comment]
Hi thanks for the reminder! Now there is already another version including `pytorch_transformers` and we are expecting to merge it to the public branch in the next few days~

**Comment by gaotianyu1350** [comment]
This  problem has been fixed
