### ISSUE TITLE
关于Manual Evaluation

### ISSUE THREAD

**Issue by ShellingFord221** [thunlp/OpenNRE#184]
你好！在关系分类的标准task中，有一种评测指标是Manual Evaluation，即手工检测高置信度的FN样本（即测试集中给定的标签是NA，但实际由于freebase的不完整性，该句子中可能存在关系）。我有以下2个问题：

1. ‘We choose the entity pairs for which at least one participating entity is not present in Freebase as a candidate.’ 这个实体对是怎么筛选的？直接与test集中那些句子标签为非NA的实体对比较，有一个不在里面就认定这个句子是candidate吗（因为这些句子就是通过与freebase对其得到标签的）？还是说有一个freebase集，直接与之对比？

2. ‘Instead, we calculate the precision of the top N extracted relation instances (by manual evaluation).’ 这里的precision指的是accuracy吗？就是找到有关系的句子，直接除以100/200/500？

谢谢！

**Comment by gaotianyu1350** [comment]
Hi，请问这两句话是从哪里引用的呀，因为没有上下文所以我不太清楚是指的什么...

**Comment by ShellingFord221** [comment]
Sorry，这两句话是PCNN那篇paper里的，4.3.2 Manual Evaluation
<img width="464" alt="image" src="https://user-images.githubusercontent.com/40685673/66373704-d6101a80-e9db-11e9-8146-59ec4f981084.png">
<img width="464" alt="image" src="https://user-images.githubusercontent.com/40685673/66373727-e4f6cd00-e9db-11e9-92f1-82b368d49033.png">

**Comment by gaotianyu1350** [comment]
1. 我觉得不论是直接和test集合比较还是和freebase比较都可以，因为都能达到不与test集重合的效果。我并不知道作者具体是怎么做的，但应该是利用test集的可能性比较大，毕竟freebase是一个很大的数据集。

2. 这里precision的算法和accuracy是一样的（正确的数量 / 总数量，也就是100，200，500），但概念上来说不能叫accuracy，因为accuracy的话，分母应该是所有的样本，这里样本首先经过了排序，并且是假定top-100，200，500都是正样本，所以应该叫precision

**Comment by gaotianyu1350** [comment]
ps: 这种和repo无关的问题建议直接发邮件问哈，提issue的话最好是和repo本身有关的～

**Comment by ShellingFord221** [comment]
关于手工检测还有一个问题，就是找到了标签为NA，预测为非NA的top 100/200/500的样本，然后是人工去看这些样本是否存在预测的那个关系，还是只要有关系（即除了NA的52种之一）就算是正确的呢？

**Comment by gaotianyu1350** [comment]
人工检测的话是看这些样本是否存在预测的那个关系

**Comment by ShellingFord221** [comment]
但是在recall很低的时候，precision有一个sharp decline并不完全是因为把标签是NA的预测成非NA的，也有可能是测试集里标签标错了的呀，导致fp降低。为什么不把所有预测为非NA的取top 100/200/500（不care这些样本在测试集中的标签到底是不是NA）做手工检测呢？

**Comment by gaotianyu1350** [comment]
哦我刚才没注意你说的那个细节，应该是只要预测非NA就要拿出来的

**Comment by ShellingFord221** [comment]
理论上应该是这样的，但是看上面那篇论文里说的false negative samples好像指的只是标签为NA，预测为非NA的（而且后面说到了due to the imcomplete nature of Freebase），感觉这个地方真的很奇怪
