### ISSUE TITLE
Document_pb2.py gives metaclass syntax error 

### ISSUE THREAD

**Issue by ejokhan** [thunlp/OpenNRE#185]
hello guys,  i took my long time still could not get the Json file of Nyt.

i am facing the error given bellow . can anyone suggest a solution here?

as i heard python 2 does not support metaclass anymore? what should i do

ipdb> 
ipdb>   File "Document_pb2.py", line 499
    class Document(_message.Message, metaclass=_reflection.GeneratedProtocolMessageType):
                                              ^
SyntaxError: invalid syntax

**Comment by gaotianyu1350** [comment]
Hi you can directly download the processed json data from [this Google Driver link](https://drive.google.com/file/d/1IzS1ipoVBgzcLvdNiWaZE5WrzH94bpeI/view?usp=sharing).
