### ISSUE TITLE
关于PCNN的网络架构

### ISSUE THREAD

**Issue by ShellingFord221** [thunlp/OpenNRE#188]
你好！看了paper和网络结构部分的代码，发现PCNN的结构是这样的：
1. embedding层
2. 卷积层
3. piecewise pooling
4. 非线性层
5. dropout
6. softmax
想问下都没有加全连接层吗？

**Comment by gaotianyu1350** [comment]
最后分类是全联接层呀

**Comment by ShellingFord221** [comment]
不好意思，新手小白，对tensorflow也不是很了解，我看到在encoder.py里面是这样的：
![Uploading image.png…]()
后面接的模块是selector.py，以bag_attention这个函数为例，其中计算logit vector的是 __attention_train_logit__函数
![Uploading image.png…]()
但是这个函数是将x与current_relation相乘，得到attention后的logit，并没有看到全连接层的计算。。。希望能给出全连接层具体的行数，非常感谢！！

**Comment by gaotianyu1350** [comment]
这里就相当于全联接哈，全联接本质是矩阵乘

**Comment by ShellingFord221** [comment]
你好，因为做对比实验的关系，关于网络结构还想再确认下，PCNN是否是：

1. embedding层
2. 卷积层
3. piecewise pooling
4. 非线性层
5. dropout
6. flatten然后全连接
7. softmax

这样是你们实现的网络结构对吗？非常感谢！！！

**Comment by gaotianyu1350** [comment]
是的
