### ISSUE TITLE
请问是google.protobuf的版本问题么？谢谢

### ISSUE THREAD

**Issue by wyqnumber** [thunlp/OpenNRE#189]
![Screenshot from 2019-10-28 15-53-13](https://user-images.githubusercontent.com/10826415/67661019-15a6a280-f99b-11e9-876a-307c231a0f38.png)

**Comment by gaotianyu1350** [comment]
如果要处理数据的话，推荐直接从[这里](https://cloud.tsinghua.edu.cn/f/b854dbdb48fb4ece8a51/)下载处理好的json数据。
