### ISSUE TITLE
where is your adversarial learning code and RL code?

### ISSUE THREAD

**Issue by DesmonDay** [thunlp/OpenNRE#191]

**Comment by gaotianyu1350** [comment]
It's in the [tensorflow](https://github.com/thunlp/OpenNRE/tree/tensorflow) and [rl](https://github.com/thunlp/OpenNRE/tree/rl) branch for now. As stated in other issues, our rl implementation may have some errors so I would recommend you to refer to [this repo](https://github.com/xuyanfu/TensorFlow_RLRE) for now.

**Comment by ShellingFord221** [comment]
你好，想问下以前的代码还能开放下载吗~

**Comment by ShellingFord221** [comment]
你好，想问下之前你们实现的Reinforcement Learning for Relation Classification from Noisy Data这篇，可以执行CNN/PCNN+MAX/ATT四种方式，想问下这四种方式在test的时候是不是都是以bag-level测试的？（尽管paper里说这篇是sentence-level，我理解是训练的时候是sentence-level，测试的时候是bag-level，不然的话sentence-level怎么会有attention？）
谢谢！

**Comment by gaotianyu1350** [comment]
你说的这些都是distant supervision的方法，都应该是bag-level训练bag-level测试的，对应的也是现在的版本里面bag-level训练bag-level测试的代码。
