### ISSUE TITLE
Question about segmentation in base_encoder

### ISSUE THREAD

**Issue by TianyuZhuuu** [thunlp/OpenNRE#192]
https://github.com/thunlp/OpenNRE/blob/c224107d0074f20a8c39bc7c5fbed17c768fe24a/opennre/encoder/base_encoder.py#L107-L117

It seems that line 115 should be `sent_2 = self.tokenizer.tokenize(sentence[pos_max[1]:])`. Now `sent_2` and `ent_0` are identical.

And I can't get the point of `rev` here, which is always set to False outside the if/else block.

Could you double check with that? Thanks.

**Comment by gaotianyu1350** [comment]
Hi! We have noticed the bug previously and have now fixed it in the latest update. Thanks for the reminder!
