### ISSUE TITLE
训练数据集的问题

### ISSUE THREAD

**Issue by ssnvxia** [thunlp/OpenNRE#195]
您好，我注意到现在pytorch版本的训练数据中有48万训练句子，而原始的数据集中有57万训练语句，当前流行的数据集也有522611个训练语句。请问有没有52万json版本的训练数据呢

**Comment by gaotianyu1350** [comment]
Hi，因为原始的数据集没有划分valid和test集（而是只有test集），所以在这个版本里面我们新划分出了一个valid集。如果需要找常用的版本的话，可以从[tsinghua cloud](https://cloud.tsinghua.edu.cn/f/b854dbdb48fb4ece8a51/) 下载
