### ISSUE TITLE
BagAttention同样的输入，输出却不同

### ISSUE THREAD

**Issue by panfengde** [thunlp/OpenNRE#196]
我在example里面重新训练BagAttention 模型。
然后将这个模型加载之后，对同一个bag 进行20词输出，模型输出的score都不一样。如图：
![image](https://user-images.githubusercontent.com/27055350/68367942-d41faf80-0171-11ea-9f4b-5da20433a709.png)
这个是正常的吗？

加载模型代码如下：
![image](https://user-images.githubusercontent.com/27055350/68368302-ba329c80-0172-11ea-8b02-05981cd27ed9.png)

**Comment by gaotianyu1350** [comment]
Hi 这是一个代码中的bug，在infer的时候忘记开eval()了。已经修复了，感谢提醒！

**Comment by panfengde** [comment]
> Hi 这是一个代码中的bug，在infer的时候忘记开eval()了。已经修复了，感谢提醒！
bag_attention.py文件里的infer 好像也忘了self.eval()

**Comment by gaotianyu1350** [comment]
sorry刚才改错地方了，现在应该可以了😂
