### ISSUE TITLE
刚安装完 结果却和easy start的结果不一样，是包出问题了吗

### ISSUE THREAD

**Issue by dlutwy** [thunlp/OpenNRE#197]
>import opennre
> model = opennre.get_model('wiki80_cnn_softmax')

> model.infer({'text': 'He was the son of Máel Dúin mac Máele Fithrich, and grandson of the high king Áed Uaridnach (died 612).', 'h': {'pos': (18, 46)}, 't': {'pos': (78, 91)}})
('father', 0.5108704566955566)

我的结果是 ('father', 0.7500484585762024)

因为驱动不能更，只可用CUDA9，pytorch1.1.0 请问是这个的影响吗，还是数据出现变动了呢？

**Comment by gaotianyu1350** [comment]
Hi, 这个结果没有问题的哈，因为我们前段时间更新了模型，和readme里面写的例子数值上不一样了。
