### ISSUE TITLE
结果与发布的不匹配

### ISSUE THREAD

**Issue by snowxiaoru** [thunlp/OpenNRE#20]
你好，我所跑出的结果跟发布的准确率不太匹配，有以下几个问题
（1）在评价准确时是不是不包含对 NA的评价，我看代码是略过NA的。
 （2）训练语料中53个类别，共55w条句子，但NA类型的句子站30w+ ,这种不平衡的语料会不会影响结果结果，(测试的语料中共有15w+ NA类型占14w+ ,且只有30左右的类型)因为在测试的时候发现，如果包含NA，准确率可以达到98%，如果不算NA的准确率，前100,200及300的准确率在1%左右。语料是否存在不平衡问题？

**Comment by THUCSTHanxu13** [comment]
在关系抽取里面，在测试的时候，一个句子预测成NA是会被忽略的，换句话说，NA的句子预测成非NA的话会降低精确度，但是非NA的句子预测成NA是不会对结果造成影响的。另外这个实验不是一个分类算准确率的设定，你要考虑每个句子对应每种关系的分数，然后去算精确度-召回率
