### ISSUE TITLE
why auc of test_demo.py and draw_plot.py are different?

### ISSUE THREAD

**Issue by eveliao** [thunlp/OpenNRE#201]
Hi,

I didn't modify the code. However, `auc, F1, P@100/200/300, mean` from `test_demo.py` (calculated from ckpt) are all different from those from `draw_plot.py` (calculated from npy files saved during training). But I checked the code and found that these npy files are produced from the saved ckpt. I wonder why this happens.

Thanks.

**Comment by gaotianyu1350** [comment]
Codes have been updated now. You can check it out again.
