### ISSUE TITLE
json.decoder.JSONDecoderError

### ISSUE THREAD

**Issue by qianlanwyd** [thunlp/OpenNRE#205]
在执行例子时遇到了问题
Python 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import opennre
>>> model=opennre.get_model('wiki80_cnn_softmax')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yidongwang/OpenNRE/opennre/pretrain.py", line 63, in get_model
    wordi2d = json.load(open(os.path.join(root_path, 'pretrain/glove/glove.6B.50d_word2id.json')))
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 1191628 (char 1191627)

**Comment by gaotianyu1350** [comment]
看起来是文件损坏了，可以重新[从这里](http://193.112.16.83:8080/opennre/pretrain/glove/)下载一下glove文件，替换`pretrain/glove/glove.6B.50d_word2id.json`

**Comment by qianlanwyd** [comment]
pretrain中并没有glove文件夹

**Comment by gaotianyu1350** [comment]
可以运行一下`download_glove.sh`

**Comment by qianlanwyd** [comment]
运行了download_bert.ssh,download_glove.ssh，依然出现一开始的问题

**Comment by gaotianyu1350** [comment]
尝试重新pull一下repo（可能你使用的是旧版本有一些bug），然后删除home目录下的`.opennre`文件夹，再试一次

**Comment by qianlanwyd** [comment]
我是今天才gitclone的项目

**Comment by gaotianyu1350** [comment]
最好再重新clone一下吧，我刚刚修了一个bug（虽然和这个问题无关）

**Comment by qianlanwyd** [comment]
感谢大大，删除.opennre文件夹后不再出现入题错误

**Comment by qianlanwyd** [comment]
nltk 的包不在requirements.txt中，我是单独pip的
