### ISSUE TITLE
Issue with multi-GPU training

### ISSUE THREAD

**Issue by pvthuy** [thunlp/OpenNRE#208]
Hi,

I got this issue while training the model for distant supervision. Does anyone have similar issues?

Command: `python3 train_nyt10_pcnn_att.py`

Initializing hyperparameters...
Finished!
Initializing word embedding with word2vec...
Finished!
.../opennre/framework/data_loader.py:156: RuntimeWarning: divide by zero encountered in true_divide
  self.weight = 1.0 / (self.weight ** 0.05)
=== Epoch 0 train ===
  0%|                                                  | 0/1582 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train_nyt10_pcnn_att.py", line 54, in <module>
    framework.train_model()
  File ".../opennre/framework/bag_re.py", line 121, in train_model
    logits = self.model(label, scope, *args, bag_size=self.bag_size)
  ...
    result = self.forward(*input, **kwargs)
  ...
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  ...
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  ...
IndexError: Caught IndexError in replica 0 on device 0.
Original Traceback (most recent call last):
  File ".../.local/lib/python3.5/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File ".../.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File ".../OpenNRE2019/opennre/model/bag_attention.py", line 92, in forward
    query[scope[i][0]:scope[i][1]] = label[i]
IndexError: index 40 is out of bounds for dimension 0 with size 40

  0%|                                                  | 0/1582 [00:23<?, ?it/s]

**Comment by gaotianyu1350** [comment]
This bug has been fixed. Also, for bag-level relation extraction, since these models use bags to train and these bags do not necessarily have the same size, we need to fix the bag size for parallel training. For fixing the bag size, you can run 

```
python example/train_nyt10_pcnn_att.py --bag_size {BAG_SIZE}
```

**Comment by pvthuy** [comment]
Thanks for fixing it!
However, when I try with bag_size `160`. The training time is extremely slow.
@gaotianyu1350 Could you check it please?

**Comment by gaotianyu1350** [comment]
Hi sorry that I didn't make it clear...  `bag_size` means the size of each bag. Normally a bag would contain only a few sentences (maybe 3~5), so I would recommend setting the `bag_size` no more than 5.

**Comment by pvthuy** [comment]
I got it. Thanks so much!
