### ISSUE TITLE
Not able to download the models

### ISSUE THREAD

**Issue by shivakarthiks** [thunlp/OpenNRE#209]
>>> import opennre
>>> model = opennre.get_model('wiki80_cnn_softmax')
the second command is not able to download the models. Getting the following error
http://193.112.16.83:8080/opennre/pretrain/nre/wiki80_cnn_softmax.pth.tar
Connecting to 193.112.16.83:8080... failed: Connection timed out.
Retrying.

**Comment by gaotianyu1350** [comment]
For me the website is fine. Maybe check your network or change to another one?

**Comment by mikeleatila** [comment]
Hi, I wanted to download Chinese pretrained models 'people_chinese_bert_softmax' or 'people_delunknown_chinese_bert_softmax', however these links seems not to be active anymore (below). Is there an alternative link where I can fetch it? Thanks in advance

https://thunlp.oss-cn-qingdao.aliyuncs.com/opennre/ckpt/people_chinese_bert_softmax.pth.tar

https://thunlp.oss-cn-qingdao.aliyuncs.com/opennre/ckpt/people_delunknown_chinese_bert_softmax.pth.tar

**Comment by naoki623** [comment]
感谢您的来信，我已成功收取。
