### ISSUE TITLE
有以下问题想咨询一下

### ISSUE THREAD

**Issue by snowxiaoru** [thunlp/OpenNRE#21]
1.训练语料和测试语料 类别数目不平衡问题
    对论文中用的语料进行了统计，统计数目如下：
    训练 ：共53个类别，语料大小 55w+，其中，NA类别数目占据 40w+
    预测： 共32个类别，语料大小 17w+，其中 NA类别语料数目占据 15w+
    发现训练语料中 NA类别的语料 太多，这样直接导致绝大多数被预测为NA类型，严重影响各类别准确率和召回率
    对这种情况的语料，你们在训练前有没有做一些预处理，还是直接使用的是这种类别数目不平衡的语料进行训练的？

2.准确率评估方式
    论文中，会对分值较高的前100,200,300类别进行准确率评估，这种评估是否是剔除NA这种类别后得到的？

3.准确率不一致问题
    按照论文提供的origin_data中的语料进行训练和测试的，由于类别数目的不平衡，导致预测只预测出了两个类别，
    剔除掉NA类别，P@100 p@200 p@300的准确率 分别为0.09、0.07和0.067，导致这个结果的原因有哪些呢？

**Comment by 1969931493** [comment]
@snowxiaoru  请教如何利用提供的模型进行预测并输出具体实体关系结果

**Comment by li10141110** [comment]
显然 NA给带来了很多噪音，现在改进NA负例就可以很好提高模型效果了

**Comment by li10141110** [comment]
@snowxiaoru 你好可以加微信聊聊这个NA的问题吗，我叫李晶 我的微信lijingx-

**Comment by lilmuggle** [comment]
@li10141110 请问怎么改进NA负例来提高模型效果呢？

**Comment by li10141110** [comment]
@lilmuggle add wechat
