### ISSUE TITLE
好多函数参数的注释部分和代码实际的返回结果都不一样，还有transformer 并没有实现

### ISSUE THREAD

**Issue by VinnyHu** [thunlp/OpenNRE#210]

**Comment by gaotianyu1350** [comment]
Transfermer 实现了呀，参见example/train_wiki80_bert_softmax.py

**Comment by VinnyHu** [comment]
> Transfermer 实现了呀，参见example/train_wiki80_bert_softmax.py

偶偶，我后来看到了，那里是我没仔细看，打扰了，谢谢回复
