### ISSUE TITLE
关于PCNN中mask矩阵的问题

### ISSUE THREAD

**Issue by Maybewuss** [thunlp/OpenNRE#211]
为什么self._minus 要设置成一百-100，这个值不是应该越低约好吗？
pool1，pool2，pool3那里为什么要先过relu再进行pooling，这样不会出问题吗，比如所有的值都是小于0，relu之后不就变成一个零向量了吗？

**Comment by gaotianyu1350** [comment]
一般来说-100就够了，如果embedding里面学出绝对值比这还大的估计要gradient explode了

变成0没关系啊，反正要取max

**Comment by Maybewuss** [comment]
变成0没关系，反正要取max
对max来说还是有关系的吧，假设x的值都是小于0的，relu完再max好好像不能反映出原始值中的max信息。
对于梯度来说确实是没关系，反正到relu这负值的梯度就断掉了，relu在前在后无所谓。
