### ISSUE TITLE
data_loader中的 seqs问题

### ISSUE THREAD

**Issue by VinnyHu** [thunlp/OpenNRE#212]
您好，按照我看源码的理解，seqs中存储的应该是 index_token,pos,pos2,mask这几部分，然后在__getitem__中返回的是对每个bag数据的处理，返回一个包的关系、名字、大小、还有具体的id数据。在collate_fn中是对batch的处理，这时候有batch个label,name,count，按照逻辑seqs中的数据不是也应该有batch个才对吗？因为我复现pcnn的代码，没有加attention，用了您的代码后这里遇到了不一致，来请教下您是怎么处理seqs的， nsum指的是什么呢？一个bag里面的句子数量吗？谢谢

**Comment by gaotianyu1350** [comment]
这里collate fn是会把每个bag里面的句子拼在一起的，nsum指的就是所有bag里面句子数的和。因为不同的entity pair对应的bag大小可能不一样，所以nsum也是会变化的。在给定的样例里面有一个参数`bag_size`，可以指定一个固定的bag的大小，这种情况下实现会稍有不同。

**Comment by VinnyHu** [comment]
> 这里collate fn是会把每个bag里面的句子拼在一起的，nsum指的就是所有bag里面句子数的和。因为不同的entity pair对应的bag大小可能不一样，所以nsum也是会变化的。在给定的样例里面有一个参数`bag_size`，可以指定一个固定的bag的大小，这种情况下实现会稍有不同。

您好，主要是seqs后面的那个torch.cat 我看的不是太懂，seqs[0] 应该是一个 (batch_size,bag_size,max_length)维度的一个张量吧，然后经过一个cat后，那里看的不是太懂，能不能解释下？谢谢您了！

**Comment by VinnyHu** [comment]
> 这里collate fn是会把每个bag里面的句子拼在一起的，nsum指的就是所有bag里面句子数的和。因为不同的entity pair对应的bag大小可能不一样，所以nsum也是会变化的。在给定的样例里面有一个参数`bag_size`，可以指定一个固定的bag的大小，这种情况下实现会稍有不同。

问题解决了，谢谢您
