### ISSUE TITLE
torch==1.3.0版本号找不到问题

### ISSUE THREAD

**Issue by wangxinyi-gsafety** [thunlp/OpenNRE#213]
请问我在运行pip install -r requirements.txt时出现torch版本1.3.0找不到的错误：
Collecting torch==1.3.0 (from -r requirements.txt (line 21))
  Could not find a version that satisfies the requirement torch==1.3.0 (from -r requirements.txt (line 21)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
No matching distribution found for torch==1.3.0 (from -r requirements.txt (line 21))

能帮忙解决一下吗？thanks.

**Comment by chendh16** [comment]
请问这个问题怎么解决？

**Comment by gaotianyu1350** [comment]
可以使用1.3之后的版本
