### ISSUE TITLE
import opennre 出错

### ISSUE THREAD

**Issue by suifeng321** [thunlp/OpenNRE#217]
安装后import opennre 出错：TypeError: expected str, bytes or os.PathLike object, not NoneType，请问有遇到同样问题的吗？

**Comment by gaotianyu1350** [comment]
Please provide more details (e.g., system version, detailed error message)

**Comment by suifeng321** [comment]
>>> import opennre
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "G:\ProgramData\Anaconda3\lib\site-packages\opennre-0.1-py3.6.egg\opennre
\__init__.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "G:\ProgramData\Anaconda3\lib\site-packages\opennre-0.1-py3.6.egg\opennre
\pretrain.py", line 10, in <module>
  File "G:\ProgramData\Anaconda3\lib\ntpath.py", line 75, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
>>>

**Comment by wshzd** [comment]
Just now, l also meet the same error when import opennre. My platform is windows10,my package is as follows:
Package         Version
--------------- ---------
boto3           1.10.2
botocore        1.13.34
certifi         2019.9.11
chardet         3.0.4
Click           7.0
docutils        0.15.2
idna            2.8
jmespath        0.9.4
joblib          0.14.0
nltk            3.4.5
numpy           1.17.4
opennre         0.1
Pillow          6.2.1
pip             19.3.1
python-dateutil 2.8.0
regex           2019.8.19
requests        2.22.0
s3transfer      0.2.1
sacremoses      0.0.35
scikit-learn    0.21.3
scipy           1.3.3
sentencepiece   0.1.83
setuptools      42.0.2
six             1.13.0
sklearn         0.0
torch           1.3.1+cpu
torchvision     0.4.2+cpu
tqdm            4.40.1
transformers    2.1.1
urllib3         1.25.7
wheel           0.33.6

**Comment by gaotianyu1350** [comment]
Sorry that for now we only support the Linux platform. Maybe you can try to use the ubuntu command line in Windows 10, or you can change the path format (the error is mainly due to the different formats of path between Linux and windows).

**Comment by wshzd** [comment]
yes, you are right.import opennre is ok on ubuntu platform,thank you.@gaotianyu1350

**Comment by GLZ1925** [comment]
只要将opennre文件夹下的pretrain.py  Line 11的os.getenv('HOME')改成当前文件夹目录名即可import

**Comment by GLZ1925** [comment]
修改opennre下的pretrain.py line11 改为default_root_path = os.path.join(os.getcwd(), '.opennre')，windows下没有HOME环境变量，然后wget的部分改成window右斜杠的目录命名方法，并下载window下的wget.exe并设置环境变量，既可以在windows下运行easy start

**Comment by Arasaraja** [comment]
Change C:\Users\......\OpenNRE\opennre -> pretrain.py line no 11 as below.
default_root_path = os.path.join(os.getcwd(), '.opennre')

**Comment by GLZ1925** [comment]
感谢解答！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月14日(周四) 下午4:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [thunlp/OpenNRE] import opennre 出错 (#217)




  
修改opennre下的pretrain.py line11 改为default_root_path = os.path.join(os.getcwd(), '.opennre')，windows下没有HOME环境变量，然后wget的部分改成window右斜杠的目录命名方法，并下载window下的wget.exe并设置环境变量，既可以在windows下运行easy start
  
it works on macOS too

**Comment by leslie991123** [comment]
> 修改opennre下的 pretrain.py line11 改为default_root_path = os.path.join（os.getcwd（）， '.opennre'），windows下没有HOME环境变量，然后wget的部分改成window右斜杠的目录命名方法，并下载window下的wget.exe并设置环境变量，既可以在windows下运行easy start

请问如何下载window下的wget.exe并设置环境变量呢，有没有大哥具体说一下
