### ISSUE TITLE
ImportError: cannot import name 'get_linear_schedule_with_warmup'

### ISSUE THREAD

**Issue by wshzd** [thunlp/OpenNRE#218]
According to the README.md, l have installed transformers  2.1.1,however,l meet the error that ImportError: cannot import name 'get_linear_schedule_with_warmup' when l run the example of train_wiki80_cnn_softmax.py. how l should do?

**Comment by gaotianyu1350** [comment]
`transformers` has now updated its interface, and simply upgrading it can solve the problem.
