### ISSUE TITLE
请问下bag attention， train时 使用label作为输入，这样提升大么，比一般的attention

### ISSUE THREAD

**Issue by guotong1988** [thunlp/OpenNRE#222]
感谢！！！
感谢！！！
感谢！！！
@zibuyu @Mrlyk423 @cgallay @cclauss @alphaf52 @gaotianyu1350 @THUCSTHanxu13

**Comment by gaotianyu1350** [comment]
和一般的attention比是指？train的时候需要label是因为要用label做key去和bag里面的instance做attention，没有label的话优化会比较慢

**Comment by guotong1988** [comment]
就是不用label输入的attention，
感谢

**Comment by guotong1988** [comment]
我理解bag attention是对 所有bag优化出一个每个bag的权重吗

**Comment by gaotianyu1350** [comment]
是优化bag里面instance的权重，不是bag的权重

**Comment by guotong1988** [comment]
instance 是指？
弱问，感谢！

**Comment by guotong1988** [comment]
一般就是3个bag是吧？

**Comment by gaotianyu1350** [comment]
instance就是句子。bag size大多在3左右，不是bag的数量是3。如果要了解更多的话，建议阅读论文 https://www.aclweb.org/anthology/P16-1200v2.pdf
