### ISSUE TITLE
Question about the data preprocess 

### ISSUE THREAD

**Issue by hningbo** [thunlp/OpenNRE#225]
The length of the sentences is different so when we feed a  batch into the model, we should ensure that all the sentences are in the same length. And i have some questions in this process:
* If we pad the sentence with 0 directly, there may be some problems when we find the corresponding item in the word embedding as well as position embedding. 
* If we pad something behind the tail of the sentence, will the output of the 3rd  part of piecewise max pooling change?

**Comment by gaotianyu1350** [comment]
For PCNN, since we use max pooling and padding 0, the padding content will not change the piecewise pooling results.
