### ISSUE TITLE
Quesiotn about extracting relations between temporal entities

### ISSUE THREAD

**Issue by shodayme** [thunlp/OpenNRE#226]
Hi everyone,

I'd like to know if OpenNRE supports the extraction of relations between temporal entities (such as date and time mentions.)  To detect the order of events in a document.  ( for instance, if we take the example " Sunday morning, he ate  before going out ", we have 2 events : "ate" and "going out" that both happened "Sunday morning" and linked with a relation of "before". 

Thank you.

**Comment by gaotianyu1350** [comment]
So basically you are talking about extracting relations between events. OpenNRE is designed for normal named entities (that could be easily recognized) and this is beyond that. I think the tricky part here is to recognize "ate" and "going out" in the sentence. Of course, if you have some human annotations for that, it would be a lot easier.

**Comment by shodayme** [comment]
I see. Thank you for the clarification.
