### ISSUE TITLE
doubt on dataset

### ISSUE THREAD

**Issue by SreenijaK** [thunlp/OpenNRE#228]
{"sentext": " But that spasm of irritation by a master intimidator was minor compared with what Bobby Fischer , the erratic former world chess champion , dished out in March at a news conference in Reykjavik , Iceland . ", "entities": ["Bobby Fischer", "Reykjavik", "Iceland"], "ID": 1, "relations": [{"rtext": "/people/person/nationality", "em2": "Iceland", "em1": "Bobby Fischer", "tags": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 5, 0]}, {"rtext": "/location/country/capital", "em2": "Reykjavik", "em1": "Iceland", "tags": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 4, 0]}, {"rtext": "/people/deceased_person/place_of_death", "em2": "Reykjavik", "em1": "Bobby Fischer", "tags": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 6, 0]}]}

what does tags here indiacte?

**Comment by gaotianyu1350** [comment]
Which dataset it is ?

**Comment by SreenijaK** [comment]
Its from NYT11 dataset

**Comment by gaotianyu1350** [comment]
I think it may be some POS-tag result? I discard these in our maintained dataset since it is not helpful for current models. Back then there are models taking these as inputs to get better results.
