### ISSUE TITLE
dataset Issue

### ISSUE THREAD

**Issue by SreenijaK** [thunlp/OpenNRE#229]
So, 'Is this how the dataset should look like?

{"text": "Not many people have cooler family closets to raid than Theodora Richards , the daughter of the Rolling Stones guitarist Keith Richards and the 70 's supermodel Patti Hansen .", "relation": "/people/person/children", "h": {"id": "/guid/9202a8c04000641f8000000000dad102", "name": "Patti Hansen", "pos": [161, 173]}, "t": {"id": "/guid/9202a8c04000641f8000000000d4eb59", "name": "Theodora Richards", "pos": [56, 73]}}.

If so, what does the if refer to? ex:
 "id": "/guid/9202a8c04000641f8000000000dad102"

**Comment by gaotianyu1350** [comment]
It is the freebase id of the entity.
