### ISSUE TITLE
Cannot download nyt10

### ISSUE THREAD

**Issue by zxc2012** [thunlp/OpenNRE#232]
Maybe the sever is disconnect

**Comment by gaotianyu1350** [comment]
We just changed to a new download server. Please pull the latest commit and then you should be able to download the data.

**Comment by gaotianyu1350** [comment]
We just changed to a new download server. Please pull the latest commit and then you should be able to download the data.

**Comment by HsimWong** [comment]
The download server is still unavailable. Please help check it.
root@shanghai:~/OpenNRE/pretrain# cat download_bert.sh
mkdir bert-base-uncased
wget -P bert-base-uncased http://193.112.16.83:8080/opennre/pretrain/bert-base-uncased/config.json
wget -P bert-base-uncased http://193.112.16.83:8080/opennre/pretrain/bert-base-uncased/pytorch_model.bin
wget -P bert-base-uncased http://193.112.16.83:8080/opennre/pretrain/bert-base-uncased/vocab.txt

**Comment by gaotianyu1350** [comment]
Sorry that I forgot to update the scripts. Now it should work.
