### ISSUE TITLE
关于bag的标签

### ISSUE THREAD

**Issue by ShellingFord221** [thunlp/OpenNRE#233]
你好，因为原始NYT数据集是给每个句子一个标签的，为了at-least-one assumption需要把相同实体对的句子放在一起形成bag。如果这些句子原始被标记了多个标签，那么bag的标签应该选取哪一个呢？（假设在multi-instance one label的情况下，因为早期贵组的多篇文章都是基于multi-instance one label的）

**Comment by gaotianyu1350** [comment]
这样的话会把这一个bag复制成多个，每个有一个不同的标签。

**Comment by yangluojun** [comment]
还是不太清楚bag的标签问题，一个bag包含n个相同实体对的句子，bag会复制成n个吗？然后将句子的标签当做bag的标签。

**Comment by gaotianyu1350** [comment]
不是。比如说(Barack Obama, US)，它有两个label：president of和citizen of。那么对于所有包含(Barack Obama, US)的句子，会在两个bag里：（Barack Obama, US, president of）和（Barack Obama, US, citizen of）

**Comment by yangluojun** [comment]
> 不是。比如说(Barack Obama, US)，它有两个label：president of和citizen of。那么对于所有包含(Barack Obama, US)的句子，会在两个bag里：（Barack Obama, US, president of）和（Barack Obama, US, citizen of）

那么，这两个包的label其实是来自最开始知识库（如freebase）准确的标注吗？如果是这样，数据好像没有标明这一点。问题比较初级，望不吝赐教。

**Comment by gaotianyu1350** [comment]
是的，标注都来自freebase。这种标注方式叫distant supervision，是由[Distant supervision for relation extraction without labeled data](https://www.aclweb.org/anthology/P09-1113.pdf)这篇论文提出的，NYT数据集是[Modeling Relations and Their Mentions without
Labeled Text](https://link.springer.com/content/pdf/10.1007/978-3-642-15939-8_10.pdf)提出的。
