### ISSUE TITLE
Question about example

### ISSUE THREAD

**Issue by qkl123** [thunlp/OpenNRE#236]
when I run train_nyt10_pcnn_att.py,the error shows:
Traceback (most recent call last):
  File "train_nyt10_pcnn_att.py", line 21, in <module>
    opennre.download_nyt10(root_path=root_path)
AttributeError: module 'opennre' has no attribute 'download_nyt10'

**Comment by gaotianyu1350** [comment]
Thanks for the reminder. The bug has been fixed.

**Comment by qkl123** [comment]
How to fix?download again or do something else?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tianyu Gao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月2日(星期四) 上午10:19
收件人:&nbsp;"thunlp/OpenNRE"<OpenNRE@noreply.github.com&gt;;
抄送:&nbsp;"123"<2863496189@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [thunlp/OpenNRE] Question about example (#236)





 
Thanks for the reminder. The bug has been fixed.

**Comment by gaotianyu1350** [comment]
Just pull the latest commit and the bug will go away.

**Comment by qkl123** [comment]
The model will get a new error,should I create a new file?
The issue is:
Traceback (most recent call last):
&nbsp; File "train_nyt10_pcnn_att.py", line 20, in <module&gt;
&nbsp;&nbsp;&nbsp; opennre.download('nyt10', root_path=root_path)
&nbsp; File "/usr/local/lib/python3.6/dist-packages/opennre-0.1-py3.6.egg/opennre/pretrain.py", line 68, in download
&nbsp; File "/usr/local/lib/python3.6/dist-packages/opennre-0.1-py3.6.egg/opennre/pretrain.py", line 31, in download_nyt10
FileNotFoundError: [Errno 2] No such file or directory: './benchmark/nyt10'






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tianyu Gao"<notifications@github.com&gt;; 
发送时间: 2020年4月2日(星期四) 下午2:17
收件人: "thunlp/OpenNRE"<OpenNRE@noreply.github.com&gt;; 
抄送: "123"<2863496189@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [thunlp/OpenNRE] Question about example (#236)





 
Just pull the latest commit and the bug will go away.

**Comment by gaotianyu1350** [comment]
Are you sure you have pulled the latest commit? It works fine for me.

**Comment by qkl123** [comment]
I have pulled the latest commit,then this error will occur.
"/usr/local/lib/python3.6/dist-packages/opennre-0.1-py3.6.egg/opennre/framework/data_loader.py:166: RuntimeWarning: divide by zero encountered in true_divide


RuntimeError: non-empty 3D or 4D input tensor expected but got ndim: 4"





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tianyu Gao"<notifications@github.com&gt;; 
发送时间: 2020年4月3日(星期五) 晚上6:07
收件人: "thunlp/OpenNRE"<OpenNRE@noreply.github.com&gt;; 
抄送: "123"<2863496189@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [thunlp/OpenNRE] Question about example (#236)





 
Are you sure you have pulled the latest commit? It works fine for me.

**Comment by qkl123** [comment]
The error occurs when I python example/train_nyt10_pcnn_att.py.
The computer will save all .txt,but this error will occur in the end.





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tianyu Gao"<notifications@github.com&gt;; 
发送时间: 2020年4月3日(星期五) 晚上6:07
收件人: "thunlp/OpenNRE"<OpenNRE@noreply.github.com&gt;; 
抄送: "123"<2863496189@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [thunlp/OpenNRE] Question about example (#236)





 
Are you sure you have pulled the latest commit? It works fine for me.

**Comment by gaotianyu1350** [comment]
Maybe you can delete all the download data and try again. It may be caused by an incomplete download.

**Comment by qkl123** [comment]
I will try again




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tianyu Gao"<notifications@github.com&gt;; 
发送时间: 2020年4月5日(星期天) 中午1:57
收件人: "thunlp/OpenNRE"<OpenNRE@noreply.github.com&gt;; 
抄送: "123"<2863496189@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [thunlp/OpenNRE] Question about example (#236)





 
Maybe you can delete all the download data and try again. It may be caused by an incomplete download.

**Comment by qkl123** [comment]
this error also exists.I send you the screen captures.








------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tianyu Gao"<notifications@github.com&gt;; 
发送时间: 2020年4月5日(星期天) 中午1:57
收件人: "thunlp/OpenNRE"<OpenNRE@noreply.github.com&gt;; 
抄送: "123"<2863496189@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [thunlp/OpenNRE] Question about example (#236)





 
Maybe you can delete all the download data and try again. It may be caused by an incomplete download.

**Comment by qkl123** [comment]
Which python file in example folder should I first run?



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tianyu Gao"<notifications@github.com&gt;; 
发送时间: 2020年4月5日(星期天) 中午1:57
收件人: "thunlp/OpenNRE"<OpenNRE@noreply.github.com&gt;; 
抄送: "123"<2863496189@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [thunlp/OpenNRE] Question about example (#236)





 
Maybe you can delete all the download data and try again. It may be caused by an incomplete download.
