### ISSUE TITLE
BERTEncoder的tokenize输入要是是text,h,t的时候，没必要tokenize两次

### ISSUE THREAD

**Issue by Jacen789** [thunlp/OpenNRE#240]
95行，re_tokens += self.tokenizer.tokenize(token) 可以加个判断。不然已经tokenize一次之后的'##l'、'##in'、'##le'等会被再次被tokenize成['#', '#', 'l'], ...。

**Comment by gaotianyu1350** [comment]
感谢提醒，bug fixed
