### ISSUE TITLE
Information about the models

### ISSUE THREAD

**Issue by kemalaraz** [thunlp/OpenNRE#242]
wiki80_bert or wiki80_cnn which one is better, have you done any evaluations on them? In addition to that which dataset did you use to train those models? Can I get better results if I train wihch nyt10 dataset?

Thanks

**Comment by kemalaraz** [comment]
By the way is there a train option for your models?

**Comment by gaotianyu1350** [comment]
wiki80_bert is better. It is trained by wiki80 dataset.
