### ISSUE TITLE
I can't reproduce the results of your paper through this framework

### ISSUE THREAD

**Issue by superwars** [thunlp/OpenNRE#246]
I run example/train_nyt10_pcnn_att.py, but the result are not up to those reported in this paper "Neural Relation Extraction with Selective Attention over Instances". Are there any problems in your reproduce code?

**Comment by gaotianyu1350** [comment]
Which metric you were referring to? Can you provide specific results / outputs?

**Comment by mrzhaojun** [comment]
After finish the training process in file "example/train_nyt10_pcnn_att.py", I use "result['prec'][99], result['prec'][199], result['prec'][299]" to get P@100, P@200, P@300 respectively. They are 0.71, 0.66, 0.59, different from the results reported in table2 of original paper which are 76.2, 73.1, 67.4. Is there any problem in my operation？

**Comment by mrzhaojun** [comment]
What adjustments do I need to make to get the results reported in the original paper？

**Comment by mrzhaojun** [comment]
In addition, errors are reported when running programs on multiple GPUs (RuntimeError: unsupported operation: more than one element of the written-to tensor refers to a single memory location. Please clone() the tensor before performing the operation.). So I run the program on a single GPU to avoid this error. I don't know if this will cause the results to decrease. 

`Traceback (most recent call last):
  File "train_nyt10_pcnn_att.py", line 62, in <module>
    result = framework.eval_model(framework.test_loader)
  File "/home/jzhao/program/RE/OpenNRE/opennre/framework/bag_re.py", line 159, in eval_model
    for iter, data in enumerate(t):
  File "/home/jzhao/anaconda3/envs/opennre/lib/python3.6/site-packages/tqdm/std.py", line 1104, in __iter__
    for obj in iterable:
  File "/home/jzhao/anaconda3/envs/opennre/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/jzhao/anaconda3/envs/opennre/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/jzhao/anaconda3/envs/opennre/lib/python3.6/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in pin memory thread for device 0.
Original Traceback (most recent call last):
  File "/home/jzhao/anaconda3/envs/opennre/lib/python3.6/site-packages/torch/utils/data/_utils/pin_memory.py", line 31, in _pin_memory_loop
    data = pin_memory(data)
  File "/home/jzhao/anaconda3/envs/opennre/lib/python3.6/site-packages/torch/utils/data/_utils/pin_memory.py", line 55, in pin_memory
    return [pin_memory(sample) for sample in data]
  File "/home/jzhao/anaconda3/envs/opennre/lib/python3.6/site-packages/torch/utils/data/_utils/pin_memory.py", line 55, in <listcomp>
    return [pin_memory(sample) for sample in data]
  File "/home/jzhao/anaconda3/envs/opennre/lib/python3.6/site-packages/torch/utils/data/_utils/pin_memory.py", line 47, in pin_memory
    return data.pin_memory()
RuntimeError: unsupported operation: more than one element of the written-to tensor refers to a single memory location. Please clone() the tensor before performing the operation.`

**Comment by gaotianyu1350** [comment]
If you are looking for the original code of the paper, you can refer to [this repo](https://github.com/thunlp/NRE). We now usually use auc (area under the curve) instead of p@n to evaluate and this implementation should have achieved better auc than the original reported result.

**Comment by gaotianyu1350** [comment]
Besides, in the given code, we actually divide the training set into training and validation set (the original dataset does not have a validation set), which may also degenerate the final figure a little.

**Comment by gaotianyu1350** [comment]
As for multi-gpu training, you need to specify the `--bag_size` arg.

**Comment by mrzhaojun** [comment]
Thanks for your reply. But I still have two questions.

Firstly, I combined the train set and dev set to get a new train set, and the best auc value is 0.325 which is not up to the value reported in your paper(0.349). Do I need to reduce learning rate for better results.

Secondly, I ran the code from this [repo](https://github.com/thunlp/NRE) you provided, but there is a gap between the PR curves I got and PR curves the original paper reported. I noticed that there was an old [dataset](https://github.com/thunlp/NRE/commit/77025e5cc6b42bc1adf3ec46835101d162013659), and I get similar result based on this dataset. So I want to confirm whether the results reported in this paper are based on old version dataset.

**Comment by gaotianyu1350** [comment]
I'm not the author of the paper, but I remember that indeed they use an old version of the dataset for the reported result, which contain shared entity pairs between train and test sets. The public dataset now has eliminated this problem so the reimplemented result may not match the reported result.

But this reimplemented result is lower than our tensorflow version (in the `tensorflow` branch). I haven't noticed this before. I will look into this, thanks!

**Comment by mrzhaojun** [comment]
I got it. Thanks!

**Comment by zhanqiuzhang** [comment]
> I'm not the author of the paper, but I remember that indeed they use an old version of the dataset for the reported result, which contain shared entity pairs between train and test sets. The public dataset now has eliminated this problem so the reimplemented result may not match the reported result.
> 
> But this reimplemented result is lower than our tensorflow version (in the `tensorflow` branch). I haven't noticed this before. I will look into this, thanks!

Hi. I ran the current pcnn+att model and got an auc value of 0.324, which is still lower than the tensorflow version. Have you fix the problem? Thanks!

**Comment by gaotianyu1350** [comment]
Move to #264
