### ISSUE TITLE
求助，想要重新训练数据集

### ISSUE THREAD

**Issue by haoliaoge** [thunlp/OpenNRE#247]
OpenNRE能训练中文数据集吗？该怎么添加

**Comment by doudouaili** [comment]
不知道啊，连一个文档都没得。

**Comment by gaotianyu1350** [comment]
目前OpenNRE还没有直接对中文做适配，但只要修改模型的tokenize函数为支持中文，就可以训练中文的数据了。现在的tokenize只适用于英文的分词
