### ISSUE TITLE
how to segment sentence into 3 pieces?

### ISSUE THREAD

**Issue by eveliao** [thunlp/OpenNRE#248]
https://github.com/thunlp/OpenNRE/blob/704479a813dbb2e2b0377ae56d2dc8a82d388c7a/opennre/encoder/pcnn_encoder.py#L156-L165

For example, given a sentence 'This is head_1 head_2 and tail_1 tail_2.', head and tail are two-word entities. According to the code, the mask should be [1,1,1,2,2,2,3,3,3]. Thus pieces are [This, is, head_1] [head_2, and, tail_1] [tail_2, .]
The entities are splitted. Why?

Besides, why should it add 'self.max_length' ?
https://github.com/thunlp/OpenNRE/blob/704479a813dbb2e2b0377ae56d2dc8a82d388c7a/opennre/encoder/pcnn_encoder.py#L138-L140

**Comment by gaotianyu1350** [comment]
For the first question, since we use CNN with window_size=3, the second piece and the third piece can see the whole first entity and the whole second entity. For the second question, we add `self.max_length` to make sure the index is non-negative.
