### ISSUE TITLE
bag_re attention的计算方式

### ISSUE THREAD

**Issue by VinnyHu** [thunlp/OpenNRE#250]
您好，在原始论文中，e_i = x_i A r_i
A是一个权重对角矩阵，是不是可以理解为，A相当于对关系表示，每个维度做了个权重。
但是在您的代码实现中，并没有实现A。
这样的理解对吗？

**Comment by gaotianyu1350** [comment]
在实验中我们发现不用A效果会更好，所以在这里的实现中没有加A
