### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by cdhx** [thunlp/OpenNRE#252]
import opennre
got error
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by mufishhh** [comment]
I had the same problem with you when I started using Windows OS. Check other people's blogs, I switch to Linux, and then get the results.

**Comment by gaotianyu1350** [comment]
Sorry that for now OpenNRE only supports Linux platform. If you are using Windows, please try to run it in WSL.
