### ISSUE TITLE
about attention

### ISSUE THREAD

**Issue by ElliottYan** [thunlp/OpenNRE#26]
I read your code and got confused in the attention you use. In my understanding, the attention should grab the attention for each sentence and each words in a sentence. But I found that you shuffle your train_words, this just doesn't make any sense to me.

**Comment by pvthuy** [comment]
Hi, I am new to this repository. Is the problem you mentioned is a big issue?

**Comment by THUCSTHanxu13** [comment]
Our attention is used to compute the weight score for each sentence. We have reconstructed the code.
