### ISSUE TITLE
Questions about details of wiki80

### ISSUE THREAD

**Issue by tanyifans** [thunlp/OpenNRE#263]
I have checked the paper of FewRel
It seems that there is no explanation about the relations defined in the dataset, so is wiki80.
Can you tell me how to find its detailed explanation with example? My boss finds it hard to explain the knowlegde graph extracted by this dataset

**Comment by gaotianyu1350** [comment]
You can refer to the FewRel [readme page](https://github.com/thunlp/FewRel) and find `pid2name.json` for the relation name and description details.

**Comment by waterhall** [comment]
pid2name.json contains 744 relations though, not 80. Is there any way to figure out what are the 80 relations in wiki80?

**Comment by waterhall** [comment]
I went through train_wiki.json and val_wiki.json in [FewRel](https://github.com/thunlp/FewRel/tree/master/data) and found the 80 relations.
