### ISSUE TITLE
nyt val dataset and test dataset

### ISSUE THREAD

**Issue by nttmac** [thunlp/OpenNRE#266]
Hello!
I found that the val dataset and test dataset of nyt are the same. Is this the original nyt dataset?
Thank you in advance!

**Comment by gaotianyu1350** [comment]
Yes, it is the original NYT dataset. The original NYT dataset does not have a validation set, and for the consistency of the API I just make the val set the same as the test set.

**Comment by nttmac** [comment]
> Yes, it is the original NYT dataset. The original NYT dataset does not have a validation set, and for the consistency of the API I just make the val set the same as the test set.

Thank you for your nice explanation!
