### ISSUE TITLE
"HOME"值

### ISSUE THREAD

**Issue by LLGISer** [thunlp/OpenNRE#268]
在opennre\pretrain.py这个文件下有default_root_path = os.path.join(os.getenv('HOME'), '.opennre')这样一个默认根路径，请问这个"HOME"环境变量设置成什么，可以请您解答一下吗？十分感谢

**Comment by LLGISer** [comment]
这个一定要在Linux下使用吗

**Comment by gaotianyu1350** [comment]
目前仅支持linux哈，指的是linux下的home目录。如果要在windows上用的话建议用windows 10中的ubuntu终端
