### ISSUE TITLE
Train on own dataset

### ISSUE THREAD

**Issue by reobroqn** [thunlp/OpenNRE#271]
Thanks for your working!
Can you describe a little more detail how to prepare my own data so i can train on it. And this is training from scratch or fine-tune: load weights from pre-trained model and continue to train on new data?
Would appreciate if u also show how to run train. >.<

**Comment by gaotianyu1350** [comment]
If you are preparing a supervised (human-annotated) dataset, you can refer to the format of datasets `semeval` or `wiki80`. If you are preparing a distantly-supervised dataset, you can refer to the format of datasets `nyt10` or `wiki_distant`. To download them, just install the package, import the package in python, and do 

```
opennre.download('DATASET NAME', root_path='WHERE YOU WANT TO DOWNLOAD THE DATASET TO')
```

For different kinds of training, you can refer to the `example` folder. BERT is a pre-trained model and CNN is trained from scratch.

**Comment by reobroqn** [comment]
Okay, many thanks!

**Comment by kbrajwani** [comment]
Hi can please you suggest some tool for human-annotation work?
