### ISSUE TITLE
opennre.download('glove', root_path=root_path)

### ISSUE THREAD

**Issue by haojing100** [thunlp/OpenNRE#272]
I don't understand the function of download(). And I could not find where is it? could you tell me? Thanks.

**Comment by haojing100** [comment]
__init__.py of opennre has from .pretrain import check_root, get_model, download, download_pretrain .

**Comment by gaotianyu1350** [comment]
It's in `opennre/pretrain.py`

**Comment by haojing100** [comment]
> It's in `opennre/pretrain.py`

yes, I find it.  Thanks.
