### ISSUE TITLE
bert+attention

### ISSUE THREAD

**Issue by haojing100** [thunlp/OpenNRE#275]
I want to input a bag sentences to model of bert+attention, so I use 
sentence_encoder = opennre.encoder.BERTEncoder()
model = opennre.model.BagAttention()
framework = opennre.framework.BagRE()
And has a TypeError :forward() missing 1 required positional argument: 'pos2'
So I add pos1,pos2 in BERTEncoder's tokenizen() ,and return indexed_tokens,pos1,pos2,att_mask .
Then have an TypeError: forward() takes 3 positional arguments but 5 were given (in bert+attention model)

And why pcnn+att model is OK?

Traceback (most recent call last):
  File "train_company_people_bert_attention.py", line 59, in <module>
    framework.train_model()
  File "/opennre/framework/bag_re.py", line 122, in train_model
    logits = self.model(label, scope, *args, bag_size=self.bag_size)
  File "/root/miniconda3/envs/python36j/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/envs/python36j/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/root/miniconda3/envs/python36j/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opennre/model/bag_attention.py", line 96, in forward
    rep = self.sentence_encoder(token, pos1, pos2, mask) # (nsum, H)
  File "/root/miniconda3/envs/python36j/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() takes 3 positional arguments but 5 were given

**Comment by haojing100** [comment]
I print the length of data in bag_re.py(line 120), the length is 7, including label ,bag_name,scope ,token_id ,pos1,pos2,mask.

**Comment by haojing100** [comment]
Maybe I know why.
In error say:
File "/opennre/model/bag_attention.py", line 96, in forward
rep = self.sentence_encoder(token, pos1, pos2, mask) # (nsum, H)

And self.sentence_encoder(token, pos1, pos2, mask)  is the forwsrd() of BERTEncoder of bert_encoder.py 
forward(self, token, att_mask) need to add pos1、pos2 parameter
Such as  
def forward(self, token, pos1,pos2,att_mask):
        """
        Args:
            token: (B, L), index of tokens
            pos1:(B, L), relative position to head entity
            pos2:(B, L), relative position to tail entity
            att_mask: (B, L), attention mask (1 for contents and 0 for padding)
        Return:
            (B, H), representations for sentences
        """
        # Check size of tensors
        if len(token.size()) != 2 or token.size() != pos1.size() or token.size() != pos2.size():
            raise Exception("Size of token, pos1 ans pos2 should be (B, L)")
        # need to Inherited class of BaseEncoder
        x = torch.cat([self.word_embedding(token), self.pos1_embedding(pos1), self.pos2_embedding(pos2)], 2) # (B, L, EMBED)
        # x = x.transpose(1, 2) # (B, EMBED, L)  because don't need cnn

        _, x = self.bert(token, attention_mask=att_mask)
        return x

(I need to change tokenize() and forward() ,maybe I could have  a  bert_encoder_for_bag_input_zhj.py )


 def forward(self, token, att_mask):
        """
        Args:
            token: (B, L), index of tokens
            att_mask: (B, L), attention mask (1 for contents and 0 for padding)
        Return:
            (B, H), representations for sentences
        """
        _, x = self.bert(token, attention_mask=att_mask)
        return x

**Comment by gaotianyu1350** [comment]
From my side, simply changing PCNN encoder to BERT works fine. Here is an example code:

```python
# coding:utf-8
import sys, json
import torch
import os
import numpy as np
import opennre
from opennre import encoder, model, framework
import sys
import os
import argparse
import logging

parser = argparse.ArgumentParser()
parser.add_argument('--pretrain_path', default='bert-base-uncased', 
        help='Pre-trained ckpt path / model name (hugginface)')
parser.add_argument('--ckpt', default='', 
        help='Checkpoint name')
parser.add_argument('--only_test', action='store_true', 
        help='Only run test')
parser.add_argument('--pooler', default='entity', choices=['cls', 'entity'], 
        help='Sentence representation pooler')
parser.add_argument('--mask_entity', action='store_true', 
        help='Mask entity mentions')


# Data
parser.add_argument('--metric', default='auc', choices=['micro_f1', 'auc'],
        help='Metric for picking up best checkpoint')
parser.add_argument('--dataset', default='none', choices=['none', 'wiki_distant', 'nyt10'],
        help='Dataset. If not none, the following args can be ignored')
parser.add_argument('--train_file', default='', type=str,
        help='Training data file')
parser.add_argument('--val_file', default='', type=str,
        help='Validation data file')
parser.add_argument('--test_file', default='', type=str,
        help='Test data file')
parser.add_argument('--rel2id_file', default='', type=str,
        help='Relation to ID file')

# Bag related
parser.add_argument('--bag_size', type=int, default=4,
        help='Fixed bag size. If set to 0, use original bag sizes')

# Hyper-parameters
parser.add_argument('--batch_size', default=16, type=int,
        help='Batch size')
parser.add_argument('--lr', default=2e-5, type=float,
        help='Learning rate')
parser.add_argument('--max_length', default=128, type=int,
        help='Maximum sentence length')
parser.add_argument('--max_epoch', default=3, type=int,
        help='Max number of training epochs')

args = parser.parse_args()

# Some basic settings
root_path = '.'
sys.path.append(root_path)
if not os.path.exists('ckpt'):
    os.mkdir('ckpt')
if len(args.ckpt) == 0:
    args.ckpt = '{}_{}'.format(args.dataset, 'pcnn_att')
ckpt = 'ckpt/{}.pth.tar'.format(args.ckpt)

if args.dataset != 'none':
    opennre.download(args.dataset, root_path=root_path)
    args.train_file = os.path.join(root_path, 'benchmark', args.dataset, '{}_train.txt'.format(args.dataset))
    args.val_file = os.path.join(root_path, 'benchmark', args.dataset, '{}_val.txt'.format(args.dataset))
    args.test_file = os.path.join(root_path, 'benchmark', args.dataset, '{}_test.txt'.format(args.dataset))
    args.rel2id_file = os.path.join(root_path, 'benchmark', args.dataset, '{}_rel2id.json'.format(args.dataset))
else:
    if not (os.path.exists(args.train_file) and os.path.exists(args.val_file) and os.path.exists(args.test_file) and os.path.exists(args.rel2id_file)):
        raise Exception('--train_file, --val_file, --test_file and --rel2id_file are not specified or files do not exist. Or specify --dataset')

logging.info('Arguments:')
for arg in vars(args):
    logging.info('    {}: {}'.format(arg, getattr(args, arg)))

rel2id = json.load(open(args.rel2id_file))

# Define the sentence encoder
if args.pooler == 'entity':
    sentence_encoder = opennre.encoder.BERTEntityEncoder(
        max_length=args.max_length, 
        pretrain_path=args.pretrain_path,
        mask_entity=args.mask_entity
    )
elif args.pooler == 'cls':
    sentence_encoder = opennre.encoder.BERTEncoder(
        max_length=args.max_length, 
        pretrain_path=args.pretrain_path,
        mask_entity=args.mask_entity
    )
else:
    raise NotImplementedError

# Define the model
model = opennre.model.BagAttention(sentence_encoder, len(rel2id), rel2id)

# Define the whole training framework
framework = opennre.framework.BagRE(
    train_path=args.train_file,
    val_path=args.val_file,
    test_path=args.test_file,
    model=model,
    ckpt=ckpt,
    batch_size=args.batch_size,
    max_epoch=args.max_epoch,
    lr=args.lr,
    opt='adamw',
    bag_size=args.bag_size)

# Train the model
if not args.only_test:
    framework.train_model(args.metric)

# Test the model
framework.load_state_dict(torch.load(ckpt)['state_dict'])
result = framework.eval_model(framework.test_loader)

# Print the result
logging.info('Test set results:')
logging.info('AUC: {}'.format(result['auc']))
logging.info('Micro F1: {}'.format(result['micro_f1']))
```
