### ISSUE TITLE
您好，想请问下训练集中关于实体的id指的是什么，有什么特殊意义吗？

### ISSUE THREAD

**Issue by wqn1** [thunlp/OpenNRE#276]

**Comment by wqn1** [comment]
![image](https://user-images.githubusercontent.com/25994043/91114161-d54aaa80-e6b9-11ea-9e51-5b52a0102f24.png)

**Comment by gaotianyu1350** [comment]
nyt10中的id是对应freebase中的id，wiki80中的id是wikidata中实体对应的id
