### ISSUE TITLE
Getting Wrong result for an example sentence

### ISSUE THREAD

**Issue by sandeeppanem** [thunlp/OpenNRE#28]
**test_sentence :** m.01rvrn	m.04gcbp	carlos_delgado	london	8	carlos_delgado born in london.	###END###

Output probabilities 

[  5.01433460e-05   1.63105437e-06   7.00082546e-06   2.98229952e-06
   5.45311934e-07   6.56117190e-05   6.24323206e-07   2.14673369e-03
   1.25849142e-03   1.26197783e-05   2.83242643e-05   2.55511759e-06
   5.36649859e-05   3.46176557e-06   1.02176155e-05   2.83429472e-06
   4.59302333e-04   1.60637079e-03   4.17622778e-06   1.10091867e-06
   4.65527728e-06   4.34826734e-06   1.03743444e-03   5.94867879e-06
   3.17883896e-05   3.49962011e-06   1.02767524e-06   4.20275348e-04
   6.89600594e-04   6.14084138e-06   1.25078814e-05   4.56587122e-06
   3.20838328e-04   4.89041558e-05   6.01866523e-05   4.32176981e-03
   1.76615795e-05   5.32836020e-06   3.60898866e-06   2.23168536e-05
   8.40354733e-06   1.58599651e-05   2.02828651e-05   3.80020742e-06
   1.28869924e-05   2.95039372e-05   2.95423979e-05   5.42388123e-04
   6.37627591e-06   2.35860600e-04   1.28738247e-05   1.20697114e-05]

Following are the indexes in descending order of probabilities

[**35**  7 17  8 22 28 47 16 27 32 49  5 34 12  0 33 24 46 45 10 39 42 36 41 44
 50  9 30 51 14 40  2 48 29 23 37 20 31 21 18 43 38 25 13  3 15 11  1 19 26
  6  4]

From the output it seems we are getting relation  **/people/person/place_lived 36** , but we should get **/people/person/place_of_birth 8**

Can anyone help on this

**Comment by THUCSTHanxu13** [comment]
It is normal to get wrong prediction, especially for those confusing relations. The relations in the NYT dataset are imbalance, and there is also much noise in this dataset. Hence, it is hard to achieve satisfactory performance on this dataset.
