### ISSUE TITLE
论文结果

### ISSUE THREAD

**Issue by huwf9918** [thunlp/OpenNRE#280]
您好，我在使用您的模型时，每次（从头）训练都会得到不同的结果，请问您当时得到论文的效果训练了多少次呢，如果训练了不止一次的话，是多次训练的结果取平均吗，还是从中选取效果最好的模型呢？

**Comment by gaotianyu1350** [comment]
这里并不是原始论文的代码，原始论文的代码在这里：https://github.com/thunlp/NRE ，用这个仓库得到的结果应该比原始论文要高。

如果波动比较大的话，个人建议是运行多次（如5～10次）算平均+标准差汇报
