### ISSUE TITLE
Delete comment line

### ISSUE THREAD

**Issue by lorelupo** [thunlp/OpenNRE#288]
The following comment has to be deleted because referring to a nonexistent argument :

https://github.com/thunlp/OpenNRE/blob/60a8ceb42e1cfacbde3c8cfb5f758fb7fe96bdc4/opennre/encoder/base_encoder.py#L88

Thanks

**Comment by lorelupo** [comment]
Same goes for the other encoders' tokenize method.

**Comment by lorelupo** [comment]
Also, the calculation of variables `pos1` and `pos2` seems useless for BERTEncoder:

https://github.com/thunlp/OpenNRE/blob/60a8ceb42e1cfacbde3c8cfb5f758fb7fe96bdc4/opennre/encoder/bert_encoder.py#L81

**Comment by gaotianyu1350** [comment]
Thanks for the comment! I have deleted these codes in `c40c680`.
