### ISSUE TITLE
如何使用tacred数据集

### ISSUE THREAD

**Issue by huwf9918** [thunlp/OpenNRE#289]
您好，我在LDC上下载了TACRED数据集，但是该数据集的格式好像无法直接被OpenNRE读取，请问应该如预处理数据集呢？

**Comment by gaotianyu1350** [comment]
将TACRED原始的数据集处理成和OpenNRE其他数据一样的格式即可。具体来说，是一个txt文件，每行一个json代表一条数据，包含"text" / "h" / "t" / "relation"等字段。

**Comment by mchl0203** [comment]
> 您好，我在LDC上下载了TACRED数据集，但是该数据集的格式好像无法直接被OpenNRE读取，请问应该如预处理数据集呢？

你好，请问LDC数据集方便发我一份吗？感谢～ 243814529@qq.com
