### ISSUE TITLE
请问下这个code是哪个paper？

### ISSUE THREAD

**Issue by guotong1988** [thunlp/OpenNRE#29]
readme里好像没说，只说了idea来源和reference

**Comment by cqiang5882** [comment]
同问 后来你找到了么

**Comment by THUCSTHanxu13** [comment]
Relation classification via convolutional deep neural network (COLING14)
Distant supervision for relation extraction via piecewise convolutional neural networks (EMNLP15)
Neural relation extraction with selective attention over instances (ACL16)
adversarial training for relation extraction (EMNLP17)

**Comment by THUCSTHanxu13** [comment]
我们还额外实现了一些神经网络模块，和选择机制模块
