### ISSUE TITLE
我想问下，openNRE中有哪些模型

### ISSUE THREAD

**Issue by zwd13122889** [thunlp/OpenNRE#291]
还有个问题就是，我想自己加入一层模型的话，我该怎么改？
封装的太好了，不知道该咋改

**Comment by gaotianyu1350** [comment]
Hi，

如果是指预先训练好提供下载的模型的话，可以参考`Easy Start`后部列举的模型。如果是指框架里的模型，`encoder`下是各种不同的encoder（CNN，PCNN，BERT），`model`下是不同的范式（sentence-level RE, bag-level RE等）。你可以根据具体需要修改的部分（encoder or model）选择对应修改的地方。
