### ISSUE TITLE
NYT数据集的测试集和验证集是同一个文件

### ISSUE THREAD

**Issue by LiZeC123** [thunlp/OpenNRE#296]
我在今年三月份的时候下载过一次NYT数据集, 最近我重新下载数据集的时候发现测试集(nyt10_test.txt)和验证集(nyt10_val.txt)是同一个文件, 而且测试集的哈希值发生了变化

三月份的时候, 哈希值为
sha1: f1d4673dd8a31f159a7356fd50325dc1616da77b

现在的哈希值为
sha1: 47e3ce1c3660c28aba308dac5a90696965ae3200

我看了文件的开头, 好像也没有变化, 文件的行数也没有变化, 所以想确认一下到底改了哪些内容? 以及现在验证集和测试集是同一个文件是否是之前修改oss资源的错误操作?

**Comment by gaotianyu1350** [comment]
您好，nyt数据集原本是没有验证集的。之前OpenNRE提供的数据集版本是从训练集里挖出了一个验证集。但现在考虑到之前的一些基于nyt的工作均没有验证集，再三考虑我们又换成了和原始数据集一样的版本，然后拿测试集的数据做了验证集的占位符。
