### ISSUE TITLE
pcnn_att模型训练中的bag_size应设置为多大？

### ISSUE THREAD

**Issue by sxtopc** [thunlp/OpenNRE#298]
你好，如果模型训练不是按照bag_level进行的，那么相当于每次取batch_size个token进行训练。
但是对于bag_level的训练模型，参数bag_level应该设置为多少呢？
论文中没有提及这部分内容，项目中全部默认为0，不明白什么意思。
希望有时间的话能够点播一二，谢谢

**Comment by gaotianyu1350** [comment]
bag_size主要是为了并行设计的。默认bag_size=0的话是说bag里所有instance都用，如果设定bag_size=x的话是说随机取bag里面x个instance，这样比较方便多gpu训练。

**Comment by sxtopc** [comment]
@gaotianyu1350 你好，按照这个意思的话。
设定bag_size=1,2,0分别对应论文中的从包中随机抽取one，two，all的instance做测试对吧。
另论文中precision@N的验证指标对接项目中的哪一部份呢

**Comment by gaotianyu1350** [comment]
现在我们一般直接用auc来评价，如果需要precision@N的话，可以用BagREDataset中eval函数返回的micro_p字段
