### ISSUE TITLE
AttributeError: 'module' object has no attribute 'rnn_cell'

### ISSUE THREAD

**Issue by PeterXUYAOHAI** [thunlp/OpenNRE#3]
Hi!  Thanks for sharing the code
When I try to run the code `python train_GPU.py`
I met

> Traceback (most recent call last):
>   File "train_GRU.py", line 243, in <module>
>     tf.app.run() 
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
>     _sys.exit(main(_sys.argv[:1] + flags_passthrough))
>   File "train_GRU.py", line 159, in main
>     m = GRU(is_training=True, word_embeddings = wordembedding, settings = settings)
>   File "train_GRU.py", line 49, in __init__
>     gru_cell_forward = tf.nn.rnn_cell.GRUCell(gru_size)
> AttributeError: 'module' object has no attribute 'rnn_cell'

my tensorflow verison is 
```
>>> print(tf.__version__)
1.0.0-rc1
```

I was wondering which tensor flow version is used in your code?

Thanks!

**Comment by crownpku** [comment]
I guess You may try tf r0.11.
If you use r1.0, tensorflow API, you have to change the code to be tf.contrib.rnn.GRUCell
You can refer to tensorflow website at https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/GRUCell

**Comment by Tsingularity** [comment]
The tf version I'm using is r0.11.0.

**Comment by PeterXUYAOHAI** [comment]
Thanks！ after change some part of the code to r1.0, this error was solved.

**Comment by Luckynmc** [comment]
I am a new student .I do not know where i need to change about code?? please help me . Thank you

**Comment by anonymous31173** [comment]
As per the latest version use this " tf.contrib.rnn import core_rnn_cell"
