### ISSUE TITLE
nyt10 中提供的数据链接有问题？

### ISSUE THREAD

**Issue by WinterSoHot** [thunlp/OpenNRE#302]
你好，我用了nyt10里面的连接下载了数据集，发现其中val和test集是完全一样的。另外数据集的样本数量和我在网络中查询到的并不一致。

**Comment by gaotianyu1350** [comment]
您好，“网络中查询到的”是指什么出处呢？

关于val集：原始的nyt10数据集只有训练集和测试集，这里验证集只是一个占位符。
