### ISSUE TITLE
Poor performance when using Bert in BagRE

### ISSUE THREAD

**Issue by LorrinWWW** [thunlp/OpenNRE#303]
I have been trying to use bert encoder in bag-level relation extraction (NYT10), however, the performance is constantly poor (i.e., auc < 0.01 and f1 < 0.1).

In my experience, the PCNN based bag-level RE model's auc can reach 0.32+ after 30th epoch, which looks correct to me; when switching to sentence-level RE, the bert-based model's f1 reached 0.37+ after the first epoch, which also looks correct to me. But when using Bert and BagRE together, the performance becomes unusually bad. 

Any idea about the cause? Have anyone try BERT on bag-level RE? Thanks in advance!

(Part of) my code for bag-level training.
```python
sentence_encoder = BERTEntityEncoder(
    max_length=args.max_length, 
    pretrain_path='bert-base-uncased',
    mask_entity=args.mask_entity,
)

model = BagAttention(sentence_encoder, len(rel2id), rel2id)

framework = BagRE(
    train_path=args.train_file,
    val_path=args.val_file,
    test_path=args.test_file,
    model=model,
    ckpt=ckpt,
    batch_size=args.batch_size,
    max_epoch=args.max_epoch,
    lr=args.lr,
    weight_decay=args.weight_decay,
    opt=args.optim,
    bag_size=args.bag_size,
)

framework.train_model(metric='auc')
```

Hyper-parameters that have been tried: 
dataset='nyt10', lr=[2e-3, 2e-4, 2e-5], batch_size=[20, 32], bag_size=[5, 10], optim='adamw', mask_entity=[False, True], max_length=120, max_epoch=10

**Comment by LorrinWWW** [comment]
Look like it's due to the order of arguments.. Please check:
https://github.com/thunlp/OpenNRE/blob/c40c680f65df6b9f20080023cf41402232e42625/opennre/model/bag_attention.py#L46
https://github.com/thunlp/OpenNRE/blob/c40c680f65df6b9f20080023cf41402232e42625/opennre/encoder/bert_encoder.py#L208
and
https://github.com/thunlp/OpenNRE/blob/c40c680f65df6b9f20080023cf41402232e42625/opennre/model/bag_attention.py#L90
https://github.com/thunlp/OpenNRE/blob/c40c680f65df6b9f20080023cf41402232e42625/opennre/encoder/bert_encoder.py#L116

**Comment by gaotianyu1350** [comment]
Hi,

Thanks for pointing this out! We just add some comments in `model/bag_attention.py` that this is a "dirty hack": the order of the names are wrong for BERT encoders, but it should still be able to work. We have also added the example code for running BERT-bag-level models in the `example` folder. Note that we also found that ATT does not work well for BERT, and simply training BERT models on distant datasets with sent-level training can achieve good performance.

**Comment by GanjinZero** [comment]
I try BERT + attention with my own biomedical dataset.
I found that reducing bag size will increase the performance.
bag 16: auc 0.035;
bag 8: auc 0.16;
bag 4: auc 0.513;
bag 2: auc 0.772;
bag 1: auc 0.832.
I doubt that the implementation of attention for Bert model is correct.
