### ISSUE TITLE
Missing Key(s) in state dict:"sentence_encoder.bert.embeddings.position_ids"

### ISSUE THREAD

**Issue by wanlipeng** [thunlp/OpenNRE#304]
你好,我按照git网址下载预训练模型" wiki80_bert_softmax" 去测试时出现这个问题,应该是模型和网络结构不对应吧,有遇到这个问题的吗,求教!

**Comment by gaotianyu1350** [comment]
您好，这个bug是由于huggingface更新了transformers库的接口造成的，现在我们已经更新了模型，可以重新下载一下试试（需要清理掉`$HOME/.opennre/pretrain/nre`下的缓存。

**Comment by wanlipeng** [comment]
刚重新下载wiki80_bert_softmax.pth.tar模型,升级了下pytorch版本到1.60,报错"UnexpectedKey(s) in state dict:"sentence_encoder.bert.embeddings.position_ids"这个错误,不过这次上面提示 Didn't find file /berse-base-uncased/added_token.json, special_tokens_map.json, tokenizer_config.json, tokenizer.json这几个在哪可以下载到呢,,再求指导下,(这边服务器不能上网是离线下载的模型测试的) @ gaotianyu1350

**Comment by gaotianyu1350** [comment]
能否提示下完整的报错信息？

**Comment by wanlipeng** [comment]
这边没法截图,方便留个邮箱,,我回去邮件发下?

**Comment by gaotianyu1350** [comment]
gaotianyu1350@126.com

**Comment by CeruleanW** [comment]
你好 我遇到了完全相同的问题。重新下载wiki80_bert_softmax.pth.tar 后还是报错。请问这个问题解决了吗？
