### ISSUE TITLE
certificate issue

### ISSUE THREAD

**Issue by wangxinyi-gsafety** [thunlp/OpenNRE#305]
你好，我今天在用opennre时报如下证书错误，请问如何解决，谢谢。

>>> model = opennre.get_model('wiki80_bert_softmax')
SYSTEM_WGETRC = c:/progra~1/wget/etc/wgetrc
syswgetrc = C:\Program Files (x86)\GnuWin32/etc/wgetrc
--2020-12-01 13:03:59--  https://thunlp.oss-cn-qingdao.aliyuncs.com/opennre/pretrain/nre/wiki80_bert_softmax.pth.tar
正在解析主机 thunlp.oss-cn-qingdao.aliyuncs.com... 119.167.128.167
Connecting to thunlp.oss-cn-qingdao.aliyuncs.com|119.167.128.167|:443... 已连接。
ERROR: cannot verify thunlp.oss-cn-qingdao.aliyuncs.com's certificate, issued by `/C=BE/O=GlobalSign nv-sa/CN=GlobalSign Organization Validation CA - SHA256 - G2':
  Unable to locally verify the issuer's authority.
ERROR: certificate common name `*.oss-cn-beijing.aliyuncs.com' doesn't match requested host name `thunlp.oss-cn-qingdao.aliyuncs.com'.
To connect to thunlp.oss-cn-qingdao.aliyuncs.com insecurely, use `--no-check-certificate'.

**Comment by gaotianyu1350** [comment]
这似乎是windows下wget的问题，我这边测试是好的。你可以尝试直接用这个链接手动下载一下模型
