### ISSUE TITLE
如何应用到中文上？

### ISSUE THREAD

**Issue by leolle** [thunlp/OpenNRE#31]
谢谢你们的工作。
我想把它应用到中文上，该怎么做？需要准确哪些东西？

**Comment by THUCSTHanxu13** [comment]
把数据按照我们的数据格式输入就可以了

**Comment by THUCSTHanxu13** [comment]
还需要一个相应的中文词向量来驱动神经网络进行编码

**Comment by THUCSTHanxu13** [comment]
没有什么需要修改的

**Comment by ufo5** [comment]
能够得到您迅速的回复真的感激不尽，有些技术细节想向您请教，方便私信您吗？QQ：84752220

**Comment by Jasperty** [comment]
应用到中文，需要重新训练吗？

**Comment by gaotianyu1350** [comment]
我们目前没有提供中文的预训练模型，所以是的，需要在自己的语料上进行重新训练
