### ISSUE TITLE
Can i only give token or text in the param when i want to infer a new sentence?

### ISSUE THREAD

**Issue by zsStrike** [thunlp/OpenNRE#314]
When infer the relation, can i just give the following param?
```
{
    text: "some text"
}
```
Must the `h` and `t` fileds be provided?

**Comment by imohitmayank** [comment]
It seems the `h` and `t` are the entities between which we want the relation to be found. As this package doesn't contain NER (named entity recognition) module, we will have to run that module as a pre-process step and use it's output here.

**Comment by zsStrike** [comment]
Ok, thanks a lot :)
