### ISSUE TITLE
Torch size issue

### ISSUE THREAD

**Issue by nick8408** [thunlp/OpenNRE#315]
File "/home/user/Desktop/NRE/nre/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1044, in load_state_dict     
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format( RuntimeError: Error(s) in loading state_dict for SoftmaxNN: 	size mismatch for sentence_encoder.pos1_embedding.weight: copying a param with shape torch.Size([160, 5]) from checkpoint, the shape in current model is torch.Size([256, 5]).

how can I change this size issue. 
Thank you for your kind help

**Comment by gaotianyu1350** [comment]
Hi,

You can change the `max_length` argument to match the size of position embeddings.
