### ISSUE TITLE
使用中文数据集和预训练词向量导致cuda out of memory

### ISSUE THREAD

**Issue by gertrude95** [thunlp/OpenNRE#318]
您好，高博！
初学者问题可能有些浅薄，请见谅~
1）我使用自己的中文数据集（1500w个句子）以及预训练词向量（134w×300），训练PCNN-attention模型，出现CUDA out of memory的问题，想问一下如何设置可以避免这个问题
2）其次是关于多GPU计算的问题，想了解一下bag_size这一参数该如何设置，他的大小决定我使用的GPU的卡数吗？我该如何指定某n个GPU进行训练呢？

**Comment by gaotianyu1350** [comment]
你好，

(1) cuda out of memory的问题，可以通过使用更小的batch size解决。

(2) bag_size和GPU个数没有关系，其指的是对于每个bag要sample多少个样本，0的话表示使用全部样本。
