### ISSUE TITLE
raise信息错误

### ISSUE THREAD

**Issue by 131441373** [thunlp/OpenNRE#320]
opennre/model/base_model里的FewShotRE的infer函数没有写raise NotImplementedError

**Comment by 131441373** [comment]
另一个:
opennre/tokenization/utils.py里的147~148行
```
def load_vocab(vocab_file):
    """Loads a vocabulary file into a dictionary."""
    if vocab_file ==  None:
        raise ValueError("Unsupported string type: %s" % (type(text)))
```
复制了别的地方的raise error但是这行实际会引发text undefine的问题而不是抛出异常

**Comment by gaotianyu1350** [comment]
Hi,

Thanks for the reminder. We have fixed these issues.
