### ISSUE TITLE
convert_ids_to_tokens运行报错

### ISSUE THREAD

**Issue by 131441373** [thunlp/OpenNRE#321]
opennre/tokenization/utils.py里的convert_by_vocab同时被
convert_ids_to_tokens和convert_tokens_to_ids引用
其中
```
    for item in items:
        if uncased:
            item = item.lower() 
```
对于ids->tokens时不存在lower(), 报错
可以在if语句加上hasattr判断 或者 在ids_to_tokens调用convert_by_vocab时设置uncased=false

**Comment by gaotianyu1350** [comment]
Hi,

Thanks for the reminder! The bug has been fixed.
