### ISSUE TITLE
wiki80_bert_softmax expects a tensor input

### ISSUE THREAD

**Issue by tomasonjo** [thunlp/OpenNRE#323]
I am trying to run the pretrained wiki80 bert model.

My code is as follows:

```
relation_model = opennre.get_model('wiki80_bert_softmax')
model.infer({'text': 'He was the son of Máel Dúin mac Máele Fithrich, and grandson of the high king Áed Uaridnach (died 612).', 'h': {'pos': (18, 46)}, 't': {'pos': (78, 91)}})
```

I get the following error:

> Traceback (most recent call last):
>   File "main.py", line 83, in <module>
>     data = relation_model.infer({'text': sentence, 'h': {'pos': source}, 't': {'pos': target}})
>   File "/home/tomaz/neo4j/OpenNRE/opennre/model/softmax_nn.py", line 31, in infer
>     logits = self.forward(*item)
>   File "/home/tomaz/neo4j/OpenNRE/opennre/model/softmax_nn.py", line 46, in forward
>     rep = self.drop(rep)
>   File "/home/tomaz/anaconda3/envs/nlp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/tomaz/anaconda3/envs/nlp/lib/python3.7/site-packages/torch/nn/modules/dropout.py", line 58, in forward
>     return F.dropout(input, self.p, self.training, self.inplace)
>   File "/home/tomaz/anaconda3/envs/nlp/lib/python3.7/site-packages/torch/nn/functional.py", line 973, in dropout
>     else _VF.dropout(input, p, training))
> TypeError: dropout(): argument 'input' (position 1) must be Tensor, not str

What am I missing?

**Comment by tomasonjo** [comment]
need to update transformers to 3.5.1

**Comment by christelle-git** [comment]
@tomasonjo are you planning to upgrade to transformers >= 4.1 ?
I use Allen NLP which needs transformers 4.1, and the output is piped to OpenNre (I get the same error as you), and it could be nice to keep it in one environment/script.
