### ISSUE TITLE
Format of train data

### ISSUE THREAD

**Issue by iden-alex** [thunlp/OpenNRE#327]
I want to train model on my dataset. What format should the training data be in?

**Comment by gaotianyu1350** [comment]
Hi,

You can format your data as a txt file, and each line contains one data point. Each data point should be formatted as a json string, for example: 

```
"token": ["Death", "To", "Spies", ":", "Moment", "Of", "Truth", "(", ")", "is", "a", "third", "-", "person", "stealth", "action", "PC", "game", "set", "during", "World", "War", "II", "."], "h": {"name": "death to spies", "id": "Q13165", "pos": [0, 3]}, "t": {"name": "world war ii", "id": "Q362", "pos": [20, 23]}, "relation": "main subject"}
```

You should also provide a json file that maps relation names ("main subject" here) to IDs (from 0 to #relation - 1).

You can download datasets in the benchmark folder and take them as a reference.
