### ISSUE TITLE
Using wiki80_bertentity_softmax

### ISSUE THREAD

**Issue by igormis** [thunlp/OpenNRE#330]
I really liked the project, though I have difficulties to infer using wiki80_bertentity_softmax. I am not sure how to concatenate extracted entities as an input to the infer method.

**Comment by joelawalsh01** [comment]
do a wget command and paste in the directory of the file: 

wget -P ner https://thunlp.oss-cn-qingdao.aliyuncs.com/opennre/pretrain/nre/wiki80_bertentity_softmax.pth.tar

**Comment by igormis** [comment]
Tnx @joelawalsh01 the question was more about how should the input looks? For instance, I have extracted entities:
`Bill Gates (Person) is the founder of Microsoft (Company). `
The question is how to this information as an input to the infer method (using the wiki80_bertentity_softmax)?
Also how to infer/train dataset with multiple entities and one relation, for instance:
` Larry Page and Sergey Brin  are the founders of Google. (the RE should work for both persons) `
or 
`Elon Mush is the founder of Tesla, SpaceX and OpenAI. (the RE should work for all companies and one person)`

**Comment by joelawalsh01** [comment]
Oh good question on the multiple. I've been using allen core nlp NER to get individual entities, then copying the sentence and iterating through each possible h,t pair to get the relation. I'm sure the authors have a much more efficient way though.

**Comment by gaotianyu1350** [comment]
Hi,

Current models in OpenNRE are trained for relation extraction of single entity pairs. If you have multiple entities, one way to do relation extraction is to enumerate all combinations of entities and do multiple times of inference (as @joelawalsh01 suggested).
