### ISSUE TITLE
Issues in executing `model = opennre.get_model('wiki80_cnn_softmax')`

### ISSUE THREAD

**Issue by raphael10-collab** [thunlp/OpenNRE#336]
(pytorch_env) raphy@pc:~/OpenNRE$ python3
    Python 3.9.4 (default, Apr  9 2021, 16:34:09) 
    [GCC 7.3.0] :: Anaconda, Inc. on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import opennre
    >>> model = opennre.get_model('wiki80_cnn_softmax')
    --2021-06-03 09:43:24--  https://thunlp.oss-cn-qingdao.aliyuncs.com/opennre/pretrain/nre/wiki80_cnn_softmax.pth.tar
    Resolving thunlp.oss-cn-qingdao.aliyuncs.com (thunlp.oss-cn-qingdao.aliyuncs.com)... 47.104.38.189
    Connecting to thunlp.oss-cn-qingdao.aliyuncs.com (thunlp.oss-cn-qingdao.aliyuncs.com)|47.104.38.189|:443... connected.
    ERROR: cannot verify thunlp.oss-cn-qingdao.aliyuncs.com's certificate, issued by ‘CN=GlobalSign Organization Validation CA - SHA256 - G2,O=GlobalSign nv-sa,C=BE’:
      Unable to locally verify the issuer's authority.
    To connect to thunlp.oss-cn-qingdao.aliyuncs.com insecurely, use `--no-check-certificate'.
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/raphy/OpenNRE/opennre/pretrain.py", line 133, in get_model
        wordi2d = json.load(open(os.path.join(root_path, 'pretrain/glove/glove.6B.50d_word2id.json')))
    FileNotFoundError: [Errno 2] No such file or directory: '/home/raphy/.opennre/pretrain/glove/glove.6B.50d_word2id.json'
 
The required packages are already installed: 

    (pytorch_env) raphy@pc:~/OpenNRE$ cat requirements.txt 
    torch==1.6.0
    transformers==3.4.0
    pytest==5.3.2
    scikit-learn==0.22.1
    scipy==1.4.1
    nltk==3.4.5
    (pytorch_env) raphy@pc:~/OpenNRE$ pip3 install torch
    Requirement already satisfied: torch in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (1.8.1+cpu)
    Requirement already satisfied: typing-extensions in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from torch) (3.7.4.3)
    Requirement already satisfied: numpy in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from torch) (1.20.1)
    (pytorch_env) raphy@pc:~/OpenNRE$ pip3 install transformers
    Requirement already satisfied: transformers in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (4.6.1)
    Requirement already satisfied: tqdm>=4.27 in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from transformers) (4.59.0)
    Requirement already satisfied: requests in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from transformers) (2.25.1)
    Requirement already satisfied: regex!=2019.12.17 in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from transformers) (2021.4.4)
    Requirement already satisfied: huggingface-hub==0.0.8 in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from transformers) (0.0.8)
    Requirement already satisfied: packaging in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from transformers) (20.9)
    Requirement already satisfied: tokenizers<0.11,>=0.10.1 in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from transformers) (0.10.3)
    Requirement already satisfied: numpy>=1.17 in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from transformers) (1.20.1)
    Requirement already satisfied: filelock in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from transformers) (3.0.12)
    Requirement already satisfied: sacremoses in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from transformers) (0.0.45)
    Requirement already satisfied: pyparsing>=2.0.2 in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from packaging->transformers) (2.4.7)
    Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from requests->transformers) (1.26.4)
    Requirement already satisfied: certifi>=2017.4.17 in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from requests->transformers) (2020.12.5)
    Requirement already satisfied: idna<3,>=2.5 in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from requests->transformers) (2.10)
    Requirement already satisfied: chardet<5,>=3.0.2 in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from requests->transformers) (4.0.0)
    Requirement already satisfied: click in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from sacremoses->transformers) (7.1.2)
    Requirement already satisfied: joblib in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from sacremoses->transformers) (1.0.1)
    Requirement already satisfied: six in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from sacremoses->transformers) (1.15.0)
    (pytorch_env) raphy@pc:~/OpenNRE$ pip3 install pytest
    Requirement already satisfied: pytest in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (6.2.3)
    Requirement already satisfied: attrs>=19.2.0 in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from pytest) (20.3.0)
    Requirement already satisfied: iniconfig in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from pytest) (1.1.1)
    Requirement already satisfied: packaging in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from pytest) (20.9)
    Requirement already satisfied: pluggy<1.0.0a1,>=0.12 in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from pytest) (0.13.1)
    Requirement already satisfied: py>=1.8.2 in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from pytest) (1.10.0)
    Requirement already satisfied: toml in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from pytest) (0.10.2)
    Requirement already satisfied: pyparsing>=2.0.2 in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from packaging->pytest) (2.4.7)
    (pytorch_env) raphy@pc:~/OpenNRE$ pip3 install scikit-learn
    Requirement already satisfied: scikit-learn in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (0.24.1)
    Requirement already satisfied: numpy>=1.13.3 in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from scikit-learn) (1.20.1)
    Requirement already satisfied: scipy>=0.19.1 in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from scikit-learn) (1.6.2)
    Requirement already satisfied: threadpoolctl>=2.0.0 in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from scikit-learn) (2.1.0)
    Requirement already satisfied: joblib>=0.11 in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from scikit-learn) (1.0.1)
    (pytorch_env) raphy@pc:~/OpenNRE$ pip3 install scipy
    Requirement already satisfied: scipy in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (1.6.2)
    Requirement already satisfied: numpy<1.23.0,>=1.16.5 in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from scipy) (1.20.1)
    (pytorch_env) raphy@pc:~/OpenNRE$ pip3 install nltk
    Requirement already satisfied: nltk in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (3.6.1)
    Requirement already satisfied: tqdm in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from nltk) (4.59.0)
    Requirement already satisfied: click in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from nltk) (7.1.2)
    Requirement already satisfied: joblib in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from nltk) (1.0.1)
    Requirement already satisfied: regex in /home/raphy/anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from nltk) (2021.4.4)
    (pytorch_env) raphy@pc:~/OpenNRE$ 

O.S.: Ubuntu 20.04 Desktop
python: 3.9.4

How to solve the problem?

**Comment by subssn21** [comment]
I had the same issue, If you originally failed to download all the required files the first time you ran the code, The directories would get created, but the files didn't download and the code will not rerun if it sees the directories.

rm -rf ~/.opennre/pretrain/glove
rm -rf ~/.opennre/benchmark/wiki80

Then the downloads should work

Actual fix would be to check the files exist in pretrain.py instead of just the directories

**Comment by raphael10-collab** [comment]
I tried again, but still have problems... :  

    (base) raphy@pc:~$ git clone https://github.com/thunlp/OpenNRE.git
    Cloning into 'OpenNRE'...
    remote: Enumerating objects: 1501, done.
    remote: Counting objects: 100% (124/124), done.
    remote: Compressing objects: 100% (85/85), done.
    remote: Total 1501 (delta 72), reused 75 (delta 39), pack-reused 1377
    Receiving objects: 100% (1501/1501), 266.83 MiB | 27.41 MiB/s, done.
    Resolving deltas: 100% (892/892), done.
    (base) raphy@pc:~$ cd OpenNRE/
    (base) raphy@pc:~/OpenNRE$ pip3 install -r requirements.txt 
    (base) raphy@pc:~/OpenNRE$ pip3 install -r requirements.txt
    Collecting torch==1.6.0
      WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/8c/5d/faf0d8ac260c7f1eda7d063001c137da5223be1c137658384d2d45dcd0d5/torch-1.6.0-cp38-cp38-manylinux1_x86_64.whl
      WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/8c/5d/faf0d8ac260c7f1eda7d063001c137da5223be1c137658384d2d45dcd0d5/torch-1.6.0-cp38-cp38-manylinux1_x86_64.whl
      Downloading torch-1.6.0-cp38-cp38-manylinux1_x86_64.whl (748.8 MB)
         |████████████████████████████████| 748.8 MB 39 kB/s 
    Collecting transformers==3.4.0
      Downloading transformers-3.4.0-py3-none-any.whl (1.3 MB)
         |████████████████████████████████| 1.3 MB 39.8 MB/s 
    Collecting pytest==5.3.2
      Downloading pytest-5.3.2-py3-none-any.whl (234 kB)
         |████████████████████████████████| 234 kB 97.6 MB/s 
    Collecting scikit-learn==0.22.1
      Downloading scikit_learn-0.22.1-cp38-cp38-manylinux1_x86_64.whl (7.0 MB)
         |████████████████████████████████| 7.0 MB 26.9 MB/s 
    Collecting scipy==1.4.1
      Downloading scipy-1.4.1-cp38-cp38-manylinux1_x86_64.whl (26.0 MB)
         |████████████████████████████████| 26.0 MB 81.6 MB/s 
    Collecting nltk==3.4.5
      Downloading nltk-3.4.5.zip (1.5 MB)
         |████████████████████████████████| 1.5 MB 77.0 MB/s 
    Requirement already satisfied: six in /home/raphy/anaconda3/lib/python3.8/site-packages (from nltk==3.4.5->-r requirements.txt (line 6)) (1.15.0)
    Requirement already satisfied: wcwidth in /home/raphy/anaconda3/lib/python3.8/site-packages (from pytest==5.3.2->-r requirements.txt (line 3)) (0.2.5)
    Requirement already satisfied: packaging in /home/raphy/anaconda3/lib/python3.8/site-packages (from pytest==5.3.2->-r requirements.txt (line 3)) (20.9)
    Requirement already satisfied: pluggy<1.0,>=0.12 in /home/raphy/anaconda3/lib/python3.8/site-packages (from pytest==5.3.2->-r requirements.txt (line 3)) (0.13.1)
    Requirement already satisfied: more-itertools>=4.0.0 in /home/raphy/anaconda3/lib/python3.8/site-packages (from pytest==5.3.2->-r requirements.txt (line 3)) (8.7.0)
    Requirement already satisfied: attrs>=17.4.0 in /home/raphy/anaconda3/lib/python3.8/site-packages (from pytest==5.3.2->-r requirements.txt (line 3)) (20.3.0)
    Requirement already satisfied: py>=1.5.0 in /home/raphy/anaconda3/lib/python3.8/site-packages (from pytest==5.3.2->-r requirements.txt (line 3)) (1.10.0)
    Requirement already satisfied: numpy>=1.11.0 in /home/raphy/anaconda3/lib/python3.8/site-packages (from scikit-learn==0.22.1->-r requirements.txt (line 4)) (1.20.1)
    Requirement already satisfied: joblib>=0.11 in /home/raphy/anaconda3/lib/python3.8/site-packages (from scikit-learn==0.22.1->-r requirements.txt (line 4)) (1.0.1)
    Requirement already satisfied: future in /home/raphy/anaconda3/lib/python3.8/site-packages (from torch==1.6.0->-r requirements.txt (line 1)) (0.18.2)
    Requirement already satisfied: regex!=2019.12.17 in /home/raphy/anaconda3/lib/python3.8/site-packages (from transformers==3.4.0->-r requirements.txt (line 2)) (2021.4.4)
    Collecting tokenizers==0.9.2
      Downloading tokenizers-0.9.2-cp38-cp38-manylinux1_x86_64.whl (2.9 MB)
         |████████████████████████████████| 2.9 MB 46.6 MB/s 
    Requirement already satisfied: tqdm>=4.27 in /home/raphy/anaconda3/lib/python3.8/site-packages (from transformers==3.4.0->-r requirements.txt (line 2)) (4.59.0)
    Requirement already satisfied: sentencepiece!=0.1.92 in /home/raphy/anaconda3/lib/python3.8/site-packages (from transformers==3.4.0->-r requirements.txt (line 2)) (0.1.91)
    Requirement already satisfied: requests in /home/raphy/anaconda3/lib/python3.8/site-packages (from transformers==3.4.0->-r requirements.txt (line 2)) (2.25.1)
    Requirement already satisfied: protobuf in /home/raphy/anaconda3/lib/python3.8/site-packages (from transformers==3.4.0->-r requirements.txt (line 2)) (3.17.3)
    Requirement already satisfied: sacremoses in /home/raphy/anaconda3/lib/python3.8/site-packages (from transformers==3.4.0->-r requirements.txt (line 2)) (0.0.45)
    Requirement already satisfied: filelock in /home/raphy/.local/lib/python3.8/site-packages (from transformers==3.4.0->-r requirements.txt (line 2)) (3.0.12)
    Requirement already satisfied: pyparsing>=2.0.2 in /home/raphy/anaconda3/lib/python3.8/site-packages (from packaging->pytest==5.3.2->-r requirements.txt (line 3)) (2.4.7)
    Requirement already satisfied: chardet<5,>=3.0.2 in /home/raphy/anaconda3/lib/python3.8/site-packages (from requests->transformers==3.4.0->-r requirements.txt (line 2)) (4.0.0)
    Requirement already satisfied: idna<3,>=2.5 in /home/raphy/anaconda3/lib/python3.8/site-packages (from requests->transformers==3.4.0->-r requirements.txt (line 2)) (2.10)
    Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/raphy/anaconda3/lib/python3.8/site-packages (from requests->transformers==3.4.0->-r requirements.txt (line 2)) (1.26.4)
    Requirement already satisfied: certifi>=2017.4.17 in /home/raphy/anaconda3/lib/python3.8/site-packages (from requests->transformers==3.4.0->-r requirements.txt (line 2)) (2020.12.5)
    Requirement already satisfied: click in /home/raphy/anaconda3/lib/python3.8/site-packages (from sacremoses->transformers==3.4.0->-r requirements.txt (line 2)) (7.1.2)
    Building wheels for collected packages: nltk
      Building wheel for nltk (setup.py) ... done
      Created wheel for nltk: filename=nltk-3.4.5-py3-none-any.whl size=1449906 sha256=a57a3ea80348b78e285c1362a3af3f1e58a1fe0ba6dd975df5c4c9ebf11dbc75
      Stored in directory: /home/raphy/.cache/pip/wheels/23/18/48/8fd6ec11da38406b309470566d6f099c04805d2ec61d7829e7
    Successfully built nltk
    Installing collected packages: tokenizers, scipy, transformers, torch, scikit-learn, pytest, nltk
      Attempting uninstall: tokenizers
        Found existing installation: tokenizers 0.10.3
        Uninstalling tokenizers-0.10.3:
          Successfully uninstalled tokenizers-0.10.3
      Attempting uninstall: scipy
        Found existing installation: scipy 1.6.2
        Uninstalling scipy-1.6.2:
          Successfully uninstalled scipy-1.6.2
      Attempting uninstall: transformers
        Found existing installation: transformers 4.8.2
        Uninstalling transformers-4.8.2:
          Successfully uninstalled transformers-4.8.2
      Attempting uninstall: torch
        Found existing installation: torch 1.9.0+cpu
        Uninstalling torch-1.9.0+cpu:
          Successfully uninstalled torch-1.9.0+cpu
      Attempting uninstall: scikit-learn
        Found existing installation: scikit-learn 0.24.1
        Uninstalling scikit-learn-0.24.1:
          Successfully uninstalled scikit-learn-0.24.1
      Attempting uninstall: pytest
        Found existing installation: pytest 6.2.3
        Uninstalling pytest-6.2.3:
          Successfully uninstalled pytest-6.2.3
      Attempting uninstall: nltk
        Found existing installation: nltk 3.6.1
        Uninstalling nltk-3.6.1:
          Successfully uninstalled nltk-3.6.1
    ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
    torchvision 0.10.0+cpu requires torch==1.9.0, but you have torch 1.6.0 which is incompatible.
    torchaudio 0.9.0 requires torch==1.9.0, but you have torch 1.6.0 which is incompatible.
    Successfully installed nltk-3.4.5 pytest-5.3.2 scikit-learn-0.22.1 scipy-1.4.1 tokenizers-0.9.2 torch-1.6.0 transformers-3.4.0
    (base) raphy@pc:~/OpenNRE$ python3
    Python 3.8.8 (default, Apr 13 2021, 19:58:26) 
    [GCC 7.3.0] :: Anaconda, Inc. on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import opennre
    >>> model = opennre.get_model('wiki80_cnn_softmax')
    --2021-07-15 10:20:00--  https://thunlp.oss-cn-qingdao.aliyuncs.com/opennre/pretrain/nre/wiki80_cnn_softmax.pth.tar
    Resolving thunlp.oss-cn-qingdao.aliyuncs.com (thunlp.oss-cn-qingdao.aliyuncs.com)... 47.104.38.189
    Connecting to thunlp.oss-cn-qingdao.aliyuncs.com (thunlp.oss-cn-qingdao.aliyuncs.com)|47.104.38.189|:443... connected.
    ERROR: cannot verify thunlp.oss-cn-qingdao.aliyuncs.com's certificate, issued by ‘CN=GlobalSign Organization Validation CA - SHA256 - G2,O=GlobalSign nv-sa,C=BE’:
      Unable to locally verify the issuer's authority.
    To connect to thunlp.oss-cn-qingdao.aliyuncs.com insecurely, use `--no-check-certificate'.
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/raphy/OpenNRE/opennre/pretrain.py", line 133, in get_model
        wordi2d = json.load(open(os.path.join(root_path, 'pretrain/glove/glove.6B.50d_word2id.json')))
    FileNotFoundError: [Errno 2] No such file or directory: '/home/raphy/.opennre/pretrain/glove/glove.6B.50d_word2id.json'
    >>>

**Comment by Kkkassini** [comment]
same error. This issue seems not difficult to resolve but it appears so many times in the issuelist.

**Comment by raphael10-collab** [comment]
I tried again from scratch and I do not understand why it doesn't find the pretrained model:

    (base) raphy@pc:~$ find -name glove.6B.50d_word2id.json
    ./OpenNRE/pretrain/glove/glove.6B.50d_word2id.json

    (base) raphy@pc:~$ python3
    Python 3.8.8 (default, Apr 13 2021, 19:58:26) 
    [GCC 7.3.0] :: Anaconda, Inc. on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import opennre
    >>> model = opennre.get_model('wiki80_cnn_softmax')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/raphy/anaconda3/lib/python3.8/site-packages/opennre-0.1-py3.8.egg/opennre/pretrain.py", line 133, in get_model
    FileNotFoundError: [Errno 2] No such file or directory: '/home/raphy/.opennre/pretrain/glove/glove.6B.50d_word2id.json'
    >>>

**Comment by raphael10-collab** [comment]
Solved:

I moved the files downloaded by the scripts in 

    (base) raphy@pc:~/OpenNRE/benchmark$ ls -lah
    total 36K
    drwxrwxr-x  3 raphy raphy 4,0K lug 28 14:39 .
    drwxrwxr-x 11 raphy raphy 4,0K lug 28 14:38 ..
    -rwxrwxr-x  1 raphy raphy  425 lug 28 14:38 download_fewrel.sh
    -rwxrwxr-x  1 raphy raphy  412 lug 28 14:38 download_nyt10m.sh
    -rwxrwxr-x  1 raphy raphy  304 lug 28 14:38 download_nyt10.sh
    -rwxrwxr-x  1 raphy raphy  425 lug 28 14:38 download_semeval.sh
    -rwxrwxr-x  1 raphy raphy  425 lug 28 14:38 download_wiki20m.sh
    -rwxrwxr-x  1 raphy raphy  313 lug 28 14:38 download_wiki80.sh


    (base) raphy@pc:~/OpenNRE/pretrain/glove$ mv glove.6B.50d_* /home/raphy/.opennre/pretrain/glove/
    
    (base) raphy@pc:~$ mv ./OpenNRE/benchmark/wiki80/wiki80_rel2id.json /home/raphy/.opennre/benchmark/wiki80
    /wiki80_rel2id.json

    (base) raphy@pc:~$ python3
    Python 3.8.8 (default, Apr 13 2021, 19:58:26) 
    [GCC 7.3.0] :: Anaconda, Inc. on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import opennre
    >>> model = opennre.get_model('wiki80_cnn_softmax')
    2021-07-28 15:31:31,257 - root - INFO - Initializing word embedding with word2vec.
    >>> model.infer({'text': 'He was the son of Máel Dúin mac Máele Fithrich, and grandson of the high king Áed Uaridnach (died 612).', 'h': {'pos': (18, 46)}, 't': {'pos': (78, 91)}})
    ('father', 0.7500484585762024)
    >>>
