### ISSUE TITLE
Chinese datasets 

### ISSUE THREAD

**Issue by ValarMorghulis2018** [thunlp/OpenNRE#337]
Do you have open source datasets in Chinese？

**Comment by monkdou0** [comment]
Same question
this package can not process chinese,right?

**Comment by THUCSTHanxu13** [comment]
The toolkit is language-independent. If you provide Chinese vocabulary and Chinese word embeddings, you can run OpenNRE on Chinese dataset. For Chinese relation extraction, you can use the competition datasets organized by Baidu, such as https://aistudio.baidu.com/aistudio/competition/detail/31/0/introduction
