### ISSUE TITLE
Could you help me？

### ISSUE THREAD

**Issue by YolandaRay** [thunlp/OpenNRE#34]
Read the questions you ask ：https://github.com/yahoo/FEL/issues/11
I can't download the dataset(https://webscope.sandbox.yahoo.com/catalog.php?datatype=l&did=81),because i don't have Amazon WS Canonical User ID .could you send me the dataset？

thank u very much，

my email songconglei@163.com

**Comment by THUCSTHanxu13** [comment]
You can download the dataset from https://drive.google.com/file/d/1BnyXMJ71jM0kxyJUlXa5MHf-vNjE57i-/view?usp=sharing
