### ISSUE TITLE
cannot find adversarial training, reinforcement learning in **model** Module

### ISSUE THREAD

**Issue by RuiqingGao** [thunlp/OpenNRE#341]
hello!  In your paper, you mentioned that 

'''Some special algorithms for enhancing RE models are also included in the toolkit, such as attention mechanism (Lin et al., 2016), **adversarial training** (Wu et al., 2017), and **reinforcement learning** (Feng et al., 2018). '''

but I didn't find the two models (adversarial training, reinforcement learning)?

**Comment by THUCSTHanxu13** [comment]
These codes are in the "old" branch.
