### ISSUE TITLE
Questions regarding the Wiki20m dataset

### ISSUE THREAD

**Issue by mehrdad-naser-73** [thunlp/OpenNRE#342]
Hi! I have a few questions about the Wiki20m dataset, and I would really appreciate your response.
1- Are all 137986 sentences in the test set manually annotated?
2- Is this dataset constructed from Wikipedia articles? 
3- Why did you choose these 80 properties from Wikidata to construct this dataset? Did you have certain criteria that only these properties met?

Thanks!

**Comment by THUCSTHanxu13** [comment]
1. All non-NA sentences in the test set are manually annotated.
2. This dataset is constructed based on aligning Wikidata and Wikipedia.
3. We use the sentences in the dataset FewRel for evaluation, and then add extra NA sentences and distantly-supervised training examples. The sentences in FewRel belong to 80 relations.
