### ISSUE TITLE
请问bag-level，输入的数据集为了生成bag是否要顺序？

### ISSUE THREAD

**Issue by KennyNg-19** [thunlp/OpenNRE#346]
你好，根据注释，a bag contains instances sharing the same relation fact。 对应代码为
```
            for idx, item in enumerate(self.data):
                # Annotated test set
                if 'anno_relation_list' in item:
                    for r in item['anno_relation_list']:
                        fact = (item['h']['id'], item['t']['id'], r)
                        if r != 'NA':
                            self.facts[fact] = 1
                    assert entpair_as_bag
                    name = (item['h']['id'], item['t']['id'])
                else:
                    fact = (item['h']['id'], item['t']['id'], item['relation'])
                    if item['relation'] != 'NA':
                        self.facts[fact] = 1
                    if entpair_as_bag:
                        name = (item['h']['id'], item['t']['id'])
                    else:
                        name = fact
                if name not in self.name2id:
                    self.name2id[name] = len(self.name2id)
                    self.bag_scope.append([])
                    self.bag_name.append(name)
                self.bag_scope[self.name2id[name]].append(idx)
```

是不是说 每组(item['h']['id'], item['t']['id'], item['relation'])都可以作为一个key，然后遍历整个data，每一个entity pair都找到对应(item['h']['id'], item['t']['id'], item['relation'])的bag。因此**不需要保证 输入数据集是把相同entity pair 连续地放在一起**？

因为我看Nyt10和其他**数据集都满足  把相同entity pair 连续放在一起**， 不知道这是不是一个硬性要求？
![image](https://user-images.githubusercontent.com/31399290/132851435-71c12341-3632-4967-8169-4b98be26187a.png)

2 entpair_as_bag 为true，是不是反而比为false时，限制更低了？因为bag name = (item['h']['id'], item['t']['id']) 比 (item['h']['id'], item['t']['id'], item['relation']) 少个relation的限制？而且**更推荐，entpair_as_bag为false 因为保证学习时，一个bag只有一个label**?

**Comment by THUCSTHanxu13** [comment]
输入数据不需要保证顺序，另外entpair_as_bag为false就是为了保证一个bag只有一个label，因为一个entity pair可能会有很多关系。

**Comment by naoki623** [comment]
感谢您的来信，我已成功收取。
