### ISSUE TITLE
nyt10m数据集

### ISSUE THREAD

**Issue by StarsEater** [thunlp/OpenNRE#347]
hello,请问有关于nyt10m数据集的详细介绍和各个模型在nyt10m的auc和P@N的分数吗

**Comment by THUCSTHanxu13** [comment]
数据下载可见https://github.com/thunlp/OpenNRE/blob/master/benchmark/download_nyt10m.sh。实验结果可见论文 Manual Evaluation Matters: Reviewing Test Protocols of Distantly Supervised Relation Extraction
