### ISSUE TITLE
How to prepare the dataset for training NER and Relations?

### ISSUE THREAD

**Issue by karndeepsingh** [thunlp/OpenNRE#349]
Hi,
I want to train the model on my own dataset. I have annotated the dataset with Entities and relations between them. But if I want to use OpenNer, in what formate the dataset should be prepared to feed into the model. Any guidance on this would be helpful.

Thanks

**Comment by tylinka** [comment]
You can use this command to download wiki80 dataset

```
python example/train_supervised_bert.py \
    --pretrain_path bert-base-uncased \
    --dataset wiki80
```

Then here _/OpenNRE/benchmark/wiki80_ you will find 3 files where you will see formats. You should prepare files like in this folder.
