### ISSUE TITLE
导入包后遇到一个问题

### ISSUE THREAD

**Issue by ssj-hub** [thunlp/OpenNRE#350]
![11a10fc40c0e84ad289caf7ee3d0bf7](https://user-images.githubusercontent.com/58419055/144433083-118f5354-fd28-4431-854e-1a7524a61f18.png)
只是import就出错了 还未调用
配置唯一改变的就是torch的版本 没有用1.6.0 但换了几个其他版本都返回相同的错误。

**Comment by QiaoZiqing** [comment]
This problem should have nothing to do with the version of torch,  it should be that the path of the opennre module is not available，please check line 12 of `opennre\pretrain.py`
> default_root_path = os.path.join('your_OpenNRE_path')

check is this path available.

**Comment by ssj-hub** [comment]
Thank you, the problem has been solved. It is indeed a path problem. Your suggestions have helped me a lot.
