### ISSUE TITLE
Mask entity parameter 

### ISSUE THREAD

**Issue by fillipefbr** [thunlp/OpenNRE#356]
Could someone please explain to me what are the practical effects of using the `mask_entity` parameter for supervised sentence-level relation extraction?

I mean, should I expect a better performance? I didn't find an explanation about this in the paper.

**Comment by THUCSTHanxu13** [comment]
The reason for masking entities is that we can keep the model from overfitting entity names. You can find more details on masking entities in our paper "Learning from Context or Names? An Empirical Study on Neural Relation Extraction".
