### ISSUE TITLE
Why did I get result that contains ‘acc', 'micro_p', 'micro_r' and 'micro_f1' all with the same value?

### ISSUE THREAD

**Issue by dr-GitHub-account** [thunlp/OpenNRE#359]
I trained a model that did Chinese NRE following [https://github.com/taorui-plus/OpenNRE](url) and it worked well in general.

However, when I tried to print result of each epoch by adding code `print("result for epoch {}: {}".format(epoch, result))` in the for loop, it seemed that every metric tended to give the same value, e.g., "result for epoch 0: {'acc': 0.902, 'micro_p': 0.902, 'micro_r': 0.902, 'micro_f1': 0.902}".

When I tried my hand at semeval, different metrics did give different values. It seems that no big change have been made in [https://github.com/taorui-plus/OpenNRE](url) compared to [https://github.com/thunlp/OpenNRE](url) except for the dataset.

**Comment by THUCSTHanxu13** [comment]
Maybe you can use some merging toolkits to compare these two codes, or check the measuring code on your data.
