### ISSUE TITLE
nyt10m数据集的疑问

### ISSUE THREAD

**Issue by Caesar-s1mple** [thunlp/OpenNRE#360]
我不理解为什么要把nyt10m数据集中一些relation的名字修改，比如
nyt10m的论文里写的、其他的所有nyt数据集都是 /people/deceased_person/place_of_death
而你们的nyt10m数据集却要将其改成/people/deceasedperson/place_of_death
我不理解作出这样的改动是为什么，这对我进行一些linking操作时带来一些本来不必要的困扰。

**Comment by THUCSTHanxu13** [comment]
我们会尽快确认下，然后更新一下
