### ISSUE TITLE
Please give me the file :'wiki80_cnn_softmax.pth.tar'

### ISSUE THREAD

**Issue by LDLINGLINGLING** [thunlp/OpenNRE#363]
Please give me the file :'wiki80_cnn_softmax.pth.tar',i can't get the file from the server。if you have the file,please send it to my email:403644786@qq.com,thank you very much.

**Comment by THUCSTHanxu13** [comment]
OK！

**Comment by gambastyle** [comment]
I need it to.. 
itay@pvalyou.com

**Comment by naoki623** [comment]
感谢您的来信，我已成功收取。
