### ISSUE TITLE
When should we instantiate sentence_encoder with BERTEncoder and BERTEntityEncoder, respectively?

### ISSUE THREAD

**Issue by dr-GitHub-account** [thunlp/OpenNRE#366]
In your paper that presents OpenNRE, "BERT" and "BERT-Entity" are discussed, representing different output taken for classification. I am wondering if BERTEncoder corresponds to "BERT" and BERTEntityEncoder corresponds to "BERT-Entity"?

**Comment by demerzel-iv** [comment]
That's right
