### ISSUE TITLE
关于包级关系提取任务

### ISSUE THREAD

**Issue by LDLINGLINGLING** [thunlp/OpenNRE#367]
请问包级的是用的哪一个？是否在这个package里面给了？另外这个基于BERT的包级关系提取任务的准确率和F1分数分别达到多少了，我在论文中没有找到相关数据？
非常感谢您的分享，在论文中已强烈推荐

**Comment by demerzel-iv** [comment]
包级的模型是`opennre.model.BagAttention`，`opennre.model.BagOne`和`opennre.model.BagAverage`
