### ISSUE TITLE
这个软件包是不兼容win平台吗

### ISSUE THREAD

**Issue by tianyudizhua** [thunlp/OpenNRE#370]
path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by HomeRedTony** [comment]
好像是的，一些环境变量windows不支持

**Comment by JJchiang189** [comment]
@tianyudizhua maybe this blog could help you out: https://blog.csdn.net/MasterChiang/article/details/128190557?spm=1001.2014.3001.5501

**Comment by THUCSTHanxu13** [comment]
因为windows上有些操作不太好进行，之前对windows的支持不是很好，我们尽快加一些模块。如果稳定使用，建议还是用linux会更稳妥点。
