### ISSUE TITLE
Chinese pretrained models links broken?

### ISSUE THREAD

**Issue by mikeleatila** [thunlp/OpenNRE#371]
Hi, I wanted to download Chinese pretrained models 'people_chinese_bert_softmax' or 'people_delunknown_chinese_bert_softmax', however these links seem not to be active anymore (below). Is there an alternative link where I can fetch them? Many thanks in advance

https://thunlp.oss-cn-qingdao.aliyuncs.com/opennre/ckpt/people_chinese_bert_softmax.pth.tar
https://thunlp.oss-cn-qingdao.aliyuncs.com/opennre/ckpt/people_delunknown_chinese_bert_softmax.pth.tar

**Comment by mikeleatila** [comment]
Or in case you have some other Chinese pretrained models available - could you share them please?

**Comment by THUCSTHanxu13** [comment]
However, we have not provided these Chinese models in the OpenNRE toolkit. Could you provide more details about these Chinese models?
