### ISSUE TITLE
Is downloading/using pretained models of opennre wiki80_bert_softmax links broken? I'm not able to use the opennre models, it was working fine until yesterday.

### ISSUE THREAD

**Issue by sushmithushara** [thunlp/OpenNRE#375]

**Comment by demerzel-iv** [comment]
You may check whether the file '$HOME/.opennre/pretrain/nre/wiki80_bert_softmax.pth.tar' exists. If not,  you could download it through this link: https://thunlp.oss-cn-qingdao.aliyuncs.com/opennre/pretrain/nre/wiki80_bert_softmax.pth.tar
