### ISSUE TITLE
TypeError: Couldn't build proto file into descriptor pool: duplicate file name (sentencepiece_model.proto)

### ISSUE THREAD

**Issue by kmnhops** [thunlp/OpenNRE#376]
import opennre
model = opennre.get_model('wiki80_bert_softmax')

while excuting this code I am getting the error mentioned in the title, and yes I did downgrade my protobuf to 3.20.3. full text of error is below:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_7576\2272666047.py in <module>
----> 1 import opennre
      2 model = opennre.get_model('wiki80_bert_softmax')

C:\bernbern\relation_extraction\OpenNRE\opennre\__init__.py in <module>
      3 from __future__ import print_function
      4 
----> 5 from .pretrain import check_root, get_model, download, download_pretrain
      6 import logging
      7 import os

C:\bernbern\relation_extraction\OpenNRE\opennre\pretrain.py in <module>
----> 1 from . import encoder
      2 from . import model
      3 from . import framework
      4 import torch
      5 import os

C:\bernbern\relation_extraction\OpenNRE\opennre\encoder\__init__.py in <module>
      5 from .cnn_encoder import CNNEncoder
      6 from .pcnn_encoder import PCNNEncoder
----> 7 from .bert_encoder import BERTEncoder, BERTEntityEncoder
      8 
      9 __all__ = [

C:\bernbern\relation_extraction\OpenNRE\opennre\encoder\bert_encoder.py in <module>
      2 import torch
      3 import torch.nn as nn
----> 4 from transformers import BertModel, BertTokenizer
      5 from .base_encoder import BaseEncoder
      6 

~\AppData\Roaming\Python\Python37\site-packages\transformers\__init__.py in <module>
    133 
    134 # Pipelines
--> 135 from .pipelines import (
    136     Conversation,
    137     ConversationalPipeline,

~\AppData\Roaming\Python\Python37\site-packages\transformers\pipelines.py in <module>
     35 from .file_utils import add_end_docstrings, is_tf_available, is_torch_available
     36 from .modelcard import ModelCard
---> 37 from .tokenization_auto import AutoTokenizer
     38 from .tokenization_bert import BasicTokenizer
     39 from .tokenization_utils import PreTrainedTokenizer

~\AppData\Roaming\Python\Python37\site-packages\transformers\tokenization_auto.py in <module>
    115 
    116 if is_tokenizers_available():
--> 117     from .tokenization_albert_fast import AlbertTokenizerFast
    118     from .tokenization_bart_fast import BartTokenizerFast
    119     from .tokenization_bert_fast import BertTokenizerFast

~\AppData\Roaming\Python\Python37\site-packages\transformers\tokenization_albert_fast.py in <module>
     21 
     22 from .file_utils import is_sentencepiece_available
---> 23 from .tokenization_utils_fast import PreTrainedTokenizerFast
     24 from .utils import logging
     25 

~\AppData\Roaming\Python\Python37\site-packages\transformers\tokenization_utils_fast.py in <module>
     28 from tokenizers.decoders import Decoder as DecoderFast
     29 
---> 30 from .convert_slow_tokenizer import convert_slow_tokenizer
     31 from .file_utils import add_end_docstrings
     32 from .tokenization_utils import PreTrainedTokenizer

~\AppData\Roaming\Python\Python37\site-packages\transformers\convert_slow_tokenizer.py in <module>
     25 
     26 # from transformers.tokenization_openai import OpenAIGPTTokenizer
---> 27 from transformers.utils import sentencepiece_model_pb2 as model
     28 
     29 from .file_utils import requires_sentencepiece

~\AppData\Roaming\Python\Python37\site-packages\transformers\utils\sentencepiece_model_pb2.py in <module>
     24     syntax="proto2",
     25     serialized_pb=_b(
---> 26         '\n\x19sentencepiece_model.proto\x12\rsentencepiece"\xf4\x08\n\x0bTrainerSpec\x12\r\n\x05input\x18\x01 \x03(\t\x12\x14\n\x0cinput_format\x18\x07 \x01(\t\x12\x14\n\x0cmodel_prefix\x18\x02 \x01(\t\x12\x41\n\nmodel_type\x18\x03 \x01(\x0e\x32$.sentencepiece.TrainerSpec.ModelType:\x07UNIGRAM\x12\x18\n\nvocab_size\x18\x04 \x01(\x05:\x04\x38\x30\x30\x30\x12\x17\n\x0f\x61\x63\x63\x65pt_language\x18\x05 \x03(\t\x12 \n\x15self_test_sample_size\x18\x06 \x01(\x05:\x01\x30\x12"\n\x12\x63haracter_coverage\x18\n \x01(\x02:\x06\x30.9995\x12\x1e\n\x13input_sentence_size\x18\x0b \x01(\x05:\x01\x30\x12$\n\x16shuffle_input_sentence\x18\x13 \x01(\x08:\x04true\x12 \n\x14mining_sentence_size\x18\x0c \x01(\x05\x42\x02\x18\x01\x12"\n\x16training_sentence_size\x18\r \x01(\x05\x42\x02\x18\x01\x12(\n\x17seed_sentencepiece_size\x18\x0e \x01(\x05:\x07\x31\x30\x30\x30\x30\x30\x30\x12\x1e\n\x10shrinking_factor\x18\x0f \x01(\x02:\x04\x30.75\x12!\n\x13max_sentence_length\x18\x12 \x01(\x05:\x04\x34\x31\x39\x32\x12\x17\n\x0bnum_threads\x18\x10 \x01(\x05:\x02\x31\x36\x12\x1d\n\x12num_sub_iterations\x18\x11 \x01(\x05:\x01\x32\x12$\n\x18max_sentencepiece_length\x18\x14 \x01(\x05:\x02\x31\x36\x12%\n\x17split_by_unicode_script\x18\x15 \x01(\x08:\x04true\x12\x1d\n\x0fsplit_by_number\x18\x17 \x01(\x08:\x04true\x12!\n\x13split_by_whitespace\x18\x16 \x01(\x08:\x04true\x12)\n\x1atreat_whitespace_as_suffix\x18\x18 \x01(\x08:\x05\x66\x61lse\x12\x17\n\x0f\x63ontrol_symbols\x18\x1e \x03(\t\x12\x1c\n\x14user_defined_symbols\x18\x1f \x03(\t\x12\x1e\n\x10hard_vocab_limit\x18! \x01(\x08:\x04true\x12\x1c\n\ruse_all_vocab\x18" \x01(\x08:\x05\x66\x61lse\x12\x11\n\x06unk_id\x18( \x01(\x05:\x01\x30\x12\x11\n\x06\x62os_id\x18) \x01(\x05:\x01\x31\x12\x11\n\x06\x65os_id\x18* \x01(\x05:\x01\x32\x12\x12\n\x06pad_id\x18+ \x01(\x05:\x02-1\x12\x18\n\tunk_piece\x18- \x01(\t:\x05<unk>\x12\x16\n\tbos_piece\x18. \x01(\t:\x03<s>\x12\x17\n\teos_piece\x18/ \x01(\t:\x04</s>\x12\x18\n\tpad_piece\x18\x30 \x01(\t:\x05<pad>\x12\x1a\n\x0bunk_surface\x18, \x01(\t:\x05 \xe2\x81\x87 "5\n\tModelType\x12\x0b\n\x07UNIGRAM\x10\x01\x12\x07\n\x03\x42PE\x10\x02\x12\x08\n\x04WORD\x10\x03\x12\x08\n\x04\x43HAR\x10\x04*\t\x08\xc8\x01\x10\x80\x80\x80\x80\x02"\xd1\x01\n\x0eNormalizerSpec\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1c\n\x14precompiled_charsmap\x18\x02 \x01(\x0c\x12\x1e\n\x10\x61\x64\x64_dummy_prefix\x18\x03 \x01(\x08:\x04true\x12&\n\x18remove_extra_whitespaces\x18\x04 \x01(\x08:\x04true\x12 \n\x12\x65scape_whitespaces\x18\x05 \x01(\x08:\x04true\x12\x1e\n\x16normalization_rule_tsv\x18\x06 \x01(\t*\t\x08\xc8\x01\x10\x80\x80\x80\x80\x02"y\n\x0cSelfTestData\x12\x33\n\x07samples\x18\x01 \x03(\x0b\x32".sentencepiece.SelfTestData.Sample\x1a)\n\x06Sample\x12\r\n\x05input\x18\x01 \x01(\t\x12\x10\n\x08\x65xpected\x18\x02 \x01(\t*\t\x08\xc8\x01\x10\x80\x80\x80\x80\x02"\xba\x03\n\nModelProto\x12\x37\n\x06pieces\x18\x01 \x03(\x0b\x32\'.sentencepiece.ModelProto.SentencePiece\x12\x30\n\x0ctrainer_spec\x18\x02 \x01(\x0b\x32\x1a.sentencepiece.TrainerSpec\x12\x36\n\x0fnormalizer_spec\x18\x03 \x01(\x0b\x32\x1d.sentencepiece.NormalizerSpec\x12\x33\n\x0eself_test_data\x18\x04 \x01(\x0b\x32\x1b.sentencepiece.SelfTestData\x1a\xc8\x01\n\rSentencePiece\x12\r\n\x05piece\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x42\n\x04type\x18\x03 \x01(\x0e\x32,.sentencepiece.ModelProto.SentencePiece.Type:\x06NORMAL"J\n\x04Type\x12\n\n\x06NORMAL\x10\x01\x12\x0b\n\x07UNKNOWN\x10\x02\x12\x0b\n\x07\x43ONTROL\x10\x03\x12\x10\n\x0cUSER_DEFINED\x10\x04\x12\n\n\x06UNUSED\x10\x05*\t\x08\xc8\x01\x10\x80\x80\x80\x80\x02*\t\x08\xc8\x01\x10\x80\x80\x80\x80\x02\x42\x02H\x03'
     27     ),
     28 )

~\AppData\Roaming\Python\Python37\site-packages\google\protobuf\descriptor.py in __new__(cls, name, package, options, serialized_options, serialized_pb, dependencies, public_dependencies, syntax, pool, create_key)

TypeError: Couldn't build proto file into descriptor pool: duplicate file name (sentencepiece_model.proto)

**Comment by naoki623** [comment]
感谢您的来信，我已成功收取。

**Comment by kmnhops** [comment]
it seems like the issue is solved
