### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by kmnhops** [thunlp/OpenNRE#377]
opennre\pretain.py has a line:(12)

---> 12 default_root_path = os.path.join(os.getenv('HOME'), '.openner')

and this HOME returns NoneType rather than other values, can you tell me where are you guys trying to point so I can put the path there.

**Comment by kmnhops** [comment]
yea i think you need to tell me where you guys wanna point this

**Comment by JJchiang189** [comment]
maybe this blog could help you out : https://blog.csdn.net/MasterChiang/article/details/128190557?spm=1001.2014.3001.5501

**Comment by kmnhops** [comment]
yea awesome this will work.
