### ISSUE TITLE
import openNRE

### ISSUE THREAD

**Issue by AncyAugustine** [thunlp/OpenNRE#380]
Always gets the below error while trying to import openNRE

File ~\anaconda3\envs\env_openNRE\lib\site-packages\numpy\__init__.py:320, in __getattr__(attr)
    317     from .testing import Tester
    318     return Tester
--> 320 raise AttributeError("module {!r} has no attribute "
    321                      "{!r}".format(__name__, attr))

AttributeError: module 'numpy' has no attribute 'typeDict'

**Comment by naoki623** [comment]
感谢您的来信，我已成功收取。

**Comment by helloxcq** [comment]
Maybe you can try to use a lower version of numpy, such as `numpy == 1.21`

**Comment by naoki623** [comment]
感谢您的来信，我已成功收取。
