### ISSUE TITLE
Not able to reproduce results or make the PR Curve from files that you give

### ISSUE THREAD

**Issue by rishabhjoshi** [thunlp/OpenNRE#39]
Hi
I am using the file provided by you in out/sample_allprob_iter_10900.npy and the code provided in plot_pr.py and I am unable to reproduce the PR Curve with these files. I am also unable to train the model and reproduce the results of the paper even after using all the hyperparameters as provided in the paper and also those that have been specified in the network.py file.
Any help will be appreciated.
Thanks
Rishabh

**Comment by rishabhjoshi** [comment]
![oldshit](https://user-images.githubusercontent.com/9219492/39097328-7c2e206e-4678-11e8-8794-b6fb83bf6ede.png)

This is the curve that I am able to obtain. Clearly the area under the curve is 0.

**Comment by gaotianyu1350** [comment]
Thanks for your feedback. We have updated our project and you could try again.
