### ISSUE TITLE
question for using python3 and tensorflow r1.x

### ISSUE THREAD

**Issue by mbxmxm** [thunlp/OpenNRE#42]
我用的是python3和tensorflow r1.x，按照您的说明修改代码之后出现错误：
InvalidArgumentError (see above for traceback): axis 0 specified more than once.
[[Node: model/ReverseV2_3 = ReverseV2[T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](model/Reshape_2, model/ReverseV2_3/axis)]]
请问这是什么原因？
非常感谢！

**Comment by gaotianyu1350** [comment]
感谢你的反馈～我们的项目刚刚更新，你可以查看一下项目的最新版本。以及我们的项目要求python >= 2.7， TensorFlow >= 1.4.1，你可能需要检查一下自己的环境是否满足要求
