### ISSUE TITLE
network.py has a little bug

### ISSUE THREAD

**Issue by sy950921** [thunlp/OpenNRE#44]
Thank you for your open source codes!
When using your codes, I found a little bug in network.py.

Line72: inputs_backward = tf.concat(2,[tf.nn.embedding_lookup(word_embedding,tf.reverse(self.input_word,[False,True])),						tf.nn.embedding_lookup(pos1_embedding,tf.reverse(self.input_pos1,[False,True])),										**tf.nn.embedding_lookup(pos1_embedding,tf.reverse(self.input_pos2,[False,True]))])**

last embedding_lookup, I think it might be **pos2_embedding,tf.reverse(self.input_pos2,[False,True])**

**Comment by gaotianyu1350** [comment]
Thanks for your feedback! We have updated our project and you can check our latest version.
