### ISSUE TITLE
Feedback -- little bugs / user-friendliness...

### ISSUE THREAD

**Issue by gwohlgen** [thunlp/OpenNRE#45]
Hi, just trying it out:

Some feedback to make it more smooth for users:

1. please automatically create the 'data' directory .. else users get an exception when calling "gen_data.py"
2. in the README.md is says on should move the NYT dataset to 'origin-data', but it has to be 'origin_data'
3. please list requirements for the tool (a requirements.txt)
4. Little bug:
python train.py --model_name pcnn_att
Traceback (most recent call last):
File "train.py", line 40, in 
from framework import Framework
File "/home/wohlg/itmo/OpenNRE/framework.py", line 58
self.encoder = Encoder(is_training, FLAGS.drop_prob)
^
TabError: inconsistent use of tabs and spaces in indentation

---> please replace the tab with spaces

**Comment by gwohlgen** [comment]
Little bug:
python train.py --model_name pcnn_att
Traceback (most recent call last):
  File "train.py", line 40, in <module>
    from framework import Framework 
  File "/home/wohlg/itmo/OpenNRE/framework.py", line 58
    self.encoder = Encoder(is_training, FLAGS.drop_prob)
                                                       ^
TabError: inconsistent use of tabs and spaces in indentation

---> please replace the tab with spaces

**Comment by gaotianyu1350** [comment]
Thanks for your feedback! All the bugs are fixed and requirements are added to the readme.md. Please check our latest commit.
