### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by nimishabajpai207** [thunlp/OpenNRE#46]
Code written in the files is in python 2. Do we have to manually change everything to make it compatible with python 3?

**Comment by gaotianyu1350** [comment]
Thanks for your feedback! We will fix the compatibility problem soon. If you want to use this project in python3 now, you could try changing all 'print' to python3 style.

**Comment by gaotianyu1350** [comment]
Python3 is supported in the latest update.
