### ISSUE TITLE
Vec.txt

### ISSUE THREAD

**Issue by nimishabajpai207** [thunlp/OpenNRE#48]
Hello I am very new to this field. I wanted to know how you got the vec.txt file? If I have to train the models on my own data do I need to create my own vec.txt?

**Comment by gaotianyu1350** [comment]
We get the vec.txt file from [word2vec tool](https://code.google.com/archive/p/word2vec/). We keep the words which appear more than 100 times in the NYT corpus as vocabulary. You could get your own vec.txt for your data by using the word2vec tool.
