### ISSUE TITLE
predicted labels

### ISSUE THREAD

**Issue by nasrin-taghizadeh** [thunlp/OpenNRE#49]
Thanks for sharing OpenNRE framework. I am wondering whether I can get predicted labels for test data, instead of precision and recall of the best epoch. Could you please add this feature to the code.
Regards

**Comment by gaotianyu1350** [comment]
Hi~ thanks for your feedback. Actually, we have this feature in our code. You could get the predicted labels from `self.test_output` in `framework.py`.  `self.test_output` is calculated at line 193 (function `test_one_step`).
