### ISSUE TITLE
您好，请问一下

### ISSUE THREAD

**Issue by bianluohuan** [thunlp/OpenNRE#5]
抽取出来的结果转换为txt格式后,与哪个.txt文件的格式相同。谢谢

**Comment by Tsingularity** [comment]
您好，为了方便进行测试结果的评测，我们在测试程序中是将抽取结果存为.npy文件放在./data目录下，目前并没有提供将结果直接转化为txt文件的接口。

**Comment by bianluohuan** [comment]
谢谢了，我自己尝试一下转换

**Comment by Tsingularity** [comment]
感谢您对TensorFlow-NRE的关注和建议，我们会在之后的工作中尝试提供直接将关系抽取结果输出.txt的接口来方便大家的使用。
