### ISSUE TITLE
How to interpret test_results?

### ISSUE THREAD

**Issue by nimishabajpai207** [thunlp/OpenNRE#50]
In the test_results folder, I am getting two different numpy arrays named model_name_x and model_name_y. What do they mean? Also how do you interpret the array inside? How do we know the entities that are recognized and the relationships created for different sentences?

**Comment by gaotianyu1350** [comment]
Hi,

`model_name_x` and `model_name_y` are the coordinates of the points on the precision-recall curve of the model. They are calculated in the function `test` in `framework.py`. More specifically, first we calculate the classification probabilities of all triples (entity_head, entity_tail, relation_type), then sort the triples by their probabilities so we can get many pairs of (precision, recall). 

About your last question, I assume you are talking about how we get the dataset. The NYT dataset is a distantly supervised dataset. The entity pairs and the relations came from Freebase, and then are attached to the sentences in the NYT corpus. You can refer to [this paper](http://www.aclweb.org/anthology/P16-1200) for details.

**Comment by nimishabajpai207** [comment]
I understand. How do I understand which entities and relationships are being assigned to a test sentence? Is their a way to label the output?

**Comment by gaotianyu1350** [comment]
There is a basic assumption: If two entities participate in a relation (in a knowledge base like freebase), all sentences that mention these two entities express that relation. But it will bring lots of noisy data. You can refer to [this paper](https://pdfs.semanticscholar.org/db55/0f7af299157c67d7f1874bf784dca10ce4a9.pdf) for details about how NYT dataset was generated.
