### ISSUE TITLE
pr_curve 准确率的疑问

### ISSUE THREAD

**Issue by jcsyl** [thunlp/OpenNRE#51]
您好，这近跑了一下您这边的实验OPEN_NRE(PCNN_att 模型)，想进一步了解test.py 得到的准确率代表的含义。即如何判断模型判断正确（这里对于每对（ent1,ent2)都生成52种关系，判断是否有对应（ent1,ent2,rel_?)在测试集中，这种做法意义是什么？）以下是您的部分代码
                    for rel in range(1, len(pred)):
                        flag = int(((entity[0], entity[1], rel) in self.data_instance_triple))
                        total_recall += flag
                        test_result.append([(entity[0], entity[1], rel), flag, pred[rel]])

**Comment by gaotianyu1350** [comment]
在远监督学习中，预测的时候我们会将所有相同entity_pair的句子放在一个bag里面，而一个bag只出一个结果。所以如果关系rel出现过且其对应的预测概率大于阈值，我们就认为是成功预测出来。

这一部分只是一个预处理，后面有把所有预测的结果按照概率排序，是为了画pr曲线

关于更多的细节，可以参考[论文](http://www.aclweb.org/anthology/P16-1200)

**Comment by jcsyl** [comment]
您好，再次打扰一下，刚刚我这边已经大致看完您推给我的论文，目前有两点疑问，劳烦您给我讲解一下。
①您说过“如果关系rel出现过且其对应的预测概率大于阈值，我们就认为是成功预测出来。”在下面代码中没有体现出阈值的概率，希望这边您能够给我指出了阈值的代码所在文件
for i, item in enumerate(sorted_test_result[::-1]):#b * s * num_class    if item[1] == 1:        correct += 1    pr_result_y.append(float(correct) / (i + 1))    pr_result_x.append(float(correct) / total_recall)
②在论文中提到了P@N(n=100,200,300) 对应的测试值，这部分代码是有体现吗？跑的test.py 得到的auc~~40%,这里的0.4 代码的准确率是值什么（没有NA 关系情况下的？）

谢谢您的阅读。

**Comment by gaotianyu1350** [comment]
1. 阈值在这里是通过排序实现的。按照最后预测的概率从大到小排序之后，每枚举一项，相当于假设阈值就是这一项的概率，即这一项前面的（概率都比它大）都算预测出来，后面的都不算。

2. 这里的代码没提供P@N，auc指的是area under the curve（曲线下面积，在这里是precision-recall曲线下的面积）。是没有NA关系情况下的。

**Comment by jcsyl** [comment]
oh~ get it.  这边写的测试效果没有达到论文中的效果，如果您这边方便的话，希望发给我P@N代码做参考。2271545898@qq.com
最后，感谢辛苦解答~

**Comment by gaotianyu1350** [comment]
这一版工程里面没计算P@N，你可以参考那片论文的(原始工程)[https://github.com/thunlp/NRE]。以及如果看pr曲线的话，我们的结果是明显好于论文里面的结果的。
