### ISSUE TITLE
数据集的国内链接

### ISSUE THREAD

**Issue by zifeiYv** [thunlp/OpenNRE#53]
请问能不能给一个国内的下载链接？上网实在是不方便。

**Comment by MrXueHuan** [comment]
http://iesl.cs.umass.edu/riedel/ecml/

You can try this URL.

**Comment by gaotianyu1350** [comment]
https://cloud.tsinghua.edu.cn/f/e106518775cf4bbc9e79/?dl=1

**Comment by zifeiYv** [comment]
多谢！
