### ISSUE TITLE
处理后的数据问题

### ISSUE THREAD

**Issue by karlhugle** [thunlp/OpenNRE#54]
在文章: Neural Relation Extraction with Selective Attention over Instances 中写道

> The training data contains **522,611** sentences, 281,270 entity pairs and 18,252 relational facts. The testing set contains 172,448 sentences, 96,678 entity pairs and 1,950 relational facts.

> 另外，训练时我将和测试集中entity pair重复的部分去掉了得到的_522611_个训练样例。

您好 能分享下lin et al. 2016 ACL 里处理后的数据吗？ 感谢。 在数据处理的代码里没发现怎么实现这个步骤 ‘_和测试集中entity pair重复的部分去掉了得到的_522611个训练样例_’

或者我理解错了，望解答， 谢谢。

**Comment by THUCSTHanxu13** [comment]
https://github.com/thunlp/NRE里面好像放了最后处理的数据，原始的NYT-10数据有些奇怪的现象需要处理，比如只出现在测试集里的关系，然后同时出现在训练集与测试集的实体对，不过非常少，好像影响不大，一般处理这个数据都会把他们去掉
