### ISSUE TITLE
framework.py文件中几行代码的问题

### ISSUE THREAD

**Issue by zifeiYv** [thunlp/OpenNRE#56]
在framework.py中：
1.第245行（train()方法）：
`index = range(i * FLAGS.batch_size, (i + 1) * FLAGS.batch_size)`
range外面不加list()的话我运行会报错；
2.第247行的for循环，如果变量名仍用i，则会与外层循环冲突，导致显示异常。

**Comment by gaotianyu1350** [comment]
Thanks for your feedback! The bugs have been fixed.
