### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by luosmart** [thunlp/OpenNRE#59]
测试阶段，把隔5次的checkpoint的模型跑一次评测结果，然后选择最好的评测结果作为最终的结果。
```
if auc > best_auc:
     best_auc = auc
     best_epoch = epoch
     save_x = pr_result_x
     save_y = pr_result_y
```
常见的做法是test集只被评测一次，结果是多少就是多少；另一种做法是跑多次，取个平均值。上述代码的方案相当于把test集当作valida集，进行多次评估，选出一个最好的结果，这样的结果很可能比别人的高。
这样做是不是不合理啊？是不是需要考虑引入valid 集合呢？

**Comment by THUCSTHanxu13** [comment]
你说的是有道理的，一般测试要么是稳定训练一个固定轮数看最后效果，要么是在验证集合上操作。不过在验证集上的操作和在测试集合上进行的操作是类似的。数据集合划分需要用户自己来进行。不过引入验证集合是合理的
