### ISSUE TITLE
About test set

### ISSUE THREAD

**Issue by Faora** [thunlp/OpenNRE#60]
About 98% of the sentences' relation in the test set are NA. How do you choose the data to test?

**Comment by THUCSTHanxu13** [comment]
NYT-10 is a benchmark dataset for RE. For testing, for each sentence, you need to compute the score for each relation (except NA). In other words, if a NA sentence is predicted with other relation, it will reduce the precision. Any sentences predicted with NA will be omitted during testing.

**Comment by THUCSTHanxu13** [comment]
You can find details of the dataset from "Modeling relations and their mentions without
labeled text."

**Comment by Faora** [comment]
Thanks for the reply, this is very helpful to me.
