### ISSUE TITLE
文件夹old中的问题

### ISSUE THREAD

**Issue by zxs1995** [thunlp/OpenNRE#62]
您好，我执行了文件夹old中的train_GRU.py但是出现了这个问题，

![image](https://user-images.githubusercontent.com/26573634/44572455-70040c00-a7b6-11e8-998b-9ec2942f6ba1.png)

但是不知您那里用到了那个包，请指点一下，谢谢您
，还有可不可以请您说一下您的这个模型图

**Comment by THUCSTHanxu13** [comment]
原来那个是很多年前的版本了，现在的tf不一定能跑的了，不过不知道您需要知道模型图哪个部分
