### ISSUE TITLE
Do you re-learn position embeddings after xavier_initializer()?

### ISSUE THREAD

**Issue by ducnx** [thunlp/OpenNRE#64]
Codes on line 37, 38 of file `network/embedding.py`:
```
input_pos1 = tf.nn.embedding_lookup(pos1_embedding, self.pos1)
input_pos2 = tf.nn.embedding_lookup(pos2_embedding, self.pos2)
```
The `pos1_embedding` and `pos2_embedding` are initiated by xavier_initializer().
I cannot find out the part of the code where you modify the position embeddings later (by learning from training data), or you just use the value created by xavier_initializer(). Can you please point out the part of the code to re-learn position embeddings, or indicate where I'm misunderstanding.
Thank you very much.

**Comment by zifeiYv** [comment]
Position embedding is a way that allow your network to take the distance from current word to entity words into consideration.  Just like the word embedding, all they need to do is converting the input to numeric type so the network could  do follow-up calculations. It is a kind of representation, not a variable.
