### ISSUE TITLE
关于pcnn_att_rl的问题

### ISSUE THREAD

**Issue by zxs1995** [thunlp/OpenNRE#68]
您好，通过运行代码，发现您这块有一些问题，不知道您的num_classes这个参数多出来怎么去改，而函数no_bag中并没有num_classes这个参数。
![image](https://user-images.githubusercontent.com/26573634/45346577-1d12bd00-b5dc-11e8-9ecf-8ac722cce518.png)

**Comment by gaotianyu1350** [comment]
您好，rl部分因为还在调试，所以push上去的代码还是不完整的。建议先用pcnn_att等模块。

**Comment by zxs1995** [comment]
不好意思，请问一下大概什么时候可以调通呢

**Comment by gaotianyu1350** [comment]
我最近正在整理项目里的代码，近两三周应该就会release的

**Comment by zxs1995** [comment]
好的谢谢您~

**Comment by zxs1995** [comment]
您好~请问强化学习的那篇会在这个版本更新吗，谢谢~

**Comment by zxs1995** [comment]
您好请问强化学习的那篇会在这个版本更新吗，谢谢
