### ISSUE TITLE
[Feature Request] Cross-sentence max pooling

### ISSUE THREAD

**Issue by jasonyu1996** [thunlp/OpenNRE#71]
Hi! It has been reported in several papers that cross-sentence max pooling can outperform selective attention. It is therefore beneficial to test it.
https://www.semanticscholar.org/paper/Relation-Extraction-with-Multi-instance-Multi-label-Jiang-Wang/8731369a707046f3f8dd463d1fd107de31d40a24

**Comment by gaotianyu1350** [comment]
The feature has been implemented.

**Comment by jasonyu1996** [comment]
Great!
