### ISSUE TITLE
NYT10 Dataset + Toolkit

### ISSUE THREAD

**Issue by cgallay** [thunlp/OpenNRE#73]
Hi, could you provide a `checksum` for the `tar` located on [Tsinghua Cloud](https://cloud.tsinghua.edu.cn/f/11391e48b72749d8b60a/?dl=1) cause when I untar it I got some errors. As well if it's possible could you upload the tar on another could like google drive as the speed of Tsinghua Cloud is very slow at least for me.   

```nyt/heldout_relations/testPositive.pb
nyt/heldout_relations/trainPositive.pb
nyt/heldout_relations/trainNegative.pb
nyt/heldout_relations/testNegative.pb
tar: Skipping to next header
nyt/kb_manual/trainPositive.pb
tar: Skipping to next header
nyt/kb_manual/.DS_Store
nyt/kb_manual/trainNegative.pb
tar: Skipping to next header
nyt/kb_manual/testNewEntities.pb
nyt/kb_manual/testNewRelations.pb
tar: Skipping to next header
tar: Exiting with failure status due to previous errors```

**Comment by gaotianyu1350** [comment]
Hi sorry for the trouble. I've uploaded the tar file to Google Drive and here is the [link](https://drive.google.com/file/d/1eSGYObt-SRLccvYCsWaHx1ldurp9eDN_/view?usp=sharing).

**Comment by cgallay** [comment]
@gaotianyu1350 Thank you now it works for me :)
