### ISSUE TITLE
Prediction on new data

### ISSUE THREAD

**Issue by cgallay** [thunlp/OpenNRE#74]
Hi,

How can I use the model (once trained) to predict the label of new data?

I have been trying to do so by imitating the `test(...)` method and keeping the output. But I have been facing two issues:
 - Firstly, I am not able to map the predicted label back from the output of the model to the entities pair.
 - Secondly, I think there is a problem with the `data_loader` as it seems to me that the last batch is not returned when there isn't enough data to fully fill the batch. I totally understand this during the training phase as we don't wanna fill the batch with noisy data and we don't care about losing a few training samples. But during the inference phase, I think it would be really great to fill the batch with zeros such that we can still predict the label for the lasts entities pairs. 

Thanks for your help.

**Comment by gaotianyu1350** [comment]
The problems you've mentioned make sense and I'll add these features soon.

**Comment by cgallay** [comment]
Hey @gaotianyu1350 that's nice from you thanks for your work.
As I need it for a project, maybe I could help so that it gets faster. Any helps needed for the implementation ?

**Comment by gaotianyu1350** [comment]
I've added those features in my latest commit and hope they could be helpful. Thanks for your proposal!
