### ISSUE TITLE
Processing NYT10 data got error

### ISSUE THREAD

**Issue by CrisJk** [thunlp/OpenNRE#76]
Hi, I processed NYT10 data following the readme. When I run the 'python protobuf2json.py'. I got a TypeError:

` serialized_pb='\n\x0e\x44ocument.proto\x12\x14large_coref.protobuf\"\x97\x04\n\x08\x44ocument\x12\x10\n\x08\x66ilename\x18\x01 \x02(\t\x12:\n\tsentences\x18\x02 \x03(\x0b\x32\'.large_coref.protobuf.Document.Sentence\x1a\xb3\x01\n\x08Sentence\x12\x34\n\x06tokens\x18\x01 \x03(\x0b\x32$.large_coref.protobuf.Document.Token\x12\x38\n\x08mentions\x18\x02 \x03(\x0b\x32&.large_coref.protobuf.Document.Mention\x12\x37\n\x07\x64\x65pTree\x18\x03 \x01(\x0b\x32&.large_coref.protobuf.Document.DepTree\x1a/\n\x05Token\x12\x0c\n\x04word\x18\x01 \x02(\t\x12\x0b\n\x03tag\x18\x02 \x01(\t\x12\x0b\n\x03ner\x18\x03 \x01(\t\x1aR\n\x07Mention\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x12\n\nentityGuid\x18\x02 \x01(\t\x12\x0c\n\x04\x66rom\x18\x03 \x02(\x05\x12\n\n\x02to\x18\x04 \x02(\x05\x12\r\n\x05label\x18\x05 \x02(\t\x1a\x36\n\x07\x44\x65pTree\x12\x0c\n\x04root\x18\x01 \x02(\x05\x12\x0c\n\x04head\x18\x02 \x03(\x05\x12\x0f\n\x07relType\x18\x03 \x03(\t\x1aJ\n\x0fRelationMention\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0e\n\x06source\x18\x02 \x02(\x05\x12\x0c\n\x04\x64\x65st\x18\x03 \x02(\x05\x12\r\n\x05label\x18\x04 \x02(\t\"\xf2\x01\n\x08Relation\x12\x12\n\nsourceGuid\x18\x01 \x02(\t\x12\x10\n\x08\x64\x65stGuid\x18\x02 \x02(\t\x12\x0f\n\x07relType\x18\x03 \x02(\t\x12\x42\n\x07mention\x18\x04 \x03(\x0b\x32\x31.large_coref.protobuf.Relation.RelationMentionRef\x1ak\n\x12RelationMentionRef\x12\x10\n\x08\x66ilename\x18\x01 \x02(\t\x12\x10\n\x08sourceId\x18\x02 \x02(\x05\x12\x0e\n\x06\x64\x65stId\x18\x03 \x02(\x05\x12\x0f\n\x07\x66\x65\x61ture\x18\x04 \x03(\t\x12\x10\n\x08sentence\x18\x05 \x01(\t\"\xc3\x01\n\x06\x45ntity\x12\x0c\n\x04guid\x18\x01 \x02(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x0c\n\x04pred\x18\x04 \x01(\t\x12>\n\x07mention\x18\x05 \x03(\x0b\x32-.large_coref.protobuf.Entity.EntityMentionRef\x1a\x41\n\x10\x45ntityMentionRef\x12\x10\n\x08\x66ilename\x18\x01 \x02(\t\x12\n\n\x02id\x18\x02 \x02(\x05\x12\x0f\n\x07\x66\x65\x61ture\x18\x03 \x03(\tB6\n$cc.refectorie.proj.relation.protobufB\x0e\x44ocumentProtos')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 878, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: expected bytes, str found`

I looked the python file 'protobuf2json.py' , and find that  'serialized_pb' is an unreadable code as it saw above
Is it the python file encoding error? How can I solve this problem?
ps: my python version is Python 3.6.6, and os is macos High Sierra 10.13.6. 

Thank you very much!

**Comment by gaotianyu1350** [comment]
Hi~ The code is for Python 2.7 and maybe you could try running the code with Python 2.7
