### ISSUE TITLE
您好请问强化学习的那篇会在旧版本更新吗，谢谢

### ISSUE THREAD

**Issue by zxs1995** [thunlp/OpenNRE#77]
_Originally posted by @zxs1995 in https://github.com/thunlp/OpenNRE/issues/68#issuecomment-427704556_

**Comment by jenniferwang0709** [comment]
您好，我从OpenNRE中提供的Tsinghua Cloud下载了将NYT10转换为json数据的工具，按照README.md运行`python protobuf2json.py`报错：在文件Document_pb2.py中expected bytes, str found，请问这个问题应该如何解决？谢谢！

**Comment by gaotianyu1350** [comment]
1. 尝试一下python2或者按照readme中的指示重新生成一下Document_pb2.py
2. README中有个地方写错了，应该是运行`python protobuf2json.py .`

**Comment by LifeForSoftwore** [comment]
> 近期我们会更新上去的～

现在代码中的rl能用吗 是Jun Feng的吗？

**Comment by gaotianyu1350** [comment]
已经更新了，用法: `python train_demo.py nyt pcnn att rl`

**Comment by zxs1995** [comment]
谢谢您~ 请问您的soft-label的代码现在可以达到论文的效果吗
