### ISSUE TITLE
Data loading problem

### ISSUE THREAD

**Issue by gwohlgen** [thunlp/OpenNRE#79]
Hi guys,

today I cloned your code and wanted to apply it to a dataset which I compiled using DBpedia.
After adapting the dataset to your json-formats, when running the code, there is an exception (see below). I just changed one line in train_demo.py to point to my data directory.
As I am not such a great Python programmer, you have an idea where to start debugging, or what might be the problem?

Some help/ideas are greatly appreciated.

```
python2.7 train_demo.py
Pre-processed files exist. Loading them...
Finish loading
Total relation fact: 18409
Pre-processed files exist. Loading them...
Finish loading
Total relation fact: 1950
Start training...
2018-10-08 23:43:59.576495: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Calculating weights_table...
Traceback (most recent call last):
  File "train_demo.py", line 100, in <module>
    framework.train(model, ckpt_dir="checkpoint", model_name=dataset_name + "_" + model.encoder + "_" + model.selector, max_epoch=60, gpu_nums=1)
  File "/home/wohlg/itmo/OpenNRE_new/OpenNRE/nrekit/framework.py", line 141, in train
    cur_model = model(self.train_data_loader, self.train_data_loader.batch_size // gpu_nums, self.train_data_loader.max_length)
  File "train_demo.py", line 73, in __init__
    self._loss = nrekit.network.classifier.softmax_cross_entropy(self._train_logit, self.label, self.rel_tot, weights_table=self.get_weights())
  File "train_demo.py", line 89, in get_weights
    _weights_table[self.train_data_loader.data_rel[i]] += 1.0 
IndexError: index 48 is out of bounds for axis 0 with size 3
```
After printing i, it is 0 for the first 572 times in the loop, and then suddenly 48. Strange.
Does that mean that item 572 in train.json is broken? Looked at it, it looks normal.

**Comment by gaotianyu1350** [comment]
Hi ~ It seems that the relation id (48) is out of your total number of relations (3). The total number of relations are defined by the length of `relation2id.json`, and you should make sure that all the ids in the `relation2id.json`  are less than the length of it. For example, if there are only 3 pairs in `relation2id.json`, all the ids should be less than 3.

**Comment by gwohlgen** [comment]
Not sure if I should post here, or make a new issue, let's see.

There are only 3 ids in `rel2id.json` file:
```
$ cat rel2id.json
{   "NA": 0,
    "locatedIn": 1,
    "Unrelated": 2
}
```

Also just checked in the `train.json` and `test.json` -- only IDs 1 and 2 are used in there, no others.
I have no idea where ID 48 might come from? (It's not in my data). For word embeddings, I just copied
those from the nyt dataset).

Thanks for you help, Gerhard

**Comment by gaotianyu1350** [comment]
I'm not sure what's wrong. Would you mind uploading your data to Google Drive and let me debug on it?

**Comment by gwohlgen** [comment]
Thanks a lot, sent it to you by email.

**Comment by gaotianyu1350** [comment]
The problem has been fixed. One needs to clear _processed_data after changing datasets.
