### ISSUE TITLE
关于shuffle数据的一个小问题

### ISSUE THREAD

**Issue by CrisJk** [thunlp/OpenNRE#80]
你好，在看你们代码的时候发现，data_loader.next_batch中，似乎是通过打乱order数组进行数据的shuffle,但在MODE_INSTANCE模式下，只是对原来的数据直接切片 ,而没有用到order数组。

请问是不需要进行shuffle？或者是在其他地方进行了shuffle？
谢谢解答

**Comment by gaotianyu1350** [comment]
测试的时候就不需要shuffle了，因为shuffle不shuffle对结果没影响
