### ISSUE TITLE
nyt data?

### ISSUE THREAD

**Issue by wenston123** [thunlp/OpenNRE#81]
就是数据集的包就一个word_vec.json，也没有包的工具说明啊？？希望楼主更新一下信息，

**Comment by gaotianyu1350** [comment]
在项目README里 Provided Data > NYT10 Dataset 这一栏里面给了google drive 和 tsinghua cloud的数据的链接。数据解压之后里面有关于数据的readme，包括详细的格式说明以及如何用原始数据处理出要求的json格式的数据。

**Comment by gaotianyu1350** [comment]
请问你用的google drive的链接还是tsinghua cloud的链接，我印象中两个上传的是一样的而且都包含readme和数据。
