### ISSUE TITLE
利用protoc将NYT数据转为json格式问题

### ISSUE THREAD

**Issue by jenniferwang0709** [thunlp/OpenNRE#83]
您好，感谢您的建议，python2对我来说不可行，因此试着重新生成‘Documen_pb2.py’，我成功下载了protoc这个工具，运行`protoc --protoc_path=. --python_out=. Document.proto`，之后运行`python protobuf2json.py .`,报错信息为`File "protobuf2json.py", line15,in get_entities
guid,word,type = line.split('\t`)  TypeError: a bytes-like object is required, not 'str'， 跟之前的报错信息类似，应该是出现了str类型数据，但是需要的是bytes-like，请问这个问题是什么原因导致的，我应该如何排查，谢谢！

**Comment by gaotianyu1350** [comment]
将第12行的f = open(file_name, 'rb')改成f = open(file_name, 'r')即可

**Comment by jenniferwang0709** [comment]
Thanks a lot! It works for me.
