### ISSUE TITLE
请问如何应用在纯文本中，谢谢

### ISSUE THREAD

**Issue by MelvinZang** [thunlp/OpenNRE#91]
请问训练结果可以应用在没有实体标注的纯文本中吗？

**Comment by THUCSTHanxu13** [comment]
关系抽取任务需要先标注实体，我们实现的一系列模型都是输入一句话以及这句话的标注实体来判别关系的。纯文本的话需要进行处理，即使不是监督数据也要是半监督的数据。

**Comment by MelvinZang** [comment]
请问测试数据集上标注了实体，没有标注关系，如何使用训练好的模型进行标注？

**Comment by MelvinZang** [comment]
@THUCSTHanxu13
