### ISSUE TITLE
No such file or directory: '_processed_data\\data\\nyt\\train_word.npy'

### ISSUE THREAD

**Issue by waithope** [thunlp/OpenNRE#92]
when I run `python train_demo.py nyt pcnn att`
I got this error:
Loading data file...
Finish loading
Loading word vector file...
Finish loading
Elimiating case sensitive problem...
Finish eliminating
Sort data...
Finish sorting
Got 114042 words of 50 dims
Building word vector matrix and mapping...
Finish building
Pre-processing data...
Finish pre-processing
Storing processed files...
Traceback (most recent call last):
  File "train_demo.py", line 19, in <module>
    shuffle=True)
  File "D:\VscodeProject\Python\OpenNRE\nrekit\data_loader.py", line 390, in __init__
    np.save(os.path.join(processed_data_dir, name_prefix + '_word.npy'), self.data_word)
  File "D:\Usr_Local\Python\Python36-64\lib\site-packages\numpy\lib\npyio.py", line 492, in save
    fid = open(file, "wb")
FileNotFoundError: [Errno 2] No such file or directory: '_processed_data\\data\\nyt\\train_word.npy'

Python version : 3.6.2 64bit 
Environment : Windows

**Comment by gaotianyu1350** [comment]
It seems to be the problem of file creation authority on Windows. You can try it on Linux or manually create those folders in the OpenNRE directory: `_processed_data/data/nyt`
