### ISSUE TITLE
Need to see output for plain sentence

### ISSUE THREAD

**Issue by renukaswamy** [thunlp/OpenNRE#93]
Hello respected,
I found this OpenNRE/oldversion, repository very insightful for my academic research purpose. Thanks for the detailed steps and insights in terms of code.
I have successfully executed this repo. 
{
**pcnn_att : auc = 0.3531428653149488 | max F1 = 0.41485148514851483
    P@100: 0.7722772277227723 | P@200: 0.7064676616915423 | P@300: 0.6611295681063123 | Mean: 0.7132914858402088**
}
**I would like to know, how can i feed the plain sentence to the test model to see relations extracted out of it.** 
(input : **sentence**)
(output: **relation tuple**)
It would be really great help to see your reply. My advance respect towards your time and suggestions.

best,
Renuk

**Comment by MelvinZang** [comment]
I want to know, too. After I recognized entities, how can I see relations in sentences.

**Comment by AbhishekPatnaik** [comment]
yeah even i want to know that

**Comment by gaotianyu1350** [comment]
Sorry for the late reply. On master branch, you can use `pred_result` in `nrekit/framework.py:251` to see relation predict result. For now there hasn't been a very convenient interface to input the sentences and entities and get the relations, so you need to modify the code a little to get what you want.
