### ISSUE TITLE
Python版本问题

### ISSUE THREAD

**Issue by charlesfufu** [thunlp/OpenNRE#95]
楼主为啥不考虑更新一些代码版本到python3，如果还有还原到python27去运行代码感觉不科学！！

**Comment by charlesfufu** [comment]
![image](https://user-images.githubusercontent.com/33311822/48328535-5cfb2c80-e67f-11e8-83cb-7041ab867636.png)

**Comment by SilenceWinter** [comment]
我也想提这个问题。。。。这兼容性

**Comment by Chenny0808** [comment]
unicode("", "utf-8")  修改为 str("utf-8")就可解决
更新下protobuf 包：pip install --upgrade protobuf
