### ISSUE TITLE
关于数据格式（测试集合没有label应怎么处理）的问题

### ISSUE THREAD

**Issue by zzbzzb1413** [thunlp/OpenNRE#98]
您好，感谢大神课题组的分享！

请问测试文件如果没有label，只是为了生成测试结果，是不是只需保证输入格式和训练数据一样，至于标签head tail 以及关系relation是空的就好了？
以及，训练文本如果是中文，该怎么处理原数据呢，每一个字之间都分开吗？

期待回复，谢谢！

**Comment by gaotianyu1350** [comment]
如果只是要测试结果，relation可以随便设，head / tail 要提供（许多NLP工具包都提供named entity recognition的功能）。

中文的话我暂时还没有试过，理论上把每个字用空格隔开就可以了。

**Comment by zzbzzb1413** [comment]
谢谢您的回复！ 我想的是，中文的话，应该是把分词结果隔开，毕竟实体都不是一个词呀。 另外一个我想请教的是，对于一个没有标注的语料，首先要做的是把潜在可能有关系的实体对找出来，如果只是在测试数据中定位训练数据的实体，然后在一定长度范围内实体随机配对，感觉这样盲目性太大了。 这个有什么合理的策略嘛？ 十分感谢！！ 805946712 邮箱805946712@qq.com 签名由 网易邮箱大师 定制 在2018年11月23日 09:06，Tianyu Gao 写道： 如果只是要测试结果，relation可以随便设，head / tail 要提供（许多NLP工具包都提供named entity recognition的功能）。 中文的话我暂时还没有试过，理论上把每个字用空格隔开就可以了。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by zzbzzb1413** [comment]
谢谢您，所以我可以这样理解吗，把出现过的实体当做自定义词表，进行分词，输入数据中分词结果用空格隔开（毕竟实体是一个词而不是一个字），整理好数据格式输入模型就OK啦？

**Comment by gaotianyu1350** [comment]
分词的话直接用专门的分词工具就可以了，不是把实体当自定义词表。用命名实体识别的工具去找出句子中的实体，后面就跟英文的做法一样了
